from collections import OrderedDict

SETUP = OrderedDict()
EXCLUSIVE = OrderedDict()
NON_EXCLUSIVE = OrderedDict()
PLACEHOLDERS = OrderedDict()
CMIMPORT_SETUP = OrderedDict()

# APPLICATION           PROFILES                                                 START_SLEEP,  STOP_SLEEP(SEC)
#  -------------------------------------------------------------------------------------------------------

exclusive = EXCLUSIVE["EXCLUSIVE"] = OrderedDict()
exclusive["APT_01"] =                                                                   (5,          5)
exclusive["HA_01"] =                                                                    (5,          5)
exclusive["CMIMPORT_14"] =                                                              (5,          5)
exclusive["CMIMPORT_02"] =                                                              (5,          5)
exclusive["CMIMPORT_04"] =                                                              (5,          5)
exclusive["AP_01"] =                                                                    (5,          5)
#  -------------------------------------------------------------------------------------------------------
setup = SETUP["SETUP"] = OrderedDict()
setup["AP_SETUP"] =                                                                     (5,       5)
setup["SHM_SETUP"] =                                                                    (5,       5)
setup["NHM_SETUP"] =                                                                    (5,       5)
setup["NHM_REST_NBI_SETUP"] =                                                           (5,       5)
setup["NETVIEW_SETUP"] =                                                                (5,       5)


setup["FM_0506"] =                                                                      (5,       5)
setup["AID_SETUP"] =                                                                    (5,       5)
setup["CMSYNC_SETUP"] =                                                                 (5,       5)
setup['CBRS_SETUP'] =                                                                   (5,       5)
setup["FTPES_01"] =                                                                     (5,       5)
#  -------------------------------------------------------------------------------------------------------
pm_rest_nbi = NON_EXCLUSIVE["PM_REST_NBI"] = OrderedDict()
pm_rest_nbi["PM_REST_NBI_01"] =                                                            (10,       5)
pm_rest_nbi["PM_REST_NBI_02"] =                                                            (10,       5)
#  -------------------------------------------------------------------------------------------------------
pm = NON_EXCLUSIVE["PM"] = OrderedDict()
pm["PM_11"] =                                                                           (10,      5)
pm["PM_40"] =                                                                           (10,      5)
pm["PM_25"] =                                                                           (10,      5)
pm["PM_31"] =                                                                           (10,      5)
pm["PM_27"] =                                                                           (10,      5)
pm["PM_02"] =                                                                           (10,      5)
pm["PM_29"] =                                                                           (10,      5)
pm["PM_16"] =                                                                           (10,      5)
pm["PM_20"] =                                                                           (10,      5)
pm["PM_03"] =                                                                           (10,      5)
pm["PM_19"] =                                                                           (10,      5)
pm["PM_30"] =                                                                           (10,      5)
pm["PM_38"] =                                                                           (10,      5)
pm["PM_24"] =                                                                           (10,      5)
pm["PM_50"] =                                                                           (10,      5)
pm["PM_48"] =                                                                           (10,      5)
pm["PM_32"] =                                                                           (10,      5)
pm["PM_47"] =                                                                           (10,      5)
pm["PM_15"] =                                                                           (10,      5)
pm["PM_42"] =                                                                           (10,      5)
pm["PM_46"] =                                                                           (10,      5)
pm["PM_52"] =                                                                           (10,      5)
pm["PM_51"] =                                                                           (10,      5)
pm["PM_26"] =                                                                           (10,      5)
pm["PM_06"] =                                                                           (10,      5)
pm["PM_44"] =                                                                           (10,      5)
pm["PM_04"] =                                                                           (10,      5)
pm["PM_17"] =                                                                           (10,      5)
pm["PM_53"] =                                                                           (10,      5)
pm["PM_54"] =                                                                           (10,      5)
pm["PM_55"] =                                                                           (10,      5)
pm["PM_56"] =                                                                           (10,      5)
pm["PM_57"] =                                                                           (10,      5)
pm["PM_58"] =                                                                           (10,      5)
pm["PM_59"] =                                                                           (10,      5)
pm["PM_60"] =                                                                           (10,      5)
pm["PM_61"] =                                                                           (10,      5)
pm["PM_62"] =                                                                           (10,      5)
pm["PM_63"] =                                                                           (10,      5)
pm["PM_64"] =                                                                           (10,      5)
pm["PM_65"] =                                                                           (10,      5)
pm["PM_66"] =                                                                           (10,      5)
pm["PM_67"] =                                                                           (10,      5)
pm["PM_68"] =                                                                           (10,      5)
pm["PM_69"] =                                                                           (10,      5)
pm["PM_70"] =                                                                           (10,      5)
pm["PM_71"] =                                                                           (10,      5)
pm["PM_72"] =                                                                           (10,      5)
pm["PM_73"] =                                                                           (10,      5)
pm["PM_74"] =                                                                           (10,      5)
pm["PM_75"] =                                                                           (10,      5)
pm["PM_76"] =                                                                           (10,      5)
pm["PM_77"] =                                                                           (10,      5)
pm["PM_78"] =                                                                           (10,      5)
pm["PM_79"] =                                                                           (10,      5)
pm["PM_80"] =                                                                           (10,      5)
pm["PM_81"] =                                                                           (10,      5)
pm["PM_82"] =                                                                           (10,      5)
pm["PM_83"] =                                                                           (10,      5)
pm["PM_84"] =                                                                           (10,      5)
pm["PM_85"] =                                                                           (10,      5)
pm["PM_86"] =                                                                           (10,      5)
pm["PM_87"] =                                                                           (10,      5)
pm["PM_88"] =                                                                           (10,      5)
pm["PM_89"] =                                                                           (10,      5)
pm["PM_90"] =                                                                           (10,      5)
pm["PM_91"] =                                                                           (10,      5)
pm["PM_92"] =                                                                           (10,      5)
pm["PM_93"] =                                                                           (10,      5)
pm["PM_94"] =                                                                           (10,      5)
pm["PM_95"] =                                                                           (10,      5)
pm["PM_96"] =                                                                           (10,      5)
pm["PM_97"] =                                                                           (10,      5)
pm["PM_98"] =                                                                           (10,      5)
pm["PM_99"] =                                                                           (10,      5)
pm["PM_49"] =                                                                           (10,      5)
pm["PM_100"] =                                                                           (10,      5)
pm["PM_101"] =                                                                           (10,      5)
pm["PM_102"] =                                                                           (10,      5)
pm["PM_103"] =                                                                           (10,      5)
pm["PM_104"] =                                                                           (10,      5)
# --------------------------------------------------------------------------------------------------------
cmsync = NON_EXCLUSIVE["CMSYNC"] = OrderedDict()
cmsync["CMSYNC_01"] =                                                                   (5,      5)
cmsync["CMSYNC_02"] =                                                                   (5,      5)
cmsync["CMSYNC_04"] =                                                                   (5,      5)
cmsync["CMSYNC_06"] =                                                                   (5,      5)
cmsync["CMSYNC_15"] =                                                                   (5,      5)
cmsync["CMSYNC_19"] =                                                                   (5,      5)
cmsync["CMSYNC_20"] =                                                                   (5,      5)
cmsync["CMSYNC_23"] =                                                                   (5,      5)
cmsync["CMSYNC_24"] =                                                                   (5,      5)
cmsync["CMSYNC_25"] =                                                                   (5,      5)
cmsync["CMSYNC_26"] =                                                                   (5,      5)
cmsync["CMSYNC_28"] =                                                                   (5,      5)
cmsync["CMSYNC_29"] =                                                                   (5,      5)
cmsync["CMSYNC_30"] =                                                                   (5,      5)
cmsync["CMSYNC_32"] =                                                                   (5,      5)
cmsync["CMSYNC_33"] =                                                                   (5,      5)
cmsync["CMSYNC_34"] =                                                                   (5,      5)
cmsync["CMSYNC_35"] =                                                                   (5,      5)
cmsync["CMSYNC_37"] =                                                                   (5,      5)
cmsync["CMSYNC_38"] =                                                                   (5,      5)
cmsync["CMSYNC_39"] =                                                                   (5,      5)
cmsync["CMSYNC_40"] =                                                                   (5,      5)
cmsync["CMSYNC_41"] =                                                                   (5,      5)
cmsync["CMSYNC_42"] =                                                                   (5,      5)
cmsync["CMSYNC_43"] =                                                                   (5,      5)
cmsync["CMSYNC_44"] =                                                                   (5,      5)
cmsync["CMSYNC_45"] =                                                                   (5,      5)
#  -------------------------------------------------------------------------------------------------------
pkiadmin = NON_EXCLUSIVE["PKIADMIN"] = OrderedDict()
pkiadmin["PKIADMIN_01"] =                                                               (10,      5)
#  -------------------------------------------------------------------------------------------------------
fm = NON_EXCLUSIVE["FM"] = OrderedDict()
fm["FM_01"] =                                                                           (10,     5)
fm["FM_02"] =                                                                           (10,     5)
fm["FM_03"] =                                                                           (10,     5)
fm["FM_08"] =                                                                           (10,     5)
fm["FM_09"] =                                                                           (10,     5)
fm["FM_10"] =                                                                           (10,     5)
fm["FM_11"] =                                                                           (10,     5)
fm["FM_12"] =                                                                           (10,     5)
fm["FM_14"] =                                                                           (10,     5)
fm["FM_15"] =                                                                           (10,     5)
fm["FM_17"] =                                                                           (10,     5)
fm["FM_20"] =                                                                           (10,     5)
fm["FM_21"] =                                                                           (10,     5)
fm["FM_25"] =                                                                           (10,     5)
fm["FM_26"] =                                                                           (10,     5)
fm["FM_27"] =                                                                           (10,     5)
fm["FM_31"] =                                                                           (10,     5)
fm["FM_32"] =                                                                           (10,     5)
#  -------------------------------------------------------------------------------------------------------
enmcli = NON_EXCLUSIVE["ENMCLI"] = OrderedDict()
enmcli["ENMCLI_01"] =                                                                   (5,       5)
enmcli["ENMCLI_02"] =                                                                   (5,       5)
enmcli["ENMCLI_03"] =                                                                   (5,       5)
enmcli["ENMCLI_05"] =                                                                   (5,       5)
enmcli["ENMCLI_06"] =                                                                   (5,       5)
enmcli["ENMCLI_07"] =                                                                   (5,       5)
enmcli["ENMCLI_08"] =                                                                   (5,       5)
enmcli["ENMCLI_09"] =                                                                   (5,       5)
enmcli["ENMCLI_10"] =                                                                   (5,       5)
#  -------------------------------------------------------------------------------------------------------
cmimport = NON_EXCLUSIVE["CMIMPORT"] = OrderedDict()
cmimport["CMIMPORT_01"] =                                                               (5,      5)
cmimport["CMIMPORT_03"] =                                                               (5,      5)
cmimport["CMIMPORT_05"] =                                                               (5,      5)
cmimport["CMIMPORT_08"] =                                                               (5,      5)
cmimport["CMIMPORT_10"] =                                                               (5,      5)
cmimport["CMIMPORT_11"] =                                                               (5,      5)
cmimport["CMIMPORT_12"] =                                                               (5,      5)
cmimport["CMIMPORT_13"] =                                                               (5,      5)
cmimport["CMIMPORT_15"] =                                                               (5,      5)
cmimport["CMIMPORT_16"] =                                                               (5,      5)
cmimport["CMIMPORT_17"] =                                                               (5,      5)
cmimport["CMIMPORT_18"] =                                                               (5,      5)
cmimport["CMIMPORT_19"] =                                                               (5,      5)
cmimport["CMIMPORT_20"] =                                                               (5,      5)
cmimport["CMIMPORT_21"] =                                                               (5,      5)
cmimport["CMIMPORT_22"] =                                                               (5,      5)
cmimport["CMIMPORT_23"] =                                                               (5,      5)
cmimport["CMIMPORT_24"] =                                                               (5,      5)
cmimport["CMIMPORT_25"] =                                                               (5,      5)
cmimport["CMIMPORT_26"] =                                                               (5,      5)
cmimport["CMIMPORT_27"] =                                                               (5,      5)
cmimport["CMIMPORT_28"] =                                                               (5,      5)
cmimport["CMIMPORT_29"] =                                                               (5,      5)
cmimport["CMIMPORT_30"] =                                                               (5,      5)
cmimport["CMIMPORT_31"] =                                                               (5,      5)
cmimport["CMIMPORT_32"] =                                                               (5,      5)
cmimport["CMIMPORT_33"] =                                                               (5,      5)
cmimport["CMIMPORT_34"] =                                                               (5,      5)
cmimport["CMIMPORT_35"] =                                                               (5,      5)
# --------------------------------------------------------------------------------------------------------
shm = NON_EXCLUSIVE["SHM"] = OrderedDict()
shm["SHM_01"] =                                                                         (10,      5)
shm["SHM_02"] =                                                                         (10,      5)
shm["SHM_06"] =                                                                         (10,      5)
shm["SHM_03"] =                                                                         (10,      5)
shm["SHM_04"] =                                                                         (10,      5)
shm["SHM_05"] =                                                                         (10,      5)
shm["SHM_07"] =                                                                         (10,      5)
shm["SHM_18"] =                                                                         (10,      5)
shm["SHM_19"] =                                                                         (10,      5)
shm["SHM_20"] =                                                                         (10,      5)
shm["SHM_21"] =                                                                         (10,      5)
shm['SHM_23'] =                                                                         (10,      5)
shm["SHM_24"] =                                                                         (10,      5)
shm["SHM_25"] =                                                                         (10,      5)
shm["SHM_26"] =                                                                         (10,      5)
shm["SHM_27"] =                                                                         (10,      5)
shm["SHM_28"] =                                                                         (10,      5)
shm["SHM_31"] =                                                                         (10,      5)
shm["SHM_32"] =                                                                         (10,      5)
shm["SHM_33"] =                                                                         (10,      5)
shm["SHM_34"] =                                                                         (10,      5)
shm["SHM_35"] =                                                                         (10,      5)
shm["SHM_36"] =                                                                         (10,      5)
shm["SHM_37"] =                                                                         (10,      5)
shm["SHM_39"] =                                                                         (10,      5)
shm["SHM_40"] =                                                                         (10,      5)
shm["SHM_41"] =                                                                         (10,      5)
shm["SHM_42"] =                                                                         (10,      5)
shm["SHM_43"] =                                                                         (10,      5)
shm["SHM_44"] =                                                                         (10,      5)
shm["SHM_45"] =                                                                         (10,      5)
shm["SHM_46"] =                                                                         (10,      5)
shm["SHM_47"] =                                                                         (10,      5)
#  -------------------------------------------------------------------------------------------------------
fmx = NON_EXCLUSIVE["FMX"] = OrderedDict()
fmx["FMX_01"] =                                                                         (10,      5)
fmx["FMX_05"] =                                                                         (10,      5)
#  -------------------------------------------------------------------------------------------------------
logviewer = NON_EXCLUSIVE["LOGVIEWER"] = OrderedDict()
logviewer["LOGVIEWER_01"] =                                                             (5,       5)
#  -------------------------------------------------------------------------------------------------------
netex = NON_EXCLUSIVE["NETEX"] = OrderedDict()
netex["NETEX_02"] =                                                                     (10,      5)
netex["NETEX_01"] =                                                                     (10,      5)
netex["NETEX_03"] =                                                                     (10,      5)
netex["NETEX_04"] =                                                                     (10,      5)
netex["NETEX_05"] =                                                                     (10,      5)
netex["NETEX_07"] =                                                                     (10,      5)
netex["NETEX_08"] =                                                                     (10,      5)
#  -------------------------------------------------------------------------------------------------------
netview = NON_EXCLUSIVE["NETVIEW"] = OrderedDict()
netview["NETVIEW_01"] =                                                                 (10,      5)
netview["NETVIEW_02"] =                                                                 (10,      5)
#  -------------------------------------------------------------------------------------------------------
nhm = NON_EXCLUSIVE["NHM"] = OrderedDict()
nhm["NHM_03"] =                                                                         (10,      5)
nhm["NHM_04"] =                                                                         (10,      5)
nhm['NHM_05'] =                                                                         (10,      5)
nhm["NHM_06"] =                                                                         (10,      5)
nhm["NHM_07"] =                                                                         (10,      5)
nhm["NHM_08"] =                                                                         (10,      5)
nhm["NHM_09"] =                                                                         (10,      5)
nhm["NHM_10"] =                                                                         (10,      5)
nhm["NHM_11"] =                                                                         (10,      5)
nhm["NHM_12"] =                                                                         (10,      5)
nhm["NHM_13"] =                                                                         (10,      5)
nhm["NHM_14"] =                                                                         (10,      5)
# --------------------------------------------------------------------------------------------------------
nhm_rest_nbi = NON_EXCLUSIVE["NHM_REST_NBI"] = OrderedDict()
nhm_rest_nbi["NHM_REST_NBI_01"] =                                                       (10,      5)
nhm_rest_nbi["NHM_REST_NBI_02"] =                                                       (10,      5)
nhm_rest_nbi["NHM_REST_NBI_03"] =                                                       (10,      5)
nhm_rest_nbi["NHM_REST_NBI_04"] =                                                       (10,      5)
nhm_rest_nbi["NHM_REST_NBI_05"] =                                                       (10,      5)
nhm_rest_nbi["NHM_REST_NBI_06"] =                                                       (10,      5)
nhm_rest_nbi["NHM_REST_NBI_07"] =                                                       (10,      5)
nhm_rest_nbi["NHM_REST_NBI_08"] =                                                       (10,      5)
# --------------------------------------------------------------------------------------------------------
ebsl = NON_EXCLUSIVE["EBSL"] = OrderedDict()
ebsl["EBSL_05"] =                                                                       (5,       5)
ebsl["EBSL_06"] =                                                                       (5,       5)
ebsl["EBSL_01"] =                                                                       (5,       5)
#  -------------------------------------------------------------------------------------------------------
ebsn = NON_EXCLUSIVE["EBSN"] = OrderedDict()
ebsn["EBSN_01"] =                                                                       (5,      10)
ebsn["EBSN_03"] =                                                                       (5,      10)
ebsn["EBSN_04"] =                                                                       (5,      10)
ebsn["EBSN_05"] =                                                                       (5,      10)
#  -------------------------------------------------------------------------------------------------------
ebsm = NON_EXCLUSIVE["EBSM"] = OrderedDict()
ebsm["EBSM_04"] =                                                                       (5,       5)
#  -------------------------------------------------------------------------------------------------------
ap = NON_EXCLUSIVE["AP"] = OrderedDict()
ap["AP_11"] =                                                                           (5,       5)
ap["AP_12"] =                                                                           (5,       5)
ap["AP_13"] =                                                                           (5,       5)
ap["AP_14"] =                                                                           (5,       5)
ap["AP_15"] =                                                                           (5,       5)
ap["AP_16"] =                                                                           (5,       5)
#  -------------------------------------------------------------------------------------------------------
aid = NON_EXCLUSIVE["AID"] = OrderedDict()
aid["AID_01"] =                                                                         (5,       5)
aid["AID_02"] =                                                                         (5,       5)
aid["AID_03"] =                                                                         (5,       5)
aid["AID_04"] =                                                                         (5,       5)
#  -------------------------------------------------------------------------------------------------------
nhc = NON_EXCLUSIVE["NHC"] = OrderedDict()
nhc["NHC_01"] =                                                                         (5,       5)
nhc["NHC_02"] =                                                                         (5,       5)
nhc["NHC_04"] =                                                                         (5,       5)
#  -------------------------------------------------------------------------------------------------------
amos = NON_EXCLUSIVE["AMOS"] = OrderedDict()
amos["AMOS_01"] =                                                                       (5,       5)
amos["AMOS_02"] =                                                                       (5,       5)
amos["AMOS_03"] =                                                                       (5,       5)
amos["AMOS_04"] =                                                                       (5,       5)
amos["AMOS_05"] =                                                                       (5,       5)
amos["AMOS_08"] =                                                                       (5,       5)
amos["AMOS_09"] =                                                                       (5,       5)
# --------------------------------------------------------------------------------------------------------
asr_l = NON_EXCLUSIVE["ASR_L"] = OrderedDict()
asr_l["ASR_L_01"] =                                                                       (5,       5)
# ---------------------------------------------------------------------------------------------------------
asr_n = NON_EXCLUSIVE["ASR_N"] = OrderedDict()
asr_n["ASR_N_01"] =                                                                       (5,       5)
# --------------------------------------------------------------------------------------------------------
asu = NON_EXCLUSIVE["ASU"] = OrderedDict()
asu["ASU_01"] =                                                                         (5,       5)
#  -------------------------------------------------------------------------------------------------------
doc = NON_EXCLUSIVE["DOC"] = OrderedDict()
doc["DOC_01"] =                                                                         (5,      5)
#  -------------------------------------------------------------------------------------------------------
em = NON_EXCLUSIVE["EM"] = OrderedDict()
em["EM_01"] =                                                                           (5,      10)
#---------------------------------------------------------------------------------------------------------
esm = NON_EXCLUSIVE["ESM"] = OrderedDict()
esm["ESM_01"] =                                                                         (5,       5)
esm["ESM_NBI_01"] =                                                                         (5,       5)
#  -------------------------------------------------------------------------------------------------------
ops = NON_EXCLUSIVE["OPS"] = OrderedDict()
ops["OPS_01"] =                                                                          (5,     5)
#  -------------------------------------------------------------------------------------------------------
cli_mon = NON_EXCLUSIVE["CLI_MON"] = OrderedDict()
cli_mon["CLI_MON_01"] =                                                                 (10,      5)
cli_mon["CLI_MON_03"] =                                                                 (10,      5)
#  -------------------------------------------------------------------------------------------------------
cmexport = NON_EXCLUSIVE["CMEXPORT"] = OrderedDict()
cmexport["CMEXPORT_01"] =                                                               (10,      5)
cmexport["CMEXPORT_02"] =                                                               (10,      5)
cmexport["CMEXPORT_03"] =                                                               (10,      5)
cmexport["CMEXPORT_05"] =                                                               (10,      5)
cmexport["CMEXPORT_07"] =                                                               (10,      5)
cmexport["CMEXPORT_08"] =                                                               (10,      5)
cmexport["CMEXPORT_11"] =                                                               (10,      5)
cmexport["CMEXPORT_12"] =                                                               (10,      5)
cmexport["CMEXPORT_13"] =                                                               (10,      5)
cmexport["CMEXPORT_14"] =                                                               (10,      5)
cmexport["CMEXPORT_16"] =                                                               (10,      5)
cmexport["CMEXPORT_17"] =                                                               (10,      5)
cmexport["CMEXPORT_18"] =                                                               (10,      5)
cmexport["CMEXPORT_19"] =                                                               (10,      5)
cmexport["CMEXPORT_20"] =                                                               (10,      5)
cmexport["CMEXPORT_21"] =                                                               (10,      5)
cmexport["CMEXPORT_22"] =                                                               (10,      5)
cmexport["CMEXPORT_23"] =                                                               (10,      5)
cmexport["CMEXPORT_25"] =                                                               (10,      5)
cmexport["CMEXPORT_26"] =                                                               (10,      5)
cmexport["CMEXPORT_27"] =                                                               (10,      5)
#  -------------------------------------------------------------------------------------------------------
top = NON_EXCLUSIVE["TOP"] = OrderedDict()
top["TOP_01"] =                                                                         (5,       5)
#  -------------------------------------------------------------------------------------------------------
lkf = NON_EXCLUSIVE["LKF"] = OrderedDict()
lkf["LKF_01"] =                                                                         (10,       10)
#  ------------------------------------------------------------------------------------------------------
ncm_mef_lcm = NON_EXCLUSIVE["NCM_MEF_LCM"] = OrderedDict()
ncm_mef_lcm["NCM_MEF_LCM_01"] =                                                                   (10,        5)
#  -------------------------------------------------------------------------------------------------------
ncm_l3_vpn = NON_EXCLUSIVE["NCM_L3_VPN"] = OrderedDict()
ncm_l3_vpn["NCM_L3_VPN_01"] =                                                                   (10,        5)
#  -------------------------------------------------------------------------------------------------------
ncm_mef = NON_EXCLUSIVE["NCM_MEF"] = OrderedDict()
ncm_mef["NCM_MEF_01"] =                                                                   (10,        5)
ncm_mef["NCM_MEF_02"] =                                                                   (10,        5)
ncm_mef["NCM_MEF_03"] =                                                                   (10,        5)
#  -------------------------------------------------------------------------------------------------------
ncm_vpn_sd = NON_EXCLUSIVE["NCM_VPN_SD"] = OrderedDict()
ncm_vpn_sd["NCM_VPN_SD_01"] =                                                                   (10,        5)
#  -------------------------------------------------------------------------------------------------------
nodesec = NON_EXCLUSIVE["NODESEC"] = OrderedDict()
nodesec["NODESEC_03"] =                                                                 (10,      5)
nodesec["NODESEC_01"] =                                                                 (10,      5)
nodesec["NODESEC_02"] =                                                                 (10,      5)
nodesec["NODESEC_04"] =                                                                 (10,      5)
nodesec["NODESEC_08"] =                                                                 (10,      5)
nodesec["NODESEC_11"] =                                                                 (10,      5)
nodesec["NODESEC_13"] =                                                                 (10,      5)
nodesec["NODESEC_15"] =                                                                 (10,      5)
nodesec["NODESEC_16"] =                                                                 (10,      5)
nodesec["NODESEC_17"] =                                                                 (10,      5)
nodesec["NODESEC_18"] =                                                                 (10,      5)
#  -------------------------------------------------------------------------------------------------------
npa = NON_EXCLUSIVE["NPA"] = OrderedDict()
npa["NPA_01"] =                                                                         (5,       5)
#  -------------------------------------------------------------------------------------------------------
nvs = NON_EXCLUSIVE["NVS"] = OrderedDict()
nvs["NVS_01"] =                                                                         (10,      5)
nvs["NVS_02"] =                                                                         (10,      5)
#  -------------------------------------------------------------------------------------------------------
nodecli = NON_EXCLUSIVE["NODECLI"] = OrderedDict()
nodecli["NODECLI_01"] =                                                                 (5,       5)
#  -------------------------------------------------------------------------------------------------------
cmevents_nbi = NON_EXCLUSIVE["CMEVENTS_NBI"] = OrderedDict()
cmevents_nbi["CMEVENTS_NBI_01"] =                                                       (5,       5)
cmevents_nbi["CMEVENTS_NBI_02"] =                                                       (5,       5)
#  -------------------------------------------------------------------------------------------------------
parmgt = NON_EXCLUSIVE["PARMGT"] = OrderedDict()
parmgt["PARMGT_01"] =                                                                   (5,       5)
parmgt["PARMGT_02"] =                                                                   (5,       5)
parmgt["PARMGT_03"] =                                                                   (5,       5)
parmgt["PARMGT_04"] =                                                                   (5,       5)
#  -------------------------------------------------------------------------------------------------------
configuration_template = NON_EXCLUSIVE["CONFIGURATION_TEMPLATE"] = OrderedDict()
#  -------------------------------------------------------------------------------------------------------
launcher = NON_EXCLUSIVE["LAUNCHER"] = OrderedDict()
launcher["LAUNCHER_01"] =                                                               (5,       5)
launcher["LAUNCHER_02"] =                                                               (5,       5)
launcher["LAUNCHER_03"] =                                                               (5,       5)
#  -------------------------------------------------------------------------------------------------------
plm = NON_EXCLUSIVE["PLM"] = OrderedDict()
plm["PLM_01"] =                                                                         (5,       5)
plm["PLM_02"] =                                                                         (5,       5)
#  -------------------------------------------------------------------------------------------------------
geo_r = NON_EXCLUSIVE["GEO_R"] = OrderedDict()
geo_r["GEO_R_01"] =                                                                     (5,       5)
#  -------------------------------------------------------------------------------------------------------
cell_mgt = NON_EXCLUSIVE["CELLMGT"] = OrderedDict()
cell_mgt["CELLMGT_01"] =                                                                (5,      5)
cell_mgt["CELLMGT_02"] =                                                                (5,      5)
cell_mgt["CELLMGT_03"] =                                                                (5,      5)
cell_mgt["CELLMGT_05"] =                                                                (5,      5)
cell_mgt["CELLMGT_07"] =                                                                (5,      5)
cell_mgt["CELLMGT_08"] =                                                                (5,      5)
cell_mgt["CELLMGT_09"] =                                                                (5,      5)
cell_mgt["CELLMGT_10"] =                                                                (5,      5)
cell_mgt["CELLMGT_11"] =                                                                (5,      5)
cell_mgt["CELLMGT_12"] =                                                                (5,      5)
cell_mgt["CELLMGT_13"] =                                                                (5,      5)
cell_mgt["CELLMGT_14"] =                                                                (5,      5)
cell_mgt["CELLMGT_15"] =                                                                (5,      5)
# --------------------------------------------------------------------------------------------------------
cbrs = NON_EXCLUSIVE["CBRS"] = OrderedDict()
# --------------------------------------------------------------------------------------------------------
ca = NON_EXCLUSIVE["CA"] = OrderedDict()
ca["CA_01"] =                                                                           (5,       5)
# --------------------------------------------------------------------------------------------------------
network = NON_EXCLUSIVE["NETWORK"] = OrderedDict()
network['NETWORK_01'] =                                                                (5,      5)
network['NETWORK_02'] =                                                                (5,      5)
network['NETWORK_03'] =                                                                (5,      5)
# --------------------------------------------------------------------------------------------------------
reparenting = NON_EXCLUSIVE["REPARENTING"] = OrderedDict()
reparenting["REPARENTING_01"] =                                                         (5,       5)
reparenting["REPARENTING_02"] =                                                         (5,       5)
reparenting["REPARENTING_03"] =                                                         (5,       5)
reparenting["REPARENTING_04"] =                                                         (5,       5)
reparenting["REPARENTING_05"] =                                                         (5,       5)
reparenting["REPARENTING_06"] =                                                         (5,       5)
reparenting["REPARENTING_07"] =                                                         (5,       5)
reparenting["REPARENTING_08"] =                                                         (5,       5)
reparenting["REPARENTING_09"] =                                                         (5,       5)
reparenting["REPARENTING_10"] =                                                         (5,       5)
reparenting["REPARENTING_11"] =                                                         (5,       5)
reparenting["REPARENTING_12"] =                                                         (5,       5)
# --------------------------------------------------------------------------------------------------------
dynamic_crud = NON_EXCLUSIVE["DYNAMIC_CRUD"] = OrderedDict()
dynamic_crud["DYNAMIC_CRUD_01"] =                                                       (5,       5)
dynamic_crud["DYNAMIC_CRUD_02"] =                                                       (5,       5)
dynamic_crud["DYNAMIC_CRUD_03"] =                                                       (5,       5)
dynamic_crud["DYNAMIC_CRUD_04"] =                                                       (5,       5)
dynamic_crud["DYNAMIC_CRUD_05"] =                                                       (5,       5)
# --------------------------------------------------------------------------------------------------------
neo4j = NON_EXCLUSIVE["NEO4J"] = OrderedDict()
neo4j["NEO4J_01"] =                                                                     (5,       5)
neo4j["NEO4J_02"] =                                                                     (5,       5)
# --------------------------------------------------------------------------------------------------------
fan = NON_EXCLUSIVE["FAN"] = OrderedDict()
fan["FAN_11"] =                                                                           (10,      5)
fan["FAN_12"] =                                                                           (10,      5)
fan["FAN_13"] =                                                                           (10,      5)
fan["FAN_14"] =                                                                           (10,      5)
# --------------------------------------------------------------------------------------------------------
nas_outage = NON_EXCLUSIVE["NAS_OUTAGE"] = OrderedDict()
nas_outage["NAS_OUTAGE_01"] =                                                                           (10,      5)
nas_outage["NAS_OUTAGE_02"] =                                                                           (10,      5)
# --------------------------------------------------------------------------------------------------------
nas_outage = NON_EXCLUSIVE["LT_SYSLOG_STREAM"] = OrderedDict()
nas_outage["LT_SYSLOG_STREAM_01"] =                                                                           (10,      5)
# --------------------------------------------------------------------------------------------------------
sev = NON_EXCLUSIVE["SEV"] = OrderedDict()
sev["SEV_01"] =                                                                           (5,      5)
sev["SEV_02"] =                                                                           (5,      5)
# --------------------------------------------------------------------------------------------------------
fs_quotas = NON_EXCLUSIVE["FS_QUOTAS"] = OrderedDict()
fs_quotas["FS_QUOTAS_01"] =                                                                           (5,      5)
# --------------------------------------------------------------------------------------------------------
secui = NON_EXCLUSIVE["SECUI"] = OrderedDict()
secui["SECUI_03"] =                                                                     (5,       5)
secui["SECUI_06"] =                                                                     (5,       5)
secui["SECUI_07"] =                                                                     (5,       5)
secui["SECUI_08"] =                                                                     (5,       5)
secui["SECUI_09"] =                                                                     (5,       5)
secui["SECUI_10"] =                                                                     (5,       5)
secui["SECUI_12"] =                                                                     (5,       5)
secui["SECUI_02"] =                                                                     (5,       5)
secui["SECUI_01"] =                                                                     (5,       5)
secui["SECUI_05"] =                                                                     (120,     5)
#
# Don't Schedule after secui 01/secui_05
#
#
placeholders = PLACEHOLDERS["PLACEHOLDERS"] = OrderedDict()
placeholders["CMSYNC_21"] =                                                             (1,     1)
placeholders["CMSYNC_22"] =                                                             (1,     1)
placeholders["BUR_02"] =                                                                (1,     1)
placeholders["MIGRATION_01"] =                                                          (1,     1)
placeholders["MIGRATION_02"] =                                                          (1,     1)
placeholders["MIGRATION_03"] =                                                          (1,     1)
placeholders["ENMCLI_04"] =                                                             (1,     1)
placeholders["ESM_02"] =                                                                (1,     1)
placeholders["LCM_01"] =                                                                (1,     1)
placeholders['FM_23'] =                                                                 (1,     1)
placeholders['FM_24'] =                                                                 (1,     1)
placeholders['NETWORK_03'] =                                                            (1,     1)
placeholders["CELLMGT_03"] =                                                            (1,     1)
placeholders["CELLMGT_05"] =                                                            (1,     1)
placeholders['PM_35'] =                                                                 (1,     1)
placeholders['PARMGT_01'] =                                                             (1,     1)
placeholders["SECUI_11"] =                                                              (1,     1)
placeholders["CMSYNC_27"] =                                                             (0,     0)
placeholders["FM_28"] =                                                                 (0,     0)
placeholders["FM_29"] =                                                                 (0,     0)
placeholders["CMSYNC_11"] =                                                             (0,     0)
placeholders["FAN_01"] =                                                                (0,     0)
placeholders["FAN_02"] =                                                                (0,     0)
placeholders["FAN_03"] =                                                                (0,     0)
placeholders["FAN_04"] =                                                                (0,     0)
placeholders["PM_28"] =                                                                (0,     0)
placeholders["PM_45"] =                                                                (0,     0)

WORKLOAD = [EXCLUSIVE, SETUP, NON_EXCLUSIVE, PLACEHOLDERS]
