from basic_network import (IMP_EXP_KEYS as IMP_EXP, USER_KEYS as USER, NODE_KEYS as NODE, TIME_KEYS as TIME,
                           NUM_EVENTS, THREAD_QUEUE_TIMEOUT, MAX_NODES, MAX_NODES_TO_ALLOCATE, SKIP_SYNC_CHECK,
                           NeTypesEnum as NODES, TIMEOUT, AMOS_USER_ROLES, COM_ROLES, OPS_USER_ROLES,
                           CNX_RULEMODULES, NSX_RULEMODULES, GRX_RULEMODULES, FMX_RULEMODULES, LTE_CELL_CHECK,
                           CHECK_NODE_SYNC)
from profile_cmds import (CMSYNC_MCD_BURST_MO_TYPE_SETTINGS,
                          BSC_AVC_BURST_MO_TYPE_SETTINGS, CMSYNC_AVC_BURST_MO_TYPE_SETTINGS)

SCHEDULED_DAYS, SCHEDULE_SLEEP, SCHEDULED_TIMES_STRINGS = TIME
NUM_USERS, USER_ROLES = USER
NUM_NODES, SUPPORTED_NODE_TYPES, TOTAL_NODES, EXCLUDE_NODES_FROM, NODE_FILTER = NODE
INTERFACE, FILETYPE, FLOW, IMPORT_TYPE, CREATE_DELETE_LIVE, CREATE_DELETE_CONFIG, UPDATE_LIVE, UPDATE_CONFIG = IMP_EXP
TOTAL_TARGET_ALARMS = 186240
FM_02_TOTAL_ALARMS = 4 * 5 * 60 * 24 * 4
FM_03_TOTAL_ALARMS = 4 * 60 * 8 * 20

extra_small_network = {
    "extra_small_network": {
        "amos": {
            'AMOS_01': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 5, NUM_USERS: 5, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ["AMOS_02", "AMOS_03", "AMOS_04", "AMOS_05", "AMOS_08", "ASU_01", "NPA_01"],
                        'VERIFY_TIMEOUT': 60 * 20,
                        SCHEDULED_TIMES_STRINGS: ["11:00:00", "11:30:00", "12:00:00", "12:30:00", "13:00:00",
                                                  "13:30:00", "14:00:00", "14:30:00"],
                        'COMMANDS': ["get upgradepackage", "get lp", "get pci", "get dcgm", "cabx"],
                        'COMMANDS_PER_ITERATION': 68},
            'AMOS_02': {},
            'AMOS_03': {},
            'AMOS_04': {},
            'AMOS_05': {},
            'AMOS_08': {},
            'AMOS_09': {SCHEDULE_SLEEP: 60 * 60 * 24, EXCLUDE_NODES_FROM: ["ASU_01", "NPA_01"]},
        },
        "aid": {
            'AID_01': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], TOTAL_NODES: 40, NUM_USERS: 1,
                       USER_ROLES: ['AutoId_Administrator'],
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}}, 'AID_PROFILE_SLEEP': 30,
                       SCHEDULED_TIMES_STRINGS: ['00:15:00', '01:15:00', '02:15:00', '03:15:00', '04:15:00',
                                                 '05:15:00', '06:15:00', '07:15:00', '08:15:00', '09:15:00',
                                                 '10:15:00', '11:15:00', '12:15:00', '13:15:00', '14:15:00',
                                                 '15:15:00', '16:15:00', '17:15:00', '18:15:00', '19:15:00',
                                                 '20:15:00', '21:15:00', '22:15:00', '23:15:00']},
        },
        "ap": {
            'AP_SETUP': {},
            'AP_01': {},
            'AP_11': {},
            'AP_12': {},
            'AP_13': {},
            'AP_14': {},
            'AP_15': {},
            'AP_16': {},
        },
        "apt": {
            'APT_01': {},
        },
        "asr_l": {
            'ASR_L_01': {},
        },
        "asr_n": {
            'ASR_N_01': {},
        },
        "asu": {},
        "bur": {},
        "ca": {
            'CA_01': {}
        },
        "cbrs": {
            'CBRS_SETUP': {}
        },
        "cellmgt": {
            'CELLMGT_01': {},
            'CELLMGT_02': {},
            'CELLMGT_03': {},
            'CELLMGT_05': {},
            'CELLMGT_07': {},
            'CELLMGT_08': {},
            'CELLMGT_09': {},
            'CELLMGT_10': {},
            'CELLMGT_11': {},
            'CELLMGT_12': {},
            'CELLMGT_13': {},
            'CELLMGT_14': {},
            'CELLMGT_15': {}
        },
        "cli_mon": {
            'CLI_MON_03': {SCHEDULE_SLEEP: 60 * 60 * 2}
        },
        "cmevents_nbi": {
            'CMEVENTS_NBI_01': {SCHEDULE_SLEEP: 60, NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"],
                                'EVENT_LIMIT': 10000}
        },
        "cmexport": {
            'CMEXPORT_01': {SCHEDULED_TIMES_STRINGS: ["06:00:00", "22:00:00"], 'FILETYPE': '3GPP',
                            'NODE_REGEX': '*LTE*;*dg2*', NUM_USERS: 1, USER_ROLES: ['Cmedit_Operator']},
            'CMEXPORT_02': {},
            'CMEXPORT_03': {},
            'CMEXPORT_05': {},
            'CMEXPORT_07': {},
            'CMEXPORT_08': {},
            'CMEXPORT_11': {},
            'CMEXPORT_12': {
                "ENM_NE_TYPES": [NODES.ERBS, NODES.RADIONODE, NODES.RBS, NODES.RNC, NODES.SGSN_MME, NODES.MGW,
                                 NODES.BSC],
                SCHEDULED_TIMES_STRINGS: ["18:00:00"], 'FILETYPE': 'dynamic',
                'NODE_BATCH_SIZE': 500, NUM_USERS: 1, USER_ROLES: ['CM_REST_Administrator'],
                INTERFACE: 'NBI', SCHEDULED_DAYS: ['SUNDAY', 'TUESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY']},
            'CMEXPORT_13': {},
            'CMEXPORT_14': {},
            'CMEXPORT_16': {},
            'CMEXPORT_17': {NUM_USERS: 1, USER_ROLES: ['Cmedit_Operator', 'CM_REST_Administrator'],
                            'FILE_RETENTION_TIME': 30 * 60, SCHEDULE_SLEEP: 15 * 60},
            'CMEXPORT_18': {},
            'CMEXPORT_19': {},
            'CMEXPORT_20': {},
            'CMEXPORT_21': {},
            'CMEXPORT_22': {},
            'CMEXPORT_25': {},
            'CMEXPORT_26': {}
        },
        "cmimport": {
            'CMIMPORT_01': {},
            'CMIMPORT_02': {TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                            'BATCH_MO_SIZE': 50, USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            'MO_VALUES': {'EUtranCellRelation': 12, 'UtranCellRelation': 12, 'GeranCellRelation': 6},
                            'MOS_ATTRS': {'UtranCellRelation': ['externalUtranCellFDDRef', 'UtranCellRelationId'],
                                          'EUtranCellRelation': ['EUtranCellRelationId', 'neighborCellRef'],
                                          'GeranCellRelation': ['GeranCellRelationId']},
                            EXCLUDE_NODES_FROM: ['CMSYNC_02'],
                            SCHEDULED_TIMES_STRINGS: ['00:30:01', '01:30:01', '02:30:01', '03:30:01', '04:30:01',
                                                      '05:30:01', '06:30:01', '07:30:01', '08:30:01', '09:30:01'],
                            FILETYPE: 'dynamic', INTERFACE: 'NBIv2', FLOW: 'live_config',
                            IMPORT_TYPE: CREATE_DELETE_LIVE, TIMEOUT: 15 * 60,
                            "MAPPING_FOR_5G_NODE_MO": {'UtranCellRelation': {'NRCellRelation': 15},
                                                       'EUtranCellRelation': {'EUtranCellRelation': 15}},
                            "MAPPING_FOR_5G_NODE_ATTRS": {'EUtranCellRelation': ['isRemoveAllowed',
                                                                                 'neighborCellRef',
                                                                                 'eUtranCellRelationId'],
                                                          'NRCellRelation': ['nRCellRelationId', 'nRCellRef',
                                                                             'nRFreqRelationRef']}},
            'CMIMPORT_03': {},
            'CMIMPORT_04': {},
            'CMIMPORT_05': {'MO_VALUES': {'UtranFreqRelation': 6, 'EUtranFreqRelation': 4},
                            'MOS_ATTRS': {'UtranFreqRelation': ['userLabel'], 'EUtranFreqRelation': ['userLabel']},
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ['02:20:01', '10:00:01'],
                            'BATCH_MO_SIZE': 25, TOTAL_NODES: 25, SUPPORTED_NODE_TYPES: [NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                            FILETYPE: '3GPP', FLOW: 'live_config', INTERFACE: 'NBIv2', IMPORT_TYPE: UPDATE_LIVE,
                            'MOS_DEFAULT': {'UtranFreqRelation': ('userLabel', 'cmimport_05_default'),
                                            'EUtranFreqRelation': ('userLabel', 'cmimport_05_default')},
                            'MOS_MODIFY': {'UtranFreqRelation': ('userLabel', 'cmimport_05_changes'),
                                           'EUtranFreqRelation': ('userLabel', 'cmimport_05_changes')},
                            TIMEOUT: 45 * 60, EXCLUDE_NODES_FROM: ["NODESEC_13"]},
            'CMIMPORT_08': {},
            'CMIMPORT_11': {},
            'CMIMPORT_12': {},
            'CMIMPORT_13': {},
            'CMIMPORT_14': {},
            'CMIMPORT_15': {},
            'CMIMPORT_16': {},
            'CMIMPORT_17': {},
            'CMIMPORT_18': {},
            'CMIMPORT_19': {},
            'CMIMPORT_20': {},
            'CMIMPORT_21': {},
            'CMIMPORT_22': {},
            'CMIMPORT_23': {},
            'CMIMPORT_24': {},
            'CMIMPORT_25': {},
            'CMIMPORT_26': {},
            'CMIMPORT_27': {}
        },
        "cmsync": {
            'CMSYNC_SETUP': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], SCHEDULE_SLEEP: 24 * 24 * 60,
                             "MSCM_RATIO": 0.5, "MSCMCE_RATIO": 0.5, "MAX_MOS_PER_RNC": 200, "VALUES_PER_PROFILE":
                                 {"CMSYNC_01": 0.0132, "CMSYNC_02": 0.6997, "CMSYNC_04": 0.1435, "CMSYNC_06": 0.1436},
                             "MAX_MOS_MSCMCE": 20000},
            'CMSYNC_01': {NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                          "BURST_TYPE": "MCD", "ME_TYPE_NODES_PERCENTAGE": {},
                          'NOTIFICATION_INFO': CMSYNC_MCD_BURST_MO_TYPE_SETTINGS,
                          EXCLUDE_NODES_FROM: ["CMIMPORT_01", "CMIMPORT_02", "CMIMPORT_03", "CMIMPORT_08",
                                               "CMIMPORT_11", "CMIMPORT_12", "CMIMPORT_13", "CMIMPORT_17", "TOP_01",
                                               "CMSYNC_02", "CMSYNC_04", "CMSYNC_06", "CELLMGT_01", "CELLMGT_02"],
                          LTE_CELL_CHECK: True, 'CELL_CARDINALITY_NES': [NODES.ERBS, NODES.RADIONODE],
                          SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                    for minute in range(0, 60, 30)],
                          'BURST_DURATION': 1800, "NO_UPGIND": True},
            'CMSYNC_02': {NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                          'CELL_CARDINALITY_NES': [NODES.ERBS, NODES.RADIONODE], LTE_CELL_CHECK: True,
                          SCHEDULE_SLEEP: 1800,
                          EXCLUDE_NODES_FROM: ["CMIMPORT_01", "CMIMPORT_02", "CMIMPORT_03", "CMIMPORT_08",
                                               "CMIMPORT_11", "CMIMPORT_12", "CMIMPORT_13", "CMIMPORT_17", "TOP_01",
                                               "CMSYNC_01", "CMSYNC_04", "CMSYNC_06", "CELLMGT_01", "CELLMGT_02"],
                          'NOTIFICATION_INFO': CMSYNC_AVC_BURST_MO_TYPE_SETTINGS, "BURST_TYPE": "AVC",
                          'BURST_DURATION': 1800},
            'CMSYNC_04': {NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                          SCHEDULE_SLEEP: 900, 'BURST_DURATION': 300, "BURST_TYPE": "AVC",
                          EXCLUDE_NODES_FROM: ["CMIMPORT_01", "CMIMPORT_02", "CMIMPORT_03", "CMIMPORT_08",
                                               "CMIMPORT_11", "CMIMPORT_12", "CMIMPORT_13", "CMIMPORT_17", "TOP_01",
                                               "CMSYNC_02", "CMSYNC_01", "CMSYNC_06", "CELLMGT_01", "CELLMGT_02"],
                          LTE_CELL_CHECK: True, 'NOTIFICATION_INFO': CMSYNC_AVC_BURST_MO_TYPE_SETTINGS},
            'CMSYNC_06': {NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                          SCHEDULE_SLEEP: 14400, 'BURST_DURATION': 120, "BURST_TYPE": "AVC",
                          EXCLUDE_NODES_FROM: ["CMIMPORT_01", "CMIMPORT_02", "CMIMPORT_03", "CMIMPORT_08",
                                               "CMIMPORT_11", "CMIMPORT_12", "CMIMPORT_13", "CMIMPORT_17", "TOP_01",
                                               "CMSYNC_02", "CMSYNC_04", "CMSYNC_01", "CELLMGT_01", "CELLMGT_02"],
                          LTE_CELL_CHECK: True, 'NOTIFICATION_INFO': CMSYNC_AVC_BURST_MO_TYPE_SETTINGS,
                          SCHEDULED_TIMES_STRINGS: ["23:45:00", "03:45:00", "07:45:00", "11:45:00",
                                                    "15:45:00", "19:45:00"]},
            'CMSYNC_11': {},
            'CMSYNC_15': {},
            'CMSYNC_19': {NUM_NODES: {NODES.RBS: 1}, SCHEDULED_TIMES_STRINGS: ["20:55:00"]},
            'CMSYNC_20': {NUM_NODES: {NODES.RNC: 1}, SCHEDULED_TIMES_STRINGS: ["23:55:00"]},
            'CMSYNC_21': {},
            'CMSYNC_22': {},
            'CMSYNC_25': {},
            'CMSYNC_26': {},
            'CMSYNC_28': {},
            'CMSYNC_29': {MAX_NODES_TO_ALLOCATE: 1, NUM_NODES: {NODES.BSC: -1}, SCHEDULED_TIMES_STRINGS: ["19:30:00"],
                          "BSC_250_CELL": True, EXCLUDE_NODES_FROM: ["CMIMPORT_19", "CMIMPORT_21", "CMIMPORT_22"]},
            'CMSYNC_30': {},
            'CMSYNC_32': {NUM_NODES: {NODES.BSC: -1}, 'AVG_PER_CELL_PER_SEC': 0.000231481, SCHEDULE_SLEEP: 1800,
                          'NOTIFICATION_INFO': BSC_AVC_BURST_MO_TYPE_SETTINGS, 'BURST_DURATION': 1800},
            'CMSYNC_35': {},
            'CMSYNC_37': {},
            'CMSYNC_38': {},
            'CMSYNC_39': {},
            'CMSYNC_40': {},
            'CMSYNC_41': {},
            'CMSYNC_42': {},
            'CMSYNC_44': {}
        },
        "configuration_template": {},
        "doc": {
            'DOC_01': {NUM_USERS: 1, USER_ROLES: ["OPERATOR"], SCHEDULE_SLEEP: 60 * 60}
        },
        "dynamic_crud": {
            'DYNAMIC_CRUD_01': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 5},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                SCHEDULE_SLEEP: 30 * 60,
                                "REQ_COUNTS": {"REQ_1_2_3": 3, "REQ_4_5_6": 16,
                                               "REQ_7": 1, "REQ_8": 1, "REQ_9": 1, "REQ_10": 1}},
            'DYNAMIC_CRUD_02': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], SCHEDULE_SLEEP: 1728},
            'DYNAMIC_CRUD_03': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 5},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                SCHEDULED_TIMES_STRINGS: ["09:30:00", "21:30:00"], "NUMBER_OF_THREADS": 2,
                                "REQ_COUNTS": {"REQ_1_2_3": 16}, EXCLUDE_NODES_FROM: ["DYNAMIC_CRUD_05"],
                                "NODES_PER_HOST": 2, MAX_NODES: 2},
            'DYNAMIC_CRUD_04': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 5},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                SCHEDULED_TIMES_STRINGS: ["03:30:00", "07:30:00", "11:30:00", "15:30:00", "19:30:00",
                                                          "23:30:00"],
                                "NUMBER_OF_THREADS": 5, "REQ_COUNTS": {"REQ_1_2_3": 125}},
            'DYNAMIC_CRUD_05': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 2},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                "NUMBER_OF_THREADS": 1, SCHEDULED_TIMES_STRINGS: ["02:30:00", "14:30:00"],
                                "REQ_COUNTS": {"PATCH": 1}, EXCLUDE_NODES_FROM: ["DYNAMIC_CRUD_03"],
                                "NODES_PER_HOST": 1, MAX_NODES: 1}
        },
        "ebsl": {
            'EBS_L_05': {},
            'EBS_L_06': {},
        },
        "ebsn": {
            'EBS_N_01': {},
            'EBS_N_03': {},
            'EBS_N_04': {},
            'EBS_N_05': {},
        },
        "ebsm": {
            'EBS_M_04': {},
        },
        "em": {
            'EM_01': {SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_Indoor], TOTAL_NODES: 100, NUM_USERS: 1,
                      'TOTAL_NODES_NON_RACK': 1, 'NUM_USERS_RACK': 100,
                      SCHEDULED_TIMES_STRINGS: ["00:30:00", "06:30:00", "12:30:00", "18:30:00"],
                      "PARALLEL_SESSIONS_LAUNCH": 1,
                      USER_ROLES: ['Element_Manager_Operator', 'ENodeB_Application_Administrator',
                                   'GNodeB_Application_Administrator', 'Network_Explorer_Operator',
                                   'RemoteDesktop_Operator', 'DesktopSession_Administrator']}
        },
        "esm": {
            'ESM_01': {NUM_USERS: 2, SCHEDULED_TIMES_STRINGS: ['00:00:00', '06:00:00', '12:00:00', '18:00:00'],
                       'THREAD_QUEUE_TIMEOUT': 60 * 60}
        },
        "esm_nbi": {},
        "enmcli": {
            'ENMCLI_01': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], TOTAL_NODES: 1, NUM_USERS: 1,
                          NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}}, LTE_CELL_CHECK: True,
                          USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator'],
                          SCHEDULE_SLEEP: 60 * 60},
            'ENMCLI_02': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], TOTAL_NODES: 1, NUM_USERS: 1,
                          NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                          USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator'],
                          SCHEDULE_SLEEP: 60 * 15, EXCLUDE_NODES_FROM: ["TOP_01"], LTE_CELL_CHECK: True},
            'ENMCLI_03': {},
            'ENMCLI_05': {},
            'ENMCLI_06': {},
            'ENMCLI_07': {},
            'ENMCLI_08': {},
        },
        "fm": {
            'FM_01': {
                SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672,
                                       NODES.BSC, NODES.SIU02, NODES.SGSN_MME, NODES.CCDM], 'AML_RATIO': 0.5,
                'DURATION': 3660, SCHEDULE_SLEEP: 3600, EXCLUDE_NODES_FROM: ["FM_02", "FM_03"],
                'AML_RATE': 0.01, NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                TOTAL_NODES: 10, 'BSC_BURST_RATE': 0.038, 'MSC_BURST_RATE': 0.038,
                'FM_01_TOTAL_ALARMS': TOTAL_TARGET_ALARMS - (FM_02_TOTAL_ALARMS + FM_03_TOTAL_ALARMS),
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('EXTERNAL ALARM', 'major'),
                    ('CCITT7 SIGNALLING LINK FAILURE', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_02': {
                SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672,
                                       NODES.BSC, NODES.SIU02, NODES.SGSN_MME, NODES.CCDM],
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                TOTAL_NODES: 45, 'BURST_RATE': 4, 'DURATION': 300, SCHEDULE_SLEEP: 900,
                EXCLUDE_NODES_FROM: ["FM_01", "FM_03"], 'AML_RATE': 0.5, 'AML_RATIO': 0.5,
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('EXTERNAL ALARM', 'major'),
                    ('CCITT7 SIGNALLING LINK FAILURE', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_03': {
                SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672,
                                       NODES.BSC, NODES.SIU02, NODES.SGSN_MME, NODES.CCDM],
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                TOTAL_NODES: 160, 'BURST_RATE': 20, 'DURATION': 240, 'AML_RATE': 1.0, 'AML_RATIO': 0.5,
                SCHEDULED_TIMES_STRINGS: ['00:00:00', '02:45:00', '06:00:00', '09:35:00', '12:10:00',
                                          '14:45:00', '18:00:00', '21:00:00'],
                EXCLUDE_NODES_FROM: ["FM_01", "FM_02"],
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('EXTERNAL ALARM', 'major'),
                    ('CCITT7 SIGNALLING LINK FAILURE', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_0506': {
                NUM_NODES: {NODES.ERBS: -1, NODES.RADIONODE: -1, NODES.MGW: -1, NODES.ROUTER6672: -1, NODES.RNC: -1,
                            NODES.RBS: -1, NODES.BSC: -1,
                            NODES.MSC_DB_BSP: -1, NODES.MSC_BC_IS: -1, NODES.SIU02: -1, NODES.SGSN_MME: -1,
                            NODES.CCDM: -1},
                USER_ROLES: ["FM_Administrator"], NUM_USERS: 1,
                'SETUP_STEPS': {"CEASE_ALARM": True, "AUTO_ACK": True, "DELAYED_ACK": True}},
            'FM_08': {TOTAL_NODES: 20, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.ROUTER6672,
                                                              NODES.CCDM],
                      NUM_USERS: 1,
                      'NUM_USERS_1': 2, 'NUM_USERS_2': 1, USER_ROLES: ["FM_Operator"], 'ALARM_MONITOR_SLEEP': 5 * 60,
                      SCHEDULE_SLEEP: 60 * 15},
            'FM_09': {TOTAL_NODES: 20, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.ROUTER6672,
                                                              NODES.CCDM],
                      NUM_USERS: 1,
                      USER_ROLES: ["FM_Operator"], 'ALARM_MONITOR_SLEEP': 60, SCHEDULE_SLEEP: 60 * 15},
            'FM_10': {NUM_NODES: {}, NUM_USERS: 1, USER_ROLES: ["FM_Administrator"],
                      SCHEDULED_TIMES_STRINGS: ["10:00:00"],
                      SCHEDULED_DAYS: ["THURSDAY"]},
            'FM_11': {NUM_USERS: 1, USER_ROLES: ["FM_Operator"], SCHEDULE_SLEEP: 60 * 60 * 2},
            'FM_12': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'TIMEOUT_SUBSCRIPTION': 60 * 24,
                      'NUMBER_NBI_SUBSCRIPTIONS': 14, 'TIMEOUT': 2, 'NBI_filters': ["LTE0", "LTE1"],
                      'CORBA_ENABLED': True, 'BNSI': True, SCHEDULED_TIMES_STRINGS: ["07:00:00"]},
            'FM_14': {TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.CCDM], NUM_USERS: 1,
                      USER_ROLES: ["FM_Administrator"], SCHEDULED_TIMES_STRINGS: ["16:00:00"],
                      "TIME_SPAN": 90},
            'FM_15': {TOTAL_NODES: 20, NUM_USERS: 1,
                      SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MINI_LINK_Indoor, NODES.MINI_LINK_669x,
                                             NODES.ROUTER6672, NODES.ROUTER6675, NODES.CCDM],
                      USER_ROLES: ["FM_Administrator"], "TIME_SPAN": 90,
                      SCHEDULED_DAYS: ['WEDNESDAY'], SCHEDULED_TIMES_STRINGS: ["16:00:00"]},
            'FM_17': {NUM_USERS: 1, NUM_NODES: {}, USER_ROLES: ["FM_Administrator"],
                      SCHEDULED_TIMES_STRINGS: ["19:00:00"], "TIME_SPAN": 1},
            'FM_20': {},
            'FM_21': {NUM_USERS: 1, SCHEDULED_TIMES_STRINGS: ["05:20:00"],
                      USER_ROLES: ["FM_Administrator", "Cmedit_Administrator"]},
            'FM_25': {NUM_USERS: 3, NUM_NODES: {NODES.ERBS: 5, NODES.RADIONODE: 5},
                      NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB"]}},
                      SCHEDULED_TIMES_STRINGS: ["10:00:00"], 'SLEEP_TIME': 1200,
                      USER_ROLES: ["FM_Operator", "NetworkLog_Administrator", "Cmedit_Operator"]},
            'FM_26': {NUM_USERS: 1, USER_ROLES: ["FM_Administrator"], 'TIME_PERIOD_IN_MIN': 45,
                      SCHEDULED_TIMES_STRINGS: ["10:00:00"]},
            'FM_27': {NUM_USERS: 1, USER_ROLES: ["FM_Administrator"], "NUMBER_OF_ROUTING_FILES": 20},
        },
        "fmx": {
            'FMX_01': {SCHEDULE_SLEEP: 60 * 60, USER_ROLES: ["FMX_Administrator"], 'execute_on_transport': False,
                       FMX_RULEMODULES: NSX_RULEMODULES + CNX_RULEMODULES + GRX_RULEMODULES},
            'FMX_05': {NUM_USERS: 1, 'NODE_COUNT': 12, 'NODE_TYPES': ['ERBS', 'RadioNode'],
                       USER_ROLES: ["ADMINISTRATOR"], SCHEDULE_SLEEP: 60 * 60, 'FETCH_NODES_FROM': ['FM_01', 'FM_02'],
                       'MAINTENANCE_MODES': ['MARK', 'NMS', 'NMSandOSS']}
        },
        "ftpes": {
            'FTPES_01': {NUM_NODES: {NODES.RADIONODE: -1}, NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"],
                         NODE_FILTER: {"RadioNode": {"managed_element_type": ["ENodeB", "GNodeB"]}},
                         'NUM_NODES_PER_BATCH': 500, 'NETWORK_PERCENT': 0.5, EXCLUDE_NODES_FROM: ["AP_01"],
                         'JOB_STATUS_CHECK_INTERVAL': 3 * 60}
        },
        "fan": {},
        "fs_quotas": {},
        "geo_r": {
            'GEO_R_01': {}
        },
        "ha": {},
        "launcher": {
            'LAUNCHER_01': {},
            'LAUNCHER_02': {},
            'LAUNCHER_03': {}
        },
        "lcm": {},
        "lkf": {},
        "logviewer": {
            'LOGVIEWER_01': {SCHEDULE_SLEEP: 1800, NUM_USERS: 1, USER_ROLES: ["OPERATOR"], 'SEARCH_TERM': "all errors"}
        },
        "lt_syslog_stream": {},
        "ncm_mef_lcm": {},
        "ncm_l3_vpn": {},
        "ncm_mef": {},
        "ncm_vpn_sd": {},
        "netex": {
            'NETEX_01': {NUM_USERS: 31, USER_ROLES: ["Network_Explorer_Administrator"], SCHEDULE_SLEEP: 60 * 30,
                         "NUM_RESULTS_LARGE_COLLECTION": 500},
            'NETEX_02': {},
            'NETEX_03': {},
            'NETEX_04': {},
            'NETEX_05': {},
            'NETEX_07': {}
        },
        "neo4j": {},
        "netview": {
            'NETVIEW_SETUP': {},
            'NETVIEW_01': {},
            'NETVIEW_02': {}
        },
        "network": {},
        "nhc": {
            'NHC_01': {},
            'NHC_02': {},
            'NHC_04': {}
        },
        "nodecli": {
            'NODECLI_01': {},
        },
        "nhm": {
            'NHM_SETUP': {},
            'NHM_03': {},
            'NHM_04': {},
            'NHM_05': {},
            'NHM_06': {},
            'NHM_07': {},
            'NHM_08': {},
            'NHM_09': {},
            'NHM_10': {},
            'NHM_11': {},
            'NHM_12': {},
            'NHM_13': {NUM_NODES: {NODES.ERBS: -1}, 'REQUIRED_NODES': 20, 'OPERATOR_ROLE': ["NHM_Administrator"],
                       'NUM_OPERATORS': 1, 'NUMBER_OF_CELLS': 3, 'NUMBER_OF_KPIS': 8, SCHEDULE_SLEEP: 28800,
                       'RECOMMENDED_KPIS': ['Downlink_Latency', 'Abnormal_Releases_ENB', 'Average_DL_UE_Latency',
                                            'Average_MAC_Cell_DL_Throughput', 'Average_PDCP_Cell_DL_Throughput',
                                            'Average_UE_PDCP_DL_Throughput', 'Average_UE_UL_PDCP_Throughput',
                                            'Initial_E-RAB_Establishment_Success_Rate']},
            'NHM_14': {NUM_NODES: {NODES.ERBS: -1, NODES.RADIONODE: -1}, 'OPERATOR_ROLE': ["NHM_Administrator"],
                       'NUM_OPERATORS': 1, 'NUMBER_OF_KPIS': 25,
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                       'REPORTING_OBJECT': ['EUtranCellFDD', 'EUtranCellTDD'],
                       'SUPPORTED_TYPES_CUSTOM_CELL_LEVEL_KPI': ['ERBS', 'RadioNode']}},
        "nhm_rest_nbi": {
            'NHM_REST_NBI_01': {},
            'NHM_REST_NBI_02': {},
            'NHM_REST_NBI_03': {},
            'NHM_REST_NBI_04': {},
            'NHM_REST_NBI_05': {},
            'NHM_REST_NBI_06': {},
            'NHM_REST_NBI_07': {},
            'NHM_REST_NBI_08': {},
            'NHM_REST_NBI_SETUP': {}
        },
        "nodesec": {
            'NODESEC_11': {},
            'NODESEC_13': {},
            'NODESEC_15': {TOTAL_NODES: 1000, SUPPORTED_NODE_TYPES: [NODES.RADIONODE, NODES.ERBS, NODES.RNC, NODES.RBS,
                                                                     NODES.MGW, NODES.DSC, NODES.EPG, NODES.MTAS,
                                                                     NODES.ROUTER6672, NODES.ROUTER6675,
                                                                     NODES.SGSN_MME],
                           NUM_USERS: 2, SCHEDULED_TIMES_STRINGS: ['08:00:00'], 'RUN_UNTIL': '18:00:00',
                           THREAD_QUEUE_TIMEOUT: 4 * 60 * 60, 'NODE_REQUEST_CREDENTIALS_TIME': 5},
            'NODESEC_16': {NUM_USERS: 1, "NUM_OF_NODES": 10, USER_ROLES: ['ldaprenewer'],
                           "CAPABILITIES": {"ldap": ["update", "patch"], "cm_editor": ["read"]},
                           SCHEDULED_TIMES_STRINGS: ['05:00:00']},
            "NODESEC_17": {NUM_USERS: 1, USER_ROLES: ["proxycleanupper"],
                           "CAPABILITIES": {"nodesec_proxy": ["read", "update", "delete"]},
                           "INACTIVE_HOURS": 48, SCHEDULED_TIMES_STRINGS: ["22:30:00"], "SCHEDULE_SLEEP_DAYS": 2},
            'NODESEC_18': {NUM_USERS: 1, NUM_NODES: {NODES.SGSN_MME: -1},
                           USER_ROLES: ['sshkeymaker'], "CAPABILITIES": {"sshkey": ["create", "delete"],
                                                                         "cm_editor": ["read"]},
                           SCHEDULED_TIMES_STRINGS: ["03:00:00"], SCHEDULED_DAYS: ["MONDAY"]}
        },
        "npa": {
            'NPA_01': {NUM_USERS: 1, SCHEDULE_SLEEP: 60 * 60 * 24 * 7, 'NUMBER_OF_FLOWS': 5, 'NUMBER_OF_CELLS': 100,
                       USER_ROLES: ['Flowautomation_Operator', 'Cmedit_Operator', 'NHM_Operator', 'NHM_Administrator',
                                    'Nhc_Administrator', 'Shm_Administrator'],
                       'NODE_VERSION_FORMAT': ["20.Q1", "20.Q2", "20.Q3", "20.Q4", "21.Q1", "21.Q2", "21.Q3", "21.Q4"],
                       'CELL_TYPE': {'RadioNode': ['EUtranCellFDD', 'EUtranCellTDD']}, 'KPI_ADJUST': 1}
        },
        "nvs": {},
        "nas_outage": {},
        "ops": {
            'OPS_01': {'FILTERED_NODES_PER_HOST': 2, USER_ROLES: OPS_USER_ROLES + COM_ROLES, SUPPORTED_NODE_TYPES: [NODES.BSC],
                       TOTAL_NODES: 2, 'MAX_SESSION_COUNT_PER_NODE': 35,
                       SCHEDULED_TIMES_STRINGS: ["03:30:00", "09:30:00", "15:30:00", "21:30:00"], "SESSION_COUNT": 1,
                       THREAD_QUEUE_TIMEOUT: 2400, EXCLUDE_NODES_FROM: ["CELLMGT_15"]}
        },
        "migration": {},
        "parmgt": {
            'PARMGT_01': {NUM_USERS: 1, USER_ROLES: ["Parameter_Management_Administrator", "Cmedit_Administrator"],
                          TOTAL_NODES: 21, SUPPORTED_NODE_TYPES: [NODES.RADIONODE],
                          NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                          SCHEDULED_TIMES_STRINGS: ["06:00:00"], "DAILY_SLEEP": 23 * 60 * 60 + 40 * 60,
                          "NUMBER_OF_ITERATIONS": 32, "TIME_IN_MINUTES_BETWEEN_ITERATIONS": 15},
            'PARMGT_02': {},
            'PARMGT_03': {NUM_USERS: 1, USER_ROLES: ["Parameter_Management_Administrator"], "NUMBER_OF_MOS": 5000,
                          SCHEDULED_TIMES_STRINGS: ["14:00:00"], SCHEDULED_DAYS: ["FRIDAY"]},
            'PARMGT_04': {}
        },
        "plm": {
            'PLM_01': {}
        },
        "pkiadmin": {
            'PKIADMIN_01': {SCHEDULE_SLEEP: 24 * 60 * 60, NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"]}
        },
        "pm_rest_nbi": {},
        "pm": {
            'PM_02': {NUM_NODES: {NODES.ERBS: -1}, 'NUM_COUNTERS': 1.0,
                      USER_ROLES: ['Cmedit_Administrator', "PM_Operator", "Network_Explorer_Administrator"],
                      'CBS': True, 'POLL_SCANNERS': True, 'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_03': {NUM_NODES: {NODES.ERBS: -1}, NUM_EVENTS: 1.0,
                      USER_ROLES: ['Cmedit_Administrator', "PM_Operator", "Network_Explorer_Administrator"],
                      'CBS': True, 'POLL_SCANNERS': True, "EVENT_FILTER": "cellTraceLRan",
                      'DEFINER': "CELLTRACE_SubscriptionAttributes"},
            'PM_04': {USER_ROLES: ["PM_Operator", 'Cmedit_Administrator'], 'SYS_DEF_SUB_PATTERN': 'CCTR'},
            'PM_06': {},
            'PM_11': {},
            'PM_15': {'POLLING_AND_MASTER_RETENTION': ("scannerPollingIntervalMinutes", 15),
                      SCHEDULE_SLEEP: 60 * 60 * 24},
            'PM_16': {USER_ROLES: ["PM_Operator", 'Cmedit_Administrator'],
                      'UE_INFO': {"type": "IMSI", "value": "27202"}, 'INTERFACE_TYPES': {'SGSN': [], 'ENODEB': ["s1"]}},
            'PM_17': {'PM_NBI_RETENTION_PARAMETERS': {
                'STATS_RETENTION': ("pmicStatisticalFileRetentionPeriodInMinutes", 4320),
                'CELLTRACE_RETENTION': ("pmicCelltraceFileRetentionPeriodInMinutes", 180),
                'UE_TRACE_RETENTION': ("pmicUeTraceFileRetentionPeriodInMinutes", 360),
                'CTUM_RETENTION': ("pmicCtumFileRetentionPeriodInMinutes", 360),
                'EBM_RETENTION': ("pmicEbmFileRetentionPeriodInMinutes", 180),
                'CELL_TRAFFIC_RETENTION': ("pmicCellTrafficFileRetentionPeriodInMinutes", 180),
                'UETR_RETENTION': ("pmicUetrFileRetentionPeriodInMinutes", 180),
                'GPEH_RETENTION': ("pmicGpehFileRetentionPeriodInMinutes", 180)}, SCHEDULE_SLEEP: 60 * 60 * 24},
            'PM_19': {USER_ROLES: ["PM_Operator", 'Cmedit_Administrator'], 'SYS_DEF_SUB_PATTERN': 'CTUM',
                      'UE_INFO': {"type": "IMSI", "value": "27208"}},
            'PM_24': {USER_ROLES: ["PM_Operator", 'Cmedit_Administrator'],
                      'UE_INFO': {"type": "IMSI", "value": "27201"}},
            'PM_25': {},
            'PM_26': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator", "Scripting_Operator", "ADMINISTRATOR"],
                      'ROP_INTERVAL': 15, 'SFTP_FETCH_TIME_IN_MINS': 13, 'N_SFTP_THREADS': 10,
                      SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                for minute in range(0, 60, 15)],
                      'DATA_TYPES': ['PM_STATISTICAL', 'PM_STATISTICAL_1MIN', 'PM_STATISTICAL_5MIN',
                                     'PM_STATISTICAL_30MIN', 'PM_STATISTICAL_1HOUR', 'PM_STATISTICAL_12HOUR',
                                     'PM_STATISTICAL_24HOUR', 'PM_CELLTRACE', 'PM_CELLTRACE_CUCP', 'PM_CELLTRACE_CUUP',
                                     'PM_CELLTRACE_DU', 'PM_UETRACE', 'PM_UETRACE_CUCP', 'PM_UETRACE_CUUP',
                                     'PM_UETRACE_DU', 'PM_EBS', 'PM_EBM', 'PM_CTUM', 'PM_UETR', 'PM_CTR', 'PM_GPEH',
                                     'PM_CELLTRAFFIC', 'PM_EBSM_3GPP', 'PM_EBSM_ENIQ', 'PM_EBSL', 'PM_EBSN_DU',
                                     'PM_EBSN_CUCP', 'PM_EBSN_CUUP', 'PM_BSC_PERFORMANCE_EVENT',
                                     'PM_BSC_PERFORMANCE_CTRL', 'PM_BSC_RTT', 'PM_BSC_PERFORMANCE_EVENT_STATISTICS',
                                     'PM_BSC_PERFORMANCE_EVENT_RAW', 'PM_BSC_PERFORMANCE_EVENT_MONITORS',
                                     'TOPOLOGY_*'], "DATA_TYPES_UPDATE_TIME": "00:00"},
            'PM_27': {USER_ROLES: ["PM_Operator", 'Cmedit_Administrator'], 'SYS_DEF_SUB_PATTERN': '(v)EPG'},
            'PM_28': {},
            'PM_29': {NUM_NODES: {NODES.RNC: -1}, NUM_EVENTS: 1.0, USER_ROLES: ["PM_Operator", 'Cmedit_Administrator'],
                      "NUM_OF_SUBSCRIPTIONS": 2},
            'PM_30': {NUM_NODES: {NODES.RBS: -1}, 'NUM_COUNTERS': 1.0, USER_ROLES: ["PM_Operator"],
                      'SYS_DEF_SUB_PATTERN': 'RBS'},
            'PM_31': {NUM_NODES: {NODES.RNC: -1}, 'NUM_COUNTERS': 1.0, USER_ROLES: ["PM_Operator"],
                      'SYS_DEF_SUB_PATTERN': 'RNC Primary'},
            'PM_32': {NUM_NODES: {NODES.ROUTER6672: -1}, 'NUM_COUNTERS': 1.0,
                      USER_ROLES: ['Cmedit_Administrator', "PM_Operator", "Network_Explorer_Administrator"],
                      'CBS': True, 'MO_CLASS_COUNTERS_INCLUDED': ['global', 'context'],
                      'MO_CLASS_SUB_COUNTERS_INCLUDED': {"global": ["average_user_mem", "cpu1min", "cpu5min",
                                                                    "cpu5sec", "epochtime", "free_user_mem",
                                                                    "load15min", "load1min", "load5min",
                                                                    "peak_user_mem", "peakcpu5min", "sysuptime",
                                                                    "total_user_mem"],
                                                         "context": ["epochtime", "sysuptime"]},
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_35': {},
            'PM_38': {NUM_NODES: {NODES.RADIONODE: -1}, 'NUM_COUNTERS': 1.0,
                      USER_ROLES: ['Cmedit_Administrator', "PM_Operator", "Network_Explorer_Administrator"],
                      'CBS': True, 'POLL_SCANNERS': True,
                      'MO_CLASS_COUNTERS_INCLUDED': {"5GS": ['NRCellDU_GNBDU', 'NRCellDU_GNBDUCP'],
                                                     "EPS": ['EUtranCellFDD', 'EUtranCellTDD'],
                                                     "GSM": ['GsmSector', 'Trx', 'ExtTrx', 'AbisIp'],
                                                     "UMTS": ['HsDschResources']},
                      'TECHNOLOGY_DOMAIN_COUNTER_LIMITS': {'5GS': 100, 'EPS': 100, 'UMTS': 100, 'GSM': 100},
                      'RESERVED_COUNTERS': {'EPS': 100}, 'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_40': {NUM_NODES: {NODES.SGSN_MME: -1}, 'NUM_COUNTERS': 1.0,
                      USER_ROLES: ["PM_Operator", 'Cmedit_Administrator', "Network_Explorer_Administrator"],
                      'CBS': True, 'ENM_NE_TYPES': ['SGSN-MME'], 'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_42': {NUM_NODES: {NODES.RADIONODE: -1}, NUM_EVENTS: 1.0,
                      USER_ROLES: ['Cmedit_Administrator', "PM_Operator", "Network_Explorer_Administrator"],
                      'CBS': True, 'POLL_SCANNERS': True,
                      NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB"]}},
                      "EVENT_FILTER": "cellTraceLRan", 'DEFINER': "CELLTRACE_SubscriptionAttributes"},
            'PM_44': {},
            'PM_46': {NUM_NODES: {NODES.RNC: -1}, NUM_EVENTS: 1.0,
                      USER_ROLES: ["PM_Operator", 'Cmedit_Administrator', "Network_Explorer_Administrator"],
                      'CBS': True},
            'PM_47': {NUM_NODES: {NODES.RNC: -1}, NUM_EVENTS: 1.0, USER_ROLES: ["PM_Operator", 'Cmedit_Administrator'],
                      'IMSI': [{"type": "IMSI", "value": "123546"}, {"type": "IMSI", "value": "234567"},
                               {"type": "IMSI", "value": "345678"},
                               {"type": "IMSI", "value": "456789"}, {"type": "IMSI", "value": "567890"},
                               {"type": "IMSI", "value": "122133213212144"},
                               {"type": "IMSI", "value": "2432342343"}, {"type": "IMSI", "value": "34234324324"},
                               {"type": "IMSI", "value": "2432423425"},
                               {"type": "IMSI", "value": "546546546546"}, {"type": "IMSI", "value": "4765765765"},
                               {"type": "IMSI", "value": "888586"},
                               {"type": "IMSI", "value": "65867885"}, {"type": "IMSI", "value": "67876878"},
                               {"type": "IMSI", "value": "6867867876"},
                               {"type": "IMSI", "value": "67876876867"}]},
            'PM_48': {},
            'PM_50': {NUM_NODES: {NODES.MTAS: -1}, USER_ROLES: ["PM_Operator", 'Cmedit_Administrator',
                                                                "Network_Explorer_Administrator"], 'CBS': True,
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_51': {NUM_NODES: {NODES.RBS: -1}, NUM_EVENTS: 1.0,
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator"], 'CBS': True},
            'PM_52': {NUM_NODES: {NODES.RADIONODE: -1}, 'NODES_TO_FIND': {NODES.RADIONODE: 10},
                      NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ["ENodeB", "ENodeB|NodeB", "NodeB"]}},
                      USER_ROLES: ['Cmedit_Administrator', "ULSA_Administrator", "PM_Operator"],
                      SCHEDULED_TIMES_STRINGS: ["06:00:00"],
                      EXCLUDE_NODES_FROM: ["CMSYNC_01", "CMSYNC_02", "CMSYNC_04", "CMSYNC_06"]},
            'PM_54': {NUM_NODES: {NODES.MINI_LINK_Indoor: -1}, NUM_EVENTS: 1.0,
                      USER_ROLES: ["PM_Operator", "Cmedit_Administrator", "Network_Explorer_Administrator"],
                      'MO_CLASS_COUNTERS_INCLUDED': ['AdaptiveCodingAndModulation_ACM_15min',
                                                     'ERP_RT', 'EthernetBandwidth',
                                                     'EthernetDelay', 'EthernetTrafficPerformance',
                                                     'IGMP-MLD-Snooping_RT', 'IP_RT', 'PDH_15min',
                                                     'PTP_RT', 'RADIUS_RT', 'RadioLinkPower_RT',
                                                     'SDH_MS_MSPNE_15min', 'SDH_VC12FE_15min',
                                                     'SDH_VC12NE_15min', 'SDH_VC4NE_15min',
                                                     'ServiceOAM', 'TACACS+_RT', 'TCP_RT', 'UDP_RT'], 'CBS': True,
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_55': {},
            'PM_56': {USER_ROLES: ["PM_Operator"], 'SYS_DEF_SUB_PATTERN': 'SIU02'},
            'PM_57': {},
            'PM_58': {},
            'PM_59': {USER_ROLES: ["PM_Operator"], 'SYS_DEF_SUB_PATTERN': 'ERBS'},
            'PM_60': {USER_ROLES: ["PM_Operator"], 'SYS_DEF_SUB_PATTERN': 'RadioNode'},
            'PM_61': {NUM_NODES: {NODES.DSC: -1},
                      USER_ROLES: ["PM_Operator", "Cmedit_Administrator", "Network_Explorer_Administrator"],
                      'CBS': True, 'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_62': {NUM_NODES: {NODES.BSC: -1}, USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator"],
                      'CBS': True, 'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_63': {},
            'PM_64': {},
            'PM_65': {},
            'PM_66': {},
            'PM_67': {NUM_NODES: {NODES.CISCO_ASR900: -1},
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator", "Cmedit_Administrator"],
                      'CBS': True, 'ENM_NE_TYPES': ['CISCO-ASR900', 'CISCO-ASR9000'], 'NUM_COUNTERS': 150,
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_68': {USER_ROLES: ["PM_Operator"],
                      'SYS_DEF_SUB_PATTERN': "FRONTHAUL-6080 Primary15min"},
            'PM_69': {},
            'PM_70': {},
            'PM_71': {},
            'PM_72': {},
            'PM_73': {USER_ROLES: ["PM_Operator"],
                      'SYS_DEF_SUB_PATTERN': "FRONTHAUL-6080 Primary24h"},
            'PM_74': {NUM_NODES: {NODES.ROUTER6672: -1}, 'CBS': True, 'ROP_STR': 'ONE_DAY',
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator", "Cmedit_Administrator"],
                      'ENM_NE_TYPES': [NODES.ROUTER6672], 'DEFINER': "STATISTICAL_SubscriptionAttributes",
                      'MO_CLASS_COUNTERS_INCLUDED': ['global', 'context', 'port-history', 'ces-pw-history'],
                      'MO_CLASS_SUB_COUNTERS_INCLUDED': {"global": ["average_user_mem", "peak_user_mem",
                                                                    "total_user_mem"],
                                                         "context": ["epochtime", "sysuptime"],
                                                         "port-history": ["epochtime", "sysuptime"],
                                                         "ces-pw-history": ["epochtime"]}},
            'PM_75': {},
            'PM_76': {NUM_NODES: {NODES.CISCO_ASR900: -1},
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator"],
                      'CBS': True, 'ROP_STR': 'ONE_DAY', 'ENM_NE_TYPES': ['CISCO-ASR900', 'CISCO-ASR9000'],
                      'NUM_COUNTERS': 150,
                      'MO_CLASS_COUNTERS_INCLUDED': ['BGP4-MIB_bgpPeerTable_Group',
                                                     'CISCO-BGP-POLICY-ACCOUNTING-MIB_cbpAcctTable_Group',
                                                     'CISCO-BGP4-MIB_cbgpPeer2AddrFamilyPrefixTable_Group',
                                                     'CISCO-BGP4-MIB_cbgpPeer2Table_Group',
                                                     'CISCO-BGP4-MIB_cbgpPeerAddrFamilyPrefixTable_Group',
                                                     'CISCO-BGP4-MIB_cbgpPeerTable_Group',
                                                     'CISCO-CEF-MIB_cefAdjTable_Group',
                                                     'CISCO-CEF-MIB_cefCCTypeTable_Group',
                                                     'CISCO-CEF-MIB_cefPeerTable_Group',
                                                     'CISCO-CEF-MIB_cefPrefixTable_Group',
                                                     'CISCO-CEF-MIB_cefResourceTable_Group',
                                                     'CISCO-CEF-MIB_cefStatsPrefixLenTable_Group',
                                                     'CISCO-CEF-MIB_cefSwitchingStatsTable_Group',
                                                     'CISCO-CLASS-BASED-QOS-MIB_cbQosC3plAccountStatsTable_Group',
                                                     'CISCO-CLASS-BASED-QOS-MIB_cbQosCMStatsTable_Group',
                                                     'CISCO-CLASS-BASED-QOS-MIB_cbQosEBStatsTable_Group',
                                                     'CISCO-CLASS-BASED-QOS-MIB_cbQosIPHCStatsTable_Group',
                                                     'CISCO-CLASS-BASED-QOS-MIB_cbQosMatchStmtStatsTable_Group'],
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_77': {NUM_NODES: {NODES.BSC: 95}, USER_ROLES: ["PM_Operator", "Cmedit_Administrator"],
                      SCHEDULED_TIMES_STRINGS: ["00:52:00", "02:52:00", "06:52:00", "08:52:00", "12:52:00", "14:52:00",
                                                "18:52:00", "20:52:00"]},
            'PM_78': {NUM_NODES: {NODES.MSC_DB_BSP: -1}, 'NODES_PER_SUBSCRIPTION': 5,
                      USER_ROLES: ["PM_Operator", "Cmedit_Administrator"],
                      SCHEDULED_TIMES_STRINGS: ["01:52:00", "03:52:00", "07:52:00", "09:52:00",
                                                "13:52:00", "15:52:00", "19:52:00", "21:52:00"],
                      "TOTAL_REQUIRED_NODES": 20},
            'PM_79': {},
            'PM_80': {},
            'PM_81': {},
            'PM_82': {},
            'PM_83': {},
            'PM_84': {},
            'PM_85': {},
            'PM_86': {},
            'PM_87': {},
            'PM_88': {},
            'PM_89': {},
            'PM_90': {},
            'PM_91': {},
            'PM_92': {},
            'PM_93': {},
            'PM_94': {NUM_NODES: {NODES.EPG_OI: -1}, USER_ROLES: ["PM_Operator", "Cmedit_Administrator"],
                      'SYS_DEF_SUB_PATTERN': 'EPG-OI'},
            'PM_95': {NUM_NODES: {NODES.ROUTER6672: 40}, USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator",
                                                                      "Cmedit_Administrator"], 'NUM_COUNTERS': 1.0,
                      'ROP_STR': 'ONE_MIN', 'MO_CLASS_COUNTERS_INCLUDED': ['global', 'context', 'port-history',
                                                                           'ces-pw-history'],
                      'MO_CLASS_SUB_COUNTERS_INCLUDED': {"global": ["average_user_mem", "peak_user_mem",
                                                                    "total_user_mem"],
                                                         "context": ["epochtime", "sysuptime"],
                                                         "port-history": ["epochtime", "sysuptime"],
                                                         "ces-pw-history": ["epochtime"]},
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_96': {NUM_NODES: {NODES.ROUTER6675: 40}, USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator",
                                                                      "Cmedit_Administrator"],
                      'ROP_STR': 'ONE_MIN', 'NUM_COUNTERS': 1.0, 'DEFINER': "STATISTICAL_SubscriptionAttributes",
                      'MO_CLASS_COUNTERS_INCLUDED': ['global', 'context', 'port-history', 'ces-pw-history'],
                      'MO_CLASS_SUB_COUNTERS_INCLUDED': {"global": ["average_user_mem", "peak_user_mem",
                                                                    "total_user_mem"],
                                                         "context": ["epochtime", "sysuptime"],
                                                         "port-history": ["epochtime", "sysuptime"],
                                                         "ces-pw-history": ["epochtime"]}},
            'PM_97': {},
            'PM_98': {},
            'PM_99': {},
            'PM_100': {},
            'PM_101': {}
        },
        "reparenting": {
            "REPARENTING_01": {},
            "REPARENTING_02": {},
            "REPARENTING_03": {},
            "REPARENTING_04": {},
            "REPARENTING_05": {},
            "REPARENTING_06": {},
            "REPARENTING_07": {},
            "REPARENTING_08": {},
            "REPARENTING_09": {},
            "REPARENTING_10": {},
            "REPARENTING_11": {},
            "REPARENTING_12": {}
        },
        "secui": {
            'SECUI_01': {},
            'SECUI_02': {},
            'SECUI_03': {SCHEDULED_TIMES_STRINGS: ["00:00:00"]},
            'SECUI_05': {},
            'SECUI_06': {},
            'SECUI_07': {},
            'SECUI_08': {},
            'SECUI_09': {},
            'SECUI_10': {},
            'SECUI_11': {},
            'SECUI_12': {},
        },
        "sev": {
            'SEV_01': {NUM_USERS: 5, USER_ROLES: ["SEV_Administrator", "SEV_Operator"], NUM_NODES: {NODES.ESC: 5},
                       NODE_FILTER: {NODES.ESC: {"node_version": ["22.Q3"]}}, SCHEDULE_SLEEP: 60 * 15,
                       CHECK_NODE_SYNC: True},
            'SEV_02': {NUM_USERS: 5, USER_ROLES: ["SEV_Administrator", "SEV_Operator"], NUM_NODES: {NODES.ESC: 5},
                       SCHEDULE_SLEEP: 60 * 15}
        },
        "shm": {
            'SHM_SETUP': {NUM_NODES: {NODES.ERBS: -1, NODES.MGW: -1, NODES.RADIONODE: -1, NODES.MINI_LINK_Indoor: -1,
                                      NODES.ROUTER6672: -1, NODES.BSC: -1,
                                      NODES.SIU02: -1}},
            'SHM_01': {NUM_NODES: {NODES.ERBS: 5}, SCHEDULED_TIMES_STRINGS: ["19:45:00"],
                       "PIB_VALUES": {"SMRS_ERBS_NoOf_BACKUP_FILES": "2"},
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["20:15:00"], 'NUM_NODES_PER_BATCH': 5, MAX_NODES: 5},
            'SHM_02': {TOTAL_NODES: 5, SCHEDULED_TIMES_STRINGS: ["12:00:00"],
                       NUM_NODES: {NODES.RADIONODE: 5},
                       "PIB_VALUES": {"SMRS_RadioNode_NoOf_BACKUP_FILES": "2"},
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ["ENodeB", "GNodeB"]}},
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["12:30:00"], 'NUM_NODES_PER_BATCH': 5, MAX_NODES: 5},
            'SHM_03': {'FILTERED_NODES_PER_HOST': 5, SCHEDULED_TIMES_STRINGS: ["06:30:00"], NUM_NODES: {NODES.ERBS: 5},
                       SCHEDULED_DAYS: ['WEDNESDAY'], MAX_NODES: 5, SKIP_SYNC_CHECK: False,
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_04': {NUM_USERS: 1, USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"],
                       NUM_NODES: {NODES.ERBS: 10}, SCHEDULED_TIMES_STRINGS: ["11:00:00"], 'TIMEOUT': 1800,
                       SCHEDULED_DAYS: ['WEDNESDAY']},
            'SHM_05': {'FILTERED_NODES_PER_HOST': 5, MAX_NODES: 5, SCHEDULED_DAYS: ['THURSDAY'],
                       SCHEDULED_TIMES_STRINGS: ["06:30:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       NUM_NODES: {NODES.RADIONODE: -1}, EXCLUDE_NODES_FROM: ['SHM_06'], SKIP_SYNC_CHECK: False,
                       NODE_FILTER: {
                           NODES.RADIONODE: {'managed_element_type': ["ENodeB"], 'model_identity': ['', '-']}},
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1", "NUMBER_OF_SOFTWARE_PACKAGES_TO_RETAIN_FOR_RADIONODE": "5"}},
            'SHM_06': {},
            'SHM_07': {},
            'SHM_19': {NUM_NODES: {}, MAX_NODES_TO_ALLOCATE: 293, SCHEDULED_TIMES_STRINGS: ["19:00:00"],
                       SCHEDULED_DAYS: ['THURSDAY']},
            'SHM_20': {NUM_NODES: {}, MAX_NODES_TO_ALLOCATE: 293, SCHEDULED_TIMES_STRINGS: ["19:00:00"],
                       SCHEDULED_DAYS: ['FRIDAY']},
            'SHM_21': {},
            'SHM_23': {'NODES_PER_HOST': 100, NUM_NODES: {NODES.MINI_LINK_Indoor: 2},
                       "PIB_VALUES": {"SMRS_MINILINKIndoor_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["02:30:00"],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["03:00:00"], MAX_NODES: 2},
            'SHM_24': {'NODES_PER_HOST': 100, NUM_NODES: {NODES.MINI_LINK_Indoor: 2},
                       SCHEDULED_TIMES_STRINGS: ["06:30:00"],
                       EXCLUDE_NODES_FROM: ['SHM_06'], "MLTN_TIMEOUT": 50, NUM_USERS: 1,
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"], SKIP_SYNC_CHECK: False,
                       SCHEDULED_DAYS: ['MONDAY'], MAX_NODES: 2, "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_27': {'NODES_PER_HOST': 100, NUM_NODES: {NODES.SIU02: -1},
                       SCHEDULED_TIMES_STRINGS: ["06:30:00"], NUM_USERS: 1, SCHEDULED_DAYS: ['SATURDAY'],
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"], SKIP_SYNC_CHECK: False,
                       MAX_NODES: 5, "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_28': {},
            'SHM_31': {},
            'SHM_32': {},
            'SHM_33': {},
            'SHM_34': {},
            'SHM_35': {NUM_USERS: 1,
                       NUM_NODES: {NODES.ERBS: -1, NODES.RADIONODE: -1, NODES.ROUTER6672: -1, NODES.BSC: -1},
                       SCHEDULED_TIMES_STRINGS: ["19:30:00"], SCHEDULE_SLEEP: 604800,
                       SCHEDULED_DAYS: ['FRIDAY'],
                       USER_ROLES: ["Shm_Administrator", 'SECURITY_ADMIN', "WinFIOL_Operator", "FIELD_TECHNICIAN",
                                    "Scripting_Operator"] + COM_ROLES,
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ["ENodeB"]}}, "NODES_PER_CHUNK": 1000},
            'SHM_36': {'NODES_PER_HOST': 2, NUM_USERS: 1, NUM_NODES: {NODES.BSC: 1}, MAX_NODES: 1,
                       SCHEDULED_TIMES_STRINGS: ["06:00:00"], SCHEDULED_DAYS: ['FRIDAY'],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"], SKIP_SYNC_CHECK: True,
                       USER_ROLES: ["Shm_Administrator", "Ops_Operator", "WinFIOL_Operator",
                                    "Element_Manager_Operator", "FIELD_TECHNICIAN", "Scripting_Operator"] + COM_ROLES,
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_37': {NUM_USERS: 1, USER_ROLES: ["Shm_Administrator"],
                       NUM_NODES: {NODES.ERBS: -1, NODES.RADIONODE: -1, NODES.ROUTER6672: -1},
                       SCHEDULED_TIMES_STRINGS: ["21:00:00"], SCHEDULED_DAYS: ["THURSDAY"],
                       "NODES_PER_CHUNK": 1000, "SLEEP_TIME_BETWEEN_JOBS": 5 * 60},
            'SHM_39': {'NODES_PER_HOST': 1, NUM_NODES: {NODES.BSC: 2}, SCHEDULED_DAYS: ["MONDAY"],
                       "PIB_VALUES": {"SMRS_BSC_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["23:00:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["23:30:00"],
                       SKIP_SYNC_CHECK: True, 'TIMEOUT': 1800,
                       NUM_USERS: 1, EXCLUDE_NODES_FROM: ['SHM_06'],
                       USER_ROLES: ["Shm_Administrator", "Ops_Operator", "WinFIOL_Operator", "FIELD_TECHNICIAN",
                                    "Element_Manager_Operator", "Scripting_Operator"] + COM_ROLES, MAX_NODES: 2},
            'SHM_40': {},
            'SHM_41': {},
            'SHM_42': {},
            'SHM_43': {},
            'SHM_44': {},
            'SHM_47': {NUM_NODES: {NODES.RADIONODE: 12},
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                       MAX_NODES: 10, SCHEDULED_DAYS: ['WEDNESDAY'], SCHEDULED_TIMES_STRINGS: ["08:30:00"],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["09:00:00"]}

        },
        "top": {
            'TOP_01': {TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], NUM_USERS: 1,
                       USER_ROLES: ["Topology_Browser_Administrator"], LTE_CELL_CHECK: True, CHECK_NODE_SYNC: True,
                       NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "ENodeB|NodeB", "GNodeB"]}},
                       EXCLUDE_NODES_FROM: ["CMSYNC_02", "CMSYNC_04", "CMSYNC_06", "CMSYNC_01", "ENMCLI_02"],
                       'THREAD_QUEUE_TIMEOUT': 60 * 25}
        }
    }
}
