# ********************************************************************
# Name    : Five Network
# Summary : If a profile is not listed here in this file, please refer to default values config file (forty_network.py) instead.
# ********************************************************************

from basic_network import (IMP_EXP_KEYS as IMP_EXP, USER_KEYS as USER, NODE_KEYS as NODE, TIME_KEYS as TIME,
                           NeTypesEnum as NODES, SKIP_SYNC_CHECK, MAX_NODES, MAX_NODES_TO_ALLOCATE, ERROR_HANDLING,
                           TIMEOUT, NUM_ITERATIONS, COM_ROLES, OPS_USER_ROLES, AMOS_USER_ROLES, SECUI_01_USER_ROLES,
                           CNX_RULEMODULES, NSX_RULEMODULES, GRX_RULEMODULES, FMX_RULEMODULES, LTE_CELL_CHECK,
                           CHECK_NODE_SYNC, THREAD_QUEUE_TIMEOUT, GEO_USER_ROLES)
from profile_cmds import (ENMCLI_COMMANDS, ROUTER_6000_AVC_BURST_MO_TYPE_SETTINGS, PCG_AVC_BURST_MO_TYPE_SETTINGS)

SCHEDULED_DAYS, SCHEDULE_SLEEP, SCHEDULED_TIMES_STRINGS = TIME
NUM_USERS, USER_ROLES = USER
NUM_NODES, SUPPORTED_NODE_TYPES, TOTAL_NODES, EXCLUDE_NODES_FROM, NODE_FILTER = NODE
INTERFACE, FILETYPE, FLOW, IMPORT_TYPE, CREATE_DELETE_LIVE, CREATE_DELETE_CONFIG, UPDATE_LIVE, UPDATE_CONFIG = IMP_EXP
TOTAL_TARGET_ALARMS = 1840000
FM_02_TOTAL_ALARMS = 4 * 5 * 60 * 24 * 40
FM_03_TOTAL_ALARMS = 4 * 60 * 8 * 200

five_k_network = {
    "five_k_network": {
        "amos": {
            'AMOS_01': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 8, NUM_USERS: 8, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ["AMOS_02", "AMOS_03", "AMOS_04", "AMOS_05", "AMOS_08", "ASU_01", "NPA_01"],
                        'VERIFY_TIMEOUT': 60 * 20,
                        SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute)
                                                  for hour in range(11, 15) for minute in ["00", "30"]],
                        'COMMANDS': ["get upgradepackage", "get lp", "get pci", "get dcgm", "cabx"],
                        'COMMANDS_PER_ITERATION': 68},
            'AMOS_02': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 8, NUM_USERS: 8, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ["AMOS_01", "AMOS_03", "AMOS_04", "AMOS_05", "AMOS_08", "ASU_01", "NPA_01"],
                        'VERIFY_TIMEOUT': 60 * 20,
                        SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(str(hour).zfill(2), minute)
                                                  for hour in range(9, 17) for minute in ["00", "30"]],
                        'COMMANDS': ["confb", "get PmService PmServiceId", "pst", "altuc"],
                        'COMMANDS_PER_ITERATION': 68},
            'AMOS_03': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 7, NUM_USERS: 7, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ['AMOS_01', 'AMOS_02', 'AMOS_04', 'AMOS_05', 'AMOS_08', 'ASU_01', 'NPA_01'],
                        'VERIFY_TIMEOUT': 60 * 20,
                        SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(str(hour).zfill(2), minute)
                                                  for hour in range(7, 19) for minute in ["00", "30"]],
                        'COMMANDS': ["confd", "al", "alt", "altuc", "lst cell"], 'COMMANDS_PER_ITERATION': 68},
            'AMOS_04': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 7, NUM_USERS: 7, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ["AMOS_01", "AMOS_02", "AMOS_03", "AMOS_05", "AMOS_08", "ASU_01", "NPA_01"],
                        'VERIFY_TIMEOUT': 60 * 20,
                        SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(str(hour).zfill(2), minute)
                                                  for hour in range(0, 24) for minute in ["00", "30"]],
                        'COMMANDS': ["get ManagedElement", "fget sec noofusedAntenna", "st fdd", "st cell",
                                     "lst RfPort", "st termpointtoenb"],
                        'COMMANDS_PER_ITERATION': 68},
            'AMOS_05': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 14, NUM_USERS: 14, USER_ROLES: AMOS_USER_ROLES + ['Scripting_Operator'],
                        'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ["AMOS_01", "AMOS_02", "AMOS_03", "AMOS_05", "AMOS_08", "ASU_01", "NPA_01"],
                        SCHEDULE_SLEEP: 60 * 10,
                        'TIMEOUT': 10, 'NUM_PARALLEL': 1,
                        'COMMANDS': ["al", "kget pci", "lk EUtraNetwork=1", "getmom", "shget pci"],
                        'COMMANDS_PER_ITERATION': 22},
        },
        "aid": {
            'AID_01': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], TOTAL_NODES: 300, NUM_USERS: 3,
                       USER_ROLES: ['AutoId_Administrator'],
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}}, 'AID_PROFILE_SLEEP': 30,
                       SCHEDULED_TIMES_STRINGS: ['00:15:00', '01:15:00', '02:15:00', '03:15:00', '04:15:00',
                                                 '05:15:00', '06:15:00', '07:15:00', '08:15:00', '09:15:00',
                                                 '10:15:00', '11:15:00', '12:15:00', '13:15:00', '14:15:00',
                                                 '15:15:00', '16:15:00', '17:15:00', '18:15:00', '19:15:00',
                                                 '20:15:00', '21:15:00', '22:15:00', '23:15:00']},
            'AID_03': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], TOTAL_NODES: 225, NUM_USERS: 1,
                       USER_ROLES: ['AutoId_Administrator'],
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                       EXCLUDE_NODES_FROM: ["AID_04"]},
            'AID_04': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], TOTAL_NODES: 25, NUM_USERS: 1,
                       USER_ROLES: ['AutoId_Administrator', "ADMINISTRATOR"], 'NUM_NODES_PER_BATCH': 100,
                       SCHEDULED_TIMES_STRINGS: ['02:00:00'],
                       'MO_ATTRIBUTE_DATA': {
                           'FDD': {'EUtranCellFDD': [['physicalLayerCellIdGroup', 0, 167],
                                                     ['physicalLayerSubCellId', 0, 2]]},
                           'TDD': {'EUtranCellTDD': [['physicalLayerCellIdGroup', 0, 167],
                                                     ['physicalLayerSubCellId', 0, 2]]}},
                       'RUN_TYPE': 'NEW', EXCLUDE_NODES_FROM: ["AID_03"],
                       NODE_FILTER: {NODES.ERBS: {"lte_cell_type": ['FDD', 'TDD']},
                                     NODES.RADIONODE: {'managed_element_type': ['ENodeB'],
                                                       "lte_cell_type": ['FDD', 'TDD']}}}
        },
        "ap": {
            'AP_01': {NUM_NODES: {NODES.RADIONODE: 1}, NUM_USERS: 1, SCHEDULED_TIMES_STRINGS: ["02:00:00"],
                      USER_ROLES: ['ADMINISTRATOR'], 'PROJECT_NAME': 'ap_01_workload', MAX_NODES: 1,
                      NUM_ITERATIONS: 10,
                      NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB'], 'model_identity': ''}},
                      EXCLUDE_NODES_FROM: ["FTPES_01"]}
        },
        "apt": {},
        "asr_l": {
            'ASR_L_01': {},
        },
        "asr_n": {
            'ASR_N_01': {},
        },
        "asu": {
            'ASU_01': {},
        },
        "bur": {},
        "ca": {
            'CA_01': {}
        },
        'cbrs': {
            'CBRS_SETUP': {USER_ROLES: ['ADMINISTRATOR'], LTE_CELL_CHECK: True,
                           'DEVICES_REQUIRED': {"2208": 0, "RadioDot": 288, "4408": 144, "6488": 0, "NR_4408": 0,
                                                "PassiveDas_4408": 0},
                           'CBRS_PAL_PERCENTAGE': 0.10, 'MIXPALGAA_PERCENTAGE': 0.50,
                           'SA_DC_CLUSTER_IP_LIST': '', 'SAS_URL': '',
                           NODE_FILTER: {
                               NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB'], 'lte_cell_type': ["TDD"]}},
                           NUM_USERS: 1, NUM_NODES: {NODES.RADIONODE: -1}}
        },
        "cellmgt": {
            'CELLMGT_07': {},
            'CELLMGT_08': {USER_ROLES: ["ADMINISTRATOR"], SCHEDULE_SLEEP: 60 * 60 * 24,
                           NUM_NODES: {NODES.ERBS: -1, NODES.RADIONODE: -1},
                           NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}}},
            'CELLMGT_09': {USER_ROLES: ["ADMINISTRATOR"],
                           SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.RNC, NODES.RBS],
                           NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                           TOTAL_NODES: 100, NUM_USERS: 5,
                           'THREAD_QUEUE_TIMEOUT': 60 * 15, 'UI_DISPLAY_LIMIT': 50,
                           SCHEDULED_TIMES_STRINGS: ['00:00:00', '01:00:00', '02:00:00', '03:00:00', '04:00:00',
                                                     '05:00:00', '06:00:00', '07:00:00', '08:00:00', '09:00:00',
                                                     '10:00:00', '11:00:00', '12:00:00', '13:00:00', '14:00:00',
                                                     '15:00:00', '16:00:00', '17:00:00', '18:00:00', '19:00:00',
                                                     '20:00:00', '21:00:00', '22:00:00', '23:00:00']},
            'CELLMGT_13': {},
            'CELLMGT_14': {},
            'CELLMGT_15': {}
        },
        "cli_mon": {},
        "cmevents_nbi": {
            'CMEVENTS_NBI_01': {SCHEDULE_SLEEP: 60, NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'EVENT_LIMIT': 20000}
        },
        "cmexport": {
            'CMEXPORT_14': {},
            'CMEXPORT_19': {},
            'CMEXPORT_21': {},
            'CMEXPORT_22': {},
            'CMEXPORT_25': {},
            'CMEXPORT_26': {}
        },
        "cmimport": {
            'CMIMPORT_01': {'TIMES_PER_DAY': 24, TOTAL_NODES: 3, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                            'BATCH_MO_SIZE': 50, USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ['03:00:01', '09:00:01', '17:00:01'],
                            'MO_VALUES': {'RetSubUnit': 1, 'AntennaSubunit': 1},
                            'MOS_ATTRS': {'RetSubUnit': ['userLabel'], 'AntennaSubunit': ['maxTotalTilt']},
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'],
                            TIMEOUT: 15 * 60, NUM_ITERATIONS: 24 / 3,
                            FILETYPE: '3GPP', FLOW: 'live_config', IMPORT_TYPE: UPDATE_LIVE,
                            'MOS_DEFAULT': {'RetSubUnit': ('userLabel', ""), 'AntennaSubunit': ('maxTotalTilt', 900)},
                            'MOS_MODIFY': {'RetSubUnit': ('userLabel', 'cmimport_01'),
                                           'AntennaSubunit': ('maxTotalTilt', 899)}},
            'CMIMPORT_02': {TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                            EXCLUDE_NODES_FROM: ['CMSYNC_02'],
                            'BATCH_MO_SIZE': 50, USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            'MO_VALUES': {'EUtranCellRelation': 12, 'UtranCellRelation': 12, 'GeranCellRelation': 6},
                            'MOS_ATTRS': {'UtranCellRelation': ['externalUtranCellFDDRef', 'UtranCellRelationId'],
                                          'EUtranCellRelation': ['EUtranCellRelationId', 'neighborCellRef'],
                                          'GeranCellRelation': ['GeranCellRelationId']},
                            SCHEDULED_TIMES_STRINGS: ['00:30:01', '01:30:01', '02:30:01', '03:30:01', '04:30:01',
                                                      '05:30:01', '06:30:01', '07:30:01', '08:30:01', '09:30:01'],
                            FILETYPE: 'dynamic', INTERFACE: 'NBIv2', FLOW: 'live_config',
                            IMPORT_TYPE: CREATE_DELETE_LIVE, TIMEOUT: 15 * 60,
                            "MAPPING_FOR_5G_NODE_MO": {'UtranCellRelation': {'NRCellRelation': 15},
                                                       'EUtranCellRelation': {'EUtranCellRelation': 15}},
                            "MAPPING_FOR_5G_NODE_ATTRS": {'EUtranCellRelation': ['isRemoveAllowed',
                                                                                 'neighborCellRef',
                                                                                 'eUtranCellRelationId'],
                                                          'NRCellRelation': ['nRCellRelationId', 'nRCellRef',
                                                                             'nRFreqRelationRef']}},
            'CMIMPORT_03': {'MO_VALUES': {'TermPointToENB': 2},
                            'MOS_ATTRS': {'TermPointToENB': ['administrativeState']},
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'], 'BATCH_MO_SIZE': 50,
                            TOTAL_NODES: 10, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'],
                            SCHEDULED_TIMES_STRINGS: ['08:45:01', '09:45:01', '10:45:01', '11:45:01', '12:45:01',
                                                      '13:45:01', '14:45:01', '15:45:01', '16:45:01', '17:45:01',
                                                      '18:45:01', '19:45:01', '20:45:01', '21:45:01'],
                            FILETYPE: 'dynamic', IMPORT_TYPE: UPDATE_LIVE, FLOW: 'live_config',
                            'MOS_DEFAULT': {'TermPointToENB': ('administrativeState', 'UNLOCKED'),
                                            'TermPointToGNodeB': ('administrativeState', 'UNLOCKED')},
                            'MOS_MODIFY': {'TermPointToENB': ('administrativeState', 'LOCKED'),
                                           'TermPointToGNodeB': ('administrativeState', 'LOCKED')},
                            TIMEOUT: 60 * 60, 'UNDO_TIME': '09:45:01', INTERFACE: 'NBIv2',
                            "MAPPING_FOR_5G_NODE_MO": {'TermPointToENB': {'TermPointToGNodeB': 2}},
                            "MAPPING_FOR_5G_NODE_ATTRS": {'TermPointToGNodeB': ['administrativeState']}},
            'CMIMPORT_04': {'MO_VALUES': {'EUtranCellRelation': 2},
                            'MOS_ATTRS': {'EUtranCellRelation': ['EUtranCellRelationId', 'neighborCellRef']},
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'], TOTAL_NODES: 15,
                            SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                            SCHEDULED_TIMES_STRINGS: ['12:50:01', '13:50:01', '14:50:01', '15:50:01', '16:50:01',
                                                      '17:50:01'], 'BATCH_MO_SIZE': 50, FILETYPE: 'dynamic',
                            FLOW: 'live_config', IMPORT_TYPE: CREATE_DELETE_LIVE, TIMEOUT: 60 * 60},
            'CMIMPORT_05': {'MO_VALUES': {'UtranFreqRelation': 6, 'EUtranFreqRelation': 4},
                            'MOS_ATTRS': {'UtranFreqRelation': ['userLabel'], 'EUtranFreqRelation': ['userLabel']},
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ['02:20:01', '10:00:01'],
                            'BATCH_MO_SIZE': 100, TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                            FILETYPE: '3GPP', FLOW: 'live_config', INTERFACE: 'NBIv2', IMPORT_TYPE: UPDATE_LIVE,
                            'MOS_DEFAULT': {'UtranFreqRelation': ('userLabel', 'cmimport_05_default'),
                                            'EUtranFreqRelation': ('userLabel', 'cmimport_05_default')},
                            'MOS_MODIFY': {'UtranFreqRelation': ('userLabel', 'cmimport_05_changes'),
                                           'EUtranFreqRelation': ('userLabel', 'cmimport_05_changes')},
                            TIMEOUT: 45 * 60, EXCLUDE_NODES_FROM: ["NODESEC_13"]},
            'CMIMPORT_10': {SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675], TOTAL_NODES: 10,
                            'BATCH_MO_SIZE': 50,
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ['02:10:00'],
                            'MO_VALUES': {'SwItem': 4}, 'MOS_ATTRS': {'SwItem': ['userLabel']},
                            FILETYPE: 'dynamic', EXCLUDE_NODES_FROM: ['CMSYNC_11', 'CMSYNC_15'],
                            FLOW: 'live_config', IMPORT_TYPE: UPDATE_LIVE, INTERFACE: 'NBIv2',
                            'MOS_DEFAULT': {'SwItem': ('userLabel', 'default')},
                            'MOS_MODIFY': {'SwItem': ('userLabel', 'modify')},
                            ERROR_HANDLING: 'continue-on-error-node', TIMEOUT: 90 * 60},
            'CMIMPORT_11': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                            TOTAL_NODES: 100, USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            'MO_VALUES': {'EUtranCellRelation': 12}, 'BATCH_MO_SIZE': 100,
                            SCHEDULED_TIMES_STRINGS: ['01:30:00'], FILETYPE: '3GPP', INTERFACE: 'NBIv1',
                            FLOW: 'live_config', 'ERROR_HANDLING': 'continue-on-error-node', IMPORT_TYPE: UPDATE_LIVE,
                            'MOS_DEFAULT': {'EUtranCellRelation': ('isRemoveAllowed', 'true'),
                                            'NRCellRelation': ('isHoAllowed', 'true')},
                            'MOS_MODIFY': {'EUtranCellRelation': ('isRemoveAllowed', 'false'),
                                           'NRCellRelation': ('isHoAllowed', 'false')},
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'], TIMEOUT: 60 * 60,
                            "MAPPING_FOR_5G_NODE_MO": {'EUtranCellRelation': {'NRCellRelation': 12}}},
            'CMIMPORT_15': {USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'], NUM_USERS: 7,
                            SCHEDULED_TIMES_STRINGS: ['09:00:01']},
            'CMIMPORT_16': {FILETYPE: 'dynamic', 'BATCH_MO_SIZE': 100,
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [NODES.TCU02, NODES.SIU02],
                            SCHEDULED_TIMES_STRINGS: ['20:00:01'], SCHEDULED_DAYS: ['THURSDAY'],
                            'MO_VALUES': {'STN': 1}, 'MOS_ATTRS': {'STN': ['userLabel']},
                            'MOS_DEFAULT': {'STN': ('userLabel', 'null')}, 'MOS_MODIFY': {'STN': ('userLabel', 'stn')},
                            INTERFACE: 'NBIv2', FLOW: 'live_config', IMPORT_TYPE: UPDATE_LIVE, TIMEOUT: 15 * 60},
            'CMIMPORT_17': {'MO_VALUES': {'UtranFreqRelation': 5, 'EUtranFreqRelation': 5},
                            'MOS_ATTRS': {'UtranFreqRelation': ['userLabel'], 'EUtranFreqRelation': ['userLabel']},
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'], FILETYPE: '3GPP',
                            SCHEDULED_TIMES_STRINGS: ['02:35:01', '12:35:01'],
                            EXCLUDE_NODES_FROM: ['CMSYNC_02', "CMSYNC_04", "CMSYNC_06"],
                            'BATCH_MO_SIZE': 100, TOTAL_NODES: 10, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                            'MOS_DEFAULT': {'UtranFreqRelation': ('userLabel', 'null'),
                                            'EUtranFreqRelation': ('userLabel', 'null'),
                                            'NRCellRelation': ('isHoAllowed', 'true')},
                            'MOS_MODIFY': {'UtranFreqRelation': ('userLabel', 'cmimport_17'),
                                           'EUtranFreqRelation': ('userLabel', 'cmimport_17'),
                                           'NRCellRelation': ('isHoAllowed', 'false')},
                            IMPORT_TYPE: UPDATE_LIVE, FLOW: 'live_config', INTERFACE: 'NBIv2', TIMEOUT: 30 * 60,
                            ERROR_HANDLING: 'continue-on-error-node',
                            "MAPPING_FOR_5G_NODE_MO": {'UtranFreqRelation': {'NRCellRelation': 5},
                                                       'EUtranFreqRelation': {'EUtranFreqRelation': 5}},
                            "MAPPING_FOR_5G_NODE_ATTRS": {'NRCellRelation': ['isHoAllowed'],
                                                          'EUtranFreqRelation': ['userLabel']}},
            'CMIMPORT_18': {},
            'CMIMPORT_19': {},
            'CMIMPORT_20': {},
            'CMIMPORT_21': {},
            'CMIMPORT_22': {},
            'CMIMPORT_23': {},
            'CMIMPORT_24': {},
            'CMIMPORT_25': {},
            'CMIMPORT_26': {},
            'CMIMPORT_27': {},
            'CMIMPORT_28': {},
            'CMIMPORT_29': {},
            'CMIMPORT_30': {},
            'CMIMPORT_31': {},
            'CMIMPORT_32': {},
            'CMIMPORT_33': {}
        },
        "cmsync": {
            'CMSYNC_SETUP': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], SCHEDULE_SLEEP: 24 * 24 * 60,
                             "MSCM_RATIO": 0.5, "MSCMCE_RATIO": 0.5, "MAX_MOS_PER_RNC": 500, "VALUES_PER_PROFILE":
                                 {"CMSYNC_01": 0.0132, "CMSYNC_02": 0.6997, "CMSYNC_04": 0.1435, "CMSYNC_06": 0.1436},
                             "MAX_MOS_MSCMCE": 76000},
            'CMSYNC_15': {TOTAL_NODES: 50, SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675],
                          SCHEDULE_SLEEP: 1800,
                          'NOTIFICATION_INFO': ROUTER_6000_AVC_BURST_MO_TYPE_SETTINGS, 'ROUTER_SUPPORT': 300,
                          EXCLUDE_NODES_FROM: ['CMIMPORT_10'], 'BURST_DURATION': 1800},
            'CMSYNC_25': {NUM_NODES: {NODES.RADIONODE: 100}, SCHEDULED_DAYS: ["SUNDAY"],
                          SCHEDULED_TIMES_STRINGS: ["23:30:00"],
                          NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB"]}}},
            'CMSYNC_30': {NUM_NODES: {NODES.ERBS: 100}, SCHEDULED_DAYS: ["SUNDAY"],
                          SCHEDULED_TIMES_STRINGS: ["21:20:00"]},
            'CMSYNC_33': {TOTAL_NODES: 50, SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675],
                          SCHEDULED_DAYS: ["THURSDAY"], SCHEDULED_TIMES_STRINGS: ["17:30:00"]},
            'CMSYNC_34': {TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_Indoor, NODES.MINI_LINK_669x],
                          SCHEDULED_DAYS: ["THURSDAY"],
                          SCHEDULED_TIMES_STRINGS: ["01:30:00"]},
            'CMSYNC_35': {},
            'CMSYNC_38': {NUM_NODES: {NODES.JUNIPER_MX: 1}, SCHEDULED_TIMES_STRINGS: ["22:15:00"]},
            'CMSYNC_39': {},
            'CMSYNC_40': {},
            'CMSYNC_41': {},
            'CMSYNC_42': {},
            'CMSYNC_44': {NUM_NODES: {NODES.PCG: 100}, 'UPDATED_AVG_PER_NODE': 0.005787, SCHEDULE_SLEEP: 86400,
                          'NOTIFICATION_INFO': PCG_AVC_BURST_MO_TYPE_SETTINGS, 'BURST_DURATION': 86400}

        },
        "configuration_template": {},
        "doc": {
            'DOC_01': {NUM_USERS: 5, USER_ROLES: ["OPERATOR"], SCHEDULE_SLEEP: 60 * 60}
        },
        "dynamic_crud": {
            'DYNAMIC_CRUD_01': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 10},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                SCHEDULE_SLEEP: 30 * 60,
                                "REQ_COUNTS": {"REQ_1_2_3": 16, "REQ_4_5_6": 78,
                                               "REQ_7": 1, "REQ_8": 1, "REQ_9": 1, "REQ_10": 1}},
            'DYNAMIC_CRUD_03': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 15},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                SCHEDULED_TIMES_STRINGS: ["09:30:00", "21:30:00"], "NUMBER_OF_THREADS": 8,
                                "REQ_COUNTS": {"REQ_1_2_3": 64}, EXCLUDE_NODES_FROM: ["DYNAMIC_CRUD_05"],
                                "NODES_PER_HOST": 8, MAX_NODES: 8},
            'DYNAMIC_CRUD_04': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 10},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                SCHEDULED_TIMES_STRINGS: ["03:30:00", "07:30:00", "11:30:00", "15:30:00", "19:30:00",
                                                          "23:30:00"],
                                "NUMBER_OF_THREADS": 10, "REQ_COUNTS": {"REQ_1_2_3": 625}},
            'DYNAMIC_CRUD_05': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 5},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                "NUMBER_OF_THREADS": 1, SCHEDULED_TIMES_STRINGS: ["02:30:00", "14:30:00"],
                                "REQ_COUNTS": {"PATCH": 6}, EXCLUDE_NODES_FROM: ["DYNAMIC_CRUD_03"],
                                "NODES_PER_HOST": 2, MAX_NODES: 2}
        },
        "ebsl": {
            'EBSL_05': {},
            'EBSL_06': {},
        },
        "ebsn": {
            'EBSN_01': {},
            'EBSN_03': {},
            'EBSN_04': {},
            'EBSN_05': {},
        },
        "ebsm": {
            'EBSM_04': {},
        },
        "em": {
            'EM_01': {SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_Indoor], TOTAL_NODES: 100, NUM_USERS: 16,
                      'TOTAL_NODES_NON_RACK': 16, 'NUM_USERS_RACK': 100,
                      SCHEDULED_TIMES_STRINGS: ["00:30:00", "06:30:00", "12:30:00", "18:30:00"],
                      "PARALLEL_SESSIONS_LAUNCH": 2,
                      USER_ROLES: ['Element_Manager_Operator', 'ENodeB_Application_Administrator',
                                   'GNodeB_Application_Administrator', 'Network_Explorer_Operator',
                                   'RemoteDesktop_Operator', 'DesktopSession_Administrator']}
        },
        "esm": {},
        "esm_nbi": {
            'ESM_NBI_01': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'ROP_INTERVAL': 15,
                           SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                     for minute in range(0, 60, 15)]}
        },
        "enmcli": {
            'ENMCLI_02': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], TOTAL_NODES: 16, NUM_USERS: 16,
                          NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                          USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator'],
                          SCHEDULE_SLEEP: 60 * 15, EXCLUDE_NODES_FROM: ["TOP_01"], LTE_CELL_CHECK: True},
            'ENMCLI_03': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], TOTAL_NODES: 2, NUM_USERS: 30,
                          NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                          'SCHEDULE_SLEEP': 900, 'enmcli_commands_list': ENMCLI_COMMANDS,
                          USER_ROLES: ['Cmedit_Operator', 'Scripting_Operator', 'FM_Operator', 'Lcm_Administrator',
                                       'NodeSecurity_Operator', 'Autoprovisioning_Operator', 'ADMINISTRATOR',
                                       'SECURITY_ADMIN'], 'total_commands_sec': 0.33,
                          'percentage_cm_bas': 22.5, 'percentage_cm_std': 45, 'percentage_cm_adv': 22.5,
                          'percentage_alarm': 5, 'percentage_secadm': 5, LTE_CELL_CHECK: True},
            'ENMCLI_05': {TOTAL_NODES: 500, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], NUM_USERS: 1,
                          USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator']},
            'ENMCLI_08': {},
        },
        "fm": {
            'FM_01': {
                SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672,
                                       NODES.BSC, NODES.SGSN_MME,
                                       NODES.MSC_DB_BSP, NODES.MSC_BC_BSP, NODES.MSC_BC_IS, NODES.SIU02, NODES.TCU02,
                                       NODES.MINI_LINK_Indoor, NODES.ROUTER6675, NODES.MINI_LINK_669x, NODES.CCDM],
                EXCLUDE_NODES_FROM: ["FM_02", "FM_03"], 'DURATION': 3660, SCHEDULE_SLEEP: 3600, 'AML_RATE': 0.05,
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'], 'AML_RATIO': 0.5,
                TOTAL_NODES: 20, 'BSC_BURST_RATE': 0.038, 'MSC_BURST_RATE': 0.038,
                'FM_01_TOTAL_ALARMS': TOTAL_TARGET_ALARMS - (FM_02_TOTAL_ALARMS + FM_03_TOTAL_ALARMS),
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('EXTERNAL ALARM', 'major'),
                    ('CCITT7 SIGNALLING LINK FAILURE', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_02': {
                SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672,
                                       NODES.BSC, NODES.SGSN_MME,
                                       NODES.MSC_DB_BSP, NODES.MSC_BC_BSP, NODES.MSC_BC_IS, NODES.SIU02, NODES.TCU02,
                                       NODES.MINI_LINK_Indoor,
                                       NODES.ROUTER6675, NODES.MINI_LINK_669x, NODES.CCDM],
                EXCLUDE_NODES_FROM: ["FM_01", "FM_03"], 'AML_RATE': 2.0, 'AML_RATIO': 0.5,
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                TOTAL_NODES: 225, 'BURST_RATE': 40, 'DURATION': 300, SCHEDULE_SLEEP: 900,
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('EXTERNAL ALARM', 'major'),
                    ('CCITT7 SIGNALLING LINK FAILURE', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_03': {
                SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672,
                                       NODES.BSC, NODES.SGSN_MME,
                                       NODES.MSC_DB_BSP, NODES.MSC_BC_BSP, NODES.MSC_BC_IS, NODES.SIU02, NODES.TCU02,
                                       NODES.MINI_LINK_Indoor,
                                       NODES.ROUTER6675, NODES.MINI_LINK_669x, NODES.CCDM],
                EXCLUDE_NODES_FROM: ["FM_01", "FM_02"], 'AML_RATE': 10.0, 'AML_RATIO': 0.5,
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                TOTAL_NODES: 750, 'BURST_RATE': 200, 'DURATION': 240,
                SCHEDULED_TIMES_STRINGS: ['00:00:00', '02:45:00', '06:00:00', '09:35:00', '12:10:00',
                                          '14:45:00', '18:00:00', '21:00:00'],
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('EXTERNAL ALARM', 'major'),
                    ('CCITT7 SIGNALLING LINK FAILURE', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_08': {TOTAL_NODES: 150,
                      SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MINI_LINK_669x, NODES.ROUTER6672,
                                             NODES.ROUTER6675, NODES.CCDM],
                      NUM_USERS: 3, 'NUM_USERS_1': 2, 'NUM_USERS_2': 1, USER_ROLES: ["FM_Operator"],
                      'ALARM_MONITOR_SLEEP': 5 * 60, SCHEDULE_SLEEP: 60 * 15},
            'FM_09': {TOTAL_NODES: 150,
                      SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.ROUTER6672, NODES.ROUTER6675,
                                             NODES.MINI_LINK_669x, NODES.CCDM], NUM_USERS: 4,
                      USER_ROLES: ["FM_Operator"], 'ALARM_MONITOR_SLEEP': 60, SCHEDULE_SLEEP: 60 * 15},
            'FM_12': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'TIMEOUT_SUBSCRIPTION': 60 * 24,
                      'NUMBER_NBI_SUBSCRIPTIONS': 14, 'TIMEOUT': 2, 'NBI_filters': ["LTE0", "LTE1"],
                      'CORBA_ENABLED': True, 'BNSI': True, SCHEDULED_TIMES_STRINGS: ["07:00:00"]},
            'FM_14': {TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.CCDM], NUM_USERS: 1,
                      USER_ROLES: ["FM_Administrator"], SCHEDULED_TIMES_STRINGS: ["16:00:00"],
                      "TIME_SPAN": 90},
            'FM_15': {TOTAL_NODES: 150, NUM_USERS: 1,
                      SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MINI_LINK_Indoor, NODES.MINI_LINK_669x,
                                             NODES.ROUTER6672, NODES.ROUTER6675, NODES.CCDM],
                      USER_ROLES: ["FM_Administrator"], "TIME_SPAN": 90,
                      SCHEDULED_DAYS: ['WEDNESDAY'], SCHEDULED_TIMES_STRINGS: ["16:00:00"]},
            'FM_25': {NUM_USERS: 3, NUM_NODES: {NODES.ERBS: 20, NODES.RADIONODE: 20},
                      NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB"]}},
                      SCHEDULED_TIMES_STRINGS: ["10:00:00"], 'SLEEP_TIME': 1200,
                      USER_ROLES: ["FM_Operator", "NetworkLog_Administrator", "Cmedit_Operator"]},
        },
        "fmx": {
            'FMX_01': {SCHEDULE_SLEEP: 60 * 60, USER_ROLES: ["FMX_Administrator"], 'execute_on_transport': False,
                       FMX_RULEMODULES: NSX_RULEMODULES + CNX_RULEMODULES + GRX_RULEMODULES},
            'FMX_05': {NUM_USERS: 1, 'NODE_COUNT': 12, 'NODE_TYPES': ['ERBS', 'RadioNode'],
                       USER_ROLES: ["ADMINISTRATOR"], SCHEDULE_SLEEP: 60 * 60, 'FETCH_NODES_FROM': ['FM_01', 'FM_02'],
                       'MAINTENANCE_MODES': ['MARK', 'NMS', 'NMSandOSS']}
        },
        "ftpes": {},
        "fan": {
            'FAN_01': {},
            'FAN_02': {},
            'FAN_03': {},
            'FAN_04': {},
            'FAN_11': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator"], 'ROP_INTERVAL': 15,
                       'FILES_FETCH_TIME_IN_MINS': 13, 'NUM_OF_BATCHES': 1, 'NUM_OF_CURL_PARALLEL_REQUESTS': 200,
                       'DATA_TYPES': ['PM_STATISTICAL_1MIN', 'PM_STATISTICAL_5MIN', 'PM_STATISTICAL',
                                      'PM_STATISTICAL_30MIN', 'PM_STATISTICAL_1HOUR', 'PM_STATISTICAL_12HOUR',
                                      'PM_STATISTICAL_24HOUR', 'PM_CELLTRACE', 'PM_CELLTRACE_CUCP',
                                      'PM_CELLTRACE_CUUP', 'PM_CELLTRACE_DU', 'PM_UETRACE',
                                      'PM_UETRACE_CUCP', 'PM_UETRACE_CUUP', 'PM_UETRACE_DU',
                                      'PM_EBS', 'PM_EBM', 'PM_CTUM', 'PM_UETR', 'PM_CTR', 'PM_GPEH',
                                      'PM_CELLTRAFFIC', 'PM_EBSM_3GPP', 'PM_EBSM_ENIQ', 'PM_EBSL', 'PM_EBSN_DU',
                                      'PM_EBSN_CUCP', 'PM_EBSN_CUUP', 'PM_BSC_PERFORMANCE_EVENT',
                                      'PM_BSC_PERFORMANCE_CTRL', 'PM_BSC_RTT', 'PM_BSC_PERFORMANCE_EVENT_STATISTICS',
                                      'PM_BSC_PERFORMANCE_EVENT_RAW', 'PM_BSC_PERFORMANCE_EVENT_MONITORS'],
                       SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                 for minute in range(0, 60, 15)], "POD_CPU": "5000m",
                       "POD_MEMORY": "1Gi", "SERVICE_FORWARD_PORT": 'fan-11', "DATA_TYPES_UPDATE_TIME": "00:00"},
            'FAN_12': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator"], 'ROP_INTERVAL': 15,
                       'FILES_FETCH_TIME_IN_MINS': 13, 'NUM_OF_BATCHES': 1, 'NUM_OF_CURL_PARALLEL_REQUESTS': 50,
                       'DATA_TYPES': ['PM_EBSL', 'PM_EBSN_CUCP', 'PM_EBSN_CUUP', 'PM_EBSN_DU',
                                      'PM_STATISTICAL', 'PM_STATISTICAL_12HOUR', 'PM_STATISTICAL_1HOUR',
                                      'PM_STATISTICAL_1MIN', 'PM_STATISTICAL_24HOUR', 'PM_STATISTICAL_30MIN',
                                      'PM_STATISTICAL_5MIN', 'PM_EBSM_3GPP', 'PM_EBSM_ENIQ', 'PM_BSC_BAR',
                                      'PM_BSC_MRR', 'PM_BSC_PERFORMANCE_EVENT_STATISTICS', 'TOPOLOGY_*'],
                       SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                 for minute in range(0, 60, 15)], "POD_CPU": "3000m",
                       "POD_MEMORY": "1Gi", "SERVICE_FORWARD_PORT": 'fan-12', 'DESIRED_TIME': '02:00',
                       "DATA_TYPES_UPDATE_TIME": "00:00"},
            'FAN_13': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator"], 'ROP_INTERVAL': 15,
                       'FILES_FETCH_TIME_IN_MINS': 13, 'NUM_OF_BATCHES': 1, 'NUM_OF_CURL_PARALLEL_REQUESTS': 200,
                       'DATA_TYPES': ['PM_STATISTICAL', 'PM_STATISTICAL_1MIN', 'PM_CELLTRACE',
                                      'PM_UETR', 'PM_GPEH', 'PM_UETRACE', 'PM_CTR',
                                      'PM_CELLTRACE_CUCP', 'PM_CELLTRACE_CUUP', 'PM_CELLTRACE_DU'],
                       SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                 for minute in range(0, 60, 15)], "POD_CPU": "3000m",
                       "POD_MEMORY": "1Gi", "SERVICE_FORWARD_PORT": 'fan-13', "DATA_TYPES_UPDATE_TIME": "00:00"},
            'FAN_14': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator"], 'ROP_INTERVAL': 15,
                       'FILES_FETCH_TIME_IN_MINS': 13, 'NUM_OF_BATCHES': 1, 'NUM_OF_CURL_PARALLEL_REQUESTS': 200,
                       'DATA_TYPES': ['PM_STATISTICAL_1MIN', 'PM_STATISTICAL_5MIN', 'PM_STATISTICAL',
                                      'PM_STATISTICAL_30MIN', 'PM_STATISTICAL_1HOUR', 'PM_STATISTICAL_12HOUR',
                                      'PM_STATISTICAL_24HOUR', 'PM_CELLTRACE', 'PM_CELLTRACE_CUCP',
                                      'PM_CELLTRACE_CUUP', 'PM_CELLTRACE_DU', 'PM_UETRACE', 'PM_UETRACE_CUCP',
                                      'PM_UETRACE_CUUP', 'PM_UETRACE_DU', 'PM_EBS', 'PM_EBM', 'PM_CTUM',
                                      'PM_UETR', 'PM_CTR', 'PM_GPEH', 'PM_CELLTRAFFIC', 'PM_EBSM_3GPP',
                                      'PM_EBSM_ENIQ', 'PM_EBSL', 'PM_EBSN_DU', 'PM_EBSN_CUCP', 'PM_EBSN_CUUP',
                                      'PM_BSC_PERFORMANCE_EVENT', 'PM_BSC_PERFORMANCE_CTRL', 'PM_BSC_RTT',
                                      'PM_BSC_PERFORMANCE_EVENT_STATISTICS', 'PM_BSC_PERFORMANCE_EVENT_RAW',
                                      'PM_BSC_PERFORMANCE_EVENT_MONITORS'],
                       SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                 for minute in range(0, 60, 15)], "POD_CPU": "3000m",
                       "POD_MEMORY": "1Gi", "SERVICE_FORWARD_PORT": 'fan-14', "DATA_TYPES_UPDATE_TIME": "00:00"}
        },
        "fs_quotas": {
            "FS_QUOTAS_01": {USER_ROLES: ["Scripting_Operator", "SECURITY_ADMIN"], "CEPH_QUOTA_LIMIT": 300,
                             "FILE_SIZE": "150M", "USER_NAME": "cephtest_1",
                             SCHEDULED_DAYS: ["THURSDAY"], SCHEDULED_TIMES_STRINGS: ['11:30:00'],
                             "RUN_UNTIL": "12:30:00"}
        },
        "geo_r": {
            'GEO_R_01': {SCHEDULED_TIMES_STRINGS: ["05:00:00", "11:00:00", "17:00:00", "23:00:00"],
                         USER_ROLES: GEO_USER_ROLES, "EXPORT_SIZE": "0.5", "MAX_FM_HISTORY_SIZE": "1"}
        },
        "ha": {},
        "launcher": {},
        "lcm": {},
        "lkf": {},
        "logviewer": {
            'LOGVIEWER_01': {SCHEDULE_SLEEP: 1800, NUM_USERS: 5, USER_ROLES: ["OPERATOR"], 'SEARCH_TERM': "all errors"}
        },
        "lt_syslog_stream": {
            'LT_SYSLOG_STREAM_01': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], "NUM_OF_LOGS": 100,
                                    SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute)
                                                              for hour in range(00, 24)
                                                              for minute in range(0, 60, 28) if minute in [28, 56]]}
        },
        "ncm_mef_lcm": {},
        "ncm_l3_vpn": {},
        "ncm_mef": {},
        "ncm_vpn_sd": {},
        "neo4j": {},
        "netex": {
            'NETEX_01': {NUM_USERS: 31, USER_ROLES: ["Network_Explorer_Administrator"], SCHEDULE_SLEEP: 60 * 30,
                         "NUM_RESULTS_LARGE_COLLECTION": 500},
            'NETEX_02': {NUM_NODES: {NODES.ERBS: -1, NODES.RADIONODE: -1, NODES.RNC: -1, NODES.RBS: -1, NODES.MGW: -1,
                                     NODES.SGSN_MME: -1},
                         'NUM_COLLECTIONS': 18, SCHEDULE_SLEEP: 60 * 60,
                         USER_ROLES: ["Network_Explorer_Administrator"], 'NODES_PER_COLLECTION': 450,
                         'ADDITIONAL_NODES_PER_COLLECTION': 50},
            'NETEX_03': {NUM_USERS: 1, SCHEDULED_TIMES_STRINGS: ["04:35:00", "10:35:00", "16:35:00", "23:25:00"],
                         "EXPECTED_NUM_LOCKED_CELLS": 720, "NETEX_KTT_TIME_LIMIT": 6.5,
                         USER_ROLES: ['Network_Explorer_Administrator', 'Cmedit_Administrator']},
            'NETEX_04': {},
            'NETEX_07': {},
        },
        "netview": {},
        "network": {},
        "nhc": {
            'NHC_01': {"NHC_SLEEP": 120, NUM_USERS: 1, USER_ROLES: ["Nhc_Operator"], "START_TIME": "19:55:00",
                       "STOP_TIME": "05:55:00", SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.MGW, NODES.RNC, NODES.RBS],
                       TOTAL_NODES: 100},
            'NHC_02': {NUM_USERS: 1, USER_ROLES: ["Nhc_Administrator"], SUPPORTED_NODE_TYPES: [NODES.RADIONODE],
                       TOTAL_NODES: 200,
                       NODE_FILTER: {NODES.RADIONODE: {"node_version": ["18.Q3", "18.Q4", "19.Q1", "19.Q2", "19.Q3",
                                                                        "19.Q4", "20.Q1", "20.Q2", "20.Q3", "20.Q4",
                                                                        "21.Q1", "21.Q2", "21.Q3", "21.Q4"]}},
                       SCHEDULED_TIMES_STRINGS: ['04:30:00'], SCHEDULED_DAYS: ['THURSDAY'],
                       "NHC_JOB_TIME": "05:00:00"},
            'NHC_04': {NUM_USERS: 1, USER_ROLES: ["Nhc_Administrator", "Shm_Administrator"],
                       SUPPORTED_NODE_TYPES: [NODES.RADIONODE], TOTAL_NODES: 200,
                       NODE_FILTER: {NODES.RADIONODE: {"node_version": ["20.Q1", "20.Q2", "20.Q3", "20.Q4",
                                                                        "21.Q1", "21.Q2", "21.Q3", "21.Q4"]}},
                       SCHEDULED_TIMES_STRINGS: ['08:20:00'],
                       SCHEDULED_DAYS: ['THURSDAY'], "NHC_JOB_TIME": "08:50:00"}
        },
        "nhm_rest_nbi": {
            'NHM_REST_NBI_01': {},
            'NHM_REST_NBI_02': {},
            'NHM_REST_NBI_03': {},
            'NHM_REST_NBI_04': {},
            'NHM_REST_NBI_05': {},
            'NHM_REST_NBI_06': {},
            'NHM_REST_NBI_07': {},
            'NHM_REST_NBI_08': {},
            'NHM_REST_NBI_SETUP': {}
        },
        "nodecli": {
            'NODECLI_01': {NUM_USERS: 30, USER_ROLES: ['NodeCLI_Administrator', 'OPERATOR'], TOTAL_NODES: 30,
                           SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MINI_LINK_Indoor,
                                                  NODES.MINI_LINK_669x,
                                                  NODES.ROUTER6672, NODES.ROUTER6675],
                           'SESSION_MULTIPLIER': 3, SCHEDULE_SLEEP: 60 * 15}
        },
        "nhm": {
            'NHM_SETUP': {NUM_NODES: {NODES.RNC: 2, NODES.ERBS: -1, NODES.RADIONODE: -1}, 'TRANSPORT_SETUP': False,
                          'NUMBER_OF_INSTANCES_REQUIRED': 300000.0, 'INSTANCES_GENERATED_BY_NPA_01': 8000.0,
                          'MAX_NUMBER_OF_CUSTOM_KPIS': 100,
                          NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'ENodeB|NodeB']}},
                          'REPORTING_OBJECT_02': {'RNC': ['UtranCell'], 'ERBS': ['EUtranCellFDD', 'EUtranCellTDD'],
                                                  'RadioNode': ['EUtranCellFDD', 'EUtranCellTDD']},
                          'REPORTING_OBJECT_01': {'ERBS': 'ENodeBFunction', 'RadioNode': 'ENodeBFunction'},
                          'SUPPORTED_TYPES_CUSTOM_CELL_LEVEL_KPI': ['RNC', 'ERBS', 'RadioNode'],
                          'UNSUPPORTED_TYPES_NODE_LEVEL_KPI': ['RNC'],
                          USER_ROLES: ['NHM_Administrator', 'Cmedit_Administrator'], 'NUM_KPIS_01': 8,
                          'UNSUPPORTED_KPIS': [['Added_E-RAB_Establishment_Success_Rate_per_QCI'],
                                               ['Average_DL_MAC_DRB_Latency_per_QCI'],
                                               ['Average_DL_PDCP_UE_DRB_Throughput_per_QCI'],
                                               ['Average_DL_UE_PDCP_DRB_Latency_per_QCI'],
                                               ['E-RAB_Retainability_Percentage_Lost_per_QCI'],
                                               ['E-RAB_Retainability_Session_Time_Normalized_per_QCI_Loss_Rate'],
                                               ['Initial_E-RAB_Establishment_Success_Rate_per_QCI'],
                                               ['UL_Packet_Loss_Rate_per_QCI'],
                                               ['Added_E-RAB_Establishment_Success_Rate_for_Emergency_Calls'],
                                               ['E-RAB_Retainability_Percentage_Lost_for_Emergency_Calls'],
                                               ['Initial_E-RAB_Establishment_Success_Rate_for_Emergency_Calls'],
                                               ['Average_DRB_Latency_DRX_Active-State_UL_In-Sync'],
                                               ['Average_DRB_Latency_with_DRX_Active-State_UL_Out-of-Sync'],
                                               ['Average_DRB_Latency_with_DRX_Inactive-State_UL_In-Sync'],
                                               ['Average_UL_UE_Throughput_per_LCG'],
                                               ['Handover_Failure'],
                                               ['Downlink_PRB_Utilization'],
                                               ['PDCCH_Utilization'],
                                               ['Uplink_PRB_Utilization']]}
        },
        "nodesec": {
            'NODESEC_11': {NUM_USERS: 1, NUM_NODES: {NODES.RADIONODE: -1},
                           NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB"]}},
                           MAX_NODES: 150, 'CERTS': ['OAM'], USER_ROLES: ['ADMINISTRATOR'], SCHEDULED_DAYS: ['FRIDAY'],
                           SCHEDULED_TIMES_STRINGS: ['18:10:00']},
            'NODESEC_13': {NUM_NODES: {NODES.RADIONODE: -1},
                           NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB"]}},
                           MAX_NODES: 120, 'CERTS': ['OAM'], SCHEDULED_DAYS: ["FRIDAY"],
                           SCHEDULED_TIMES_STRINGS: ['22:35:00'], EXCLUDE_NODES_FROM: ["CMIMPORT_05"]},
            'NODESEC_15': {TOTAL_NODES: 1000, SUPPORTED_NODE_TYPES: [NODES.RADIONODE, NODES.ERBS, NODES.RNC, NODES.RBS,
                                                                     NODES.MGW, NODES.DSC, NODES.EPG, NODES.MTAS,
                                                                     NODES.ROUTER6672, NODES.ROUTER6675,
                                                                     NODES.SGSN_MME],
                           NUM_USERS: 20, SCHEDULED_TIMES_STRINGS: ['08:00:00'], 'RUN_UNTIL': '18:00:00',
                           THREAD_QUEUE_TIMEOUT: 4 * 60 * 60, 'NODE_REQUEST_CREDENTIALS_TIME': 5},
            'NODESEC_16': {NUM_USERS: 1, "NUM_OF_NODES": 100, USER_ROLES: ['ldaprenewer'],
                           "CAPABILITIES": {"ldap": ["update", "patch"], "cm_editor": ["read"]},
                           SCHEDULED_TIMES_STRINGS: ['05:00:00']},
            "NODESEC_17": {NUM_USERS: 1, USER_ROLES: ["proxycleanupper"],
                           "CAPABILITIES": {"nodesec_proxy": ["read", "update", "delete"]},
                           "INACTIVE_HOURS": 48, SCHEDULED_TIMES_STRINGS: ["22:30:00"], "SCHEDULE_SLEEP_DAYS": 2},
            'NODESEC_18': {NUM_USERS: 1, NUM_NODES: {NODES.SGSN_MME: -1},
                           USER_ROLES: ['sshkeymaker'], "CAPABILITIES": {"sshkey": ["create", "delete"],
                                                                         "cm_editor": ["read"]},
                           SCHEDULED_TIMES_STRINGS: ["03:00:00"], SCHEDULED_DAYS: ["MONDAY"]}
        },
        "npa": {
            'NPA_01': {NUM_USERS: 1, SCHEDULE_SLEEP: 60 * 60 * 24 * 7, 'NUMBER_OF_FLOWS': 5, 'NUMBER_OF_CELLS': 100,
                       USER_ROLES: ['Flowautomation_Operator', 'Cmedit_Operator', 'NHM_Operator', 'NHM_Administrator',
                                    'Nhc_Administrator', 'Shm_Administrator'],
                       'NODE_VERSION_FORMAT': ["20.Q1", "20.Q2", "20.Q3", "20.Q4", "21.Q1", "21.Q2", "21.Q3", "21.Q4"],
                       'CELL_TYPE': {'RadioNode': ['EUtranCellFDD', 'EUtranCellTDD']}, 'KPI_ADJUST': 7}
        },
        "nvs": {},
        "nas_outage": {},
        "ops": {
            'OPS_01': {'FILTERED_NODES_PER_HOST': 1, USER_ROLES: OPS_USER_ROLES + COM_ROLES, SUPPORTED_NODE_TYPES: [NODES.BSC],
                       TOTAL_NODES: 16, 'MAX_SESSION_COUNT_PER_NODE': 35,
                       SCHEDULED_TIMES_STRINGS: ["03:30:00", "09:30:00", "15:30:00", "21:30:00"], "SESSION_COUNT": 14,
                       THREAD_QUEUE_TIMEOUT: 2400, EXCLUDE_NODES_FROM: ["CELLMGT_15"]}
        },
        "migration": {},
        "parmgt": {
            'PARMGT_01': {NUM_USERS: 5, USER_ROLES: ["Parameter_Management_Administrator", "Cmedit_Administrator"],
                          TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [NODES.RADIONODE],
                          NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                          SCHEDULED_TIMES_STRINGS: ["06:00:00"], "DAILY_SLEEP": 23 * 60 * 60 + 40 * 60,
                          "NUMBER_OF_ITERATIONS": 32, "TIME_IN_MINUTES_BETWEEN_ITERATIONS": 15},
            'PARMGT_03': {NUM_USERS: 1, USER_ROLES: ["Parameter_Management_Administrator"], "NUMBER_OF_MOS": 5000,
                          SCHEDULED_TIMES_STRINGS: ["14:00:00"], SCHEDULED_DAYS: ["FRIDAY"]}
        },
        "plm": {
            'PLM_01': {NUM_USERS: 1, USER_ROLES: ["LinkManagement_Administrator", "LinkManagement_Operator",
                                                  "Cmedit_Administrator"], SCHEDULE_SLEEP: 60 * 60,
                       "NODE_TYPES": [NODES.RADIONODE, NODES.SGSN_MME, NODES.MINILINK_6352, NODES.ROUTER6672, NODES.ROUTER6675,
                                      NODES.MINI_LINK_669x],
                       'MAX_LINKS': 21980},
            'PLM_02': {NUM_USERS: 1, USER_ROLES: ["LinkManagement_Administrator", "LinkManagement_Operator",
                                                  "Cmedit_Administrator"], TOTAL_NODES: 20, SCHEDULE_SLEEP: 60 * 60,
                       SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_669x]}
        },
        "pkiadmin": {},
        "pm_rest_nbi": {},
        "pm": {
            'PM_44': {},
            'PM_80': {},
            'PM_81': {},
            'PM_97': {},
            'PM_98': {},
            'PM_99': {},
            'PM_100': {},
            'PM_101': {}
        },
        "reparenting": {
            "REPARENTING_01": {},
            "REPARENTING_02": {},
            "REPARENTING_03": {},
            "REPARENTING_04": {},
            "REPARENTING_05": {},
            "REPARENTING_06": {},
            "REPARENTING_07": {},
            "REPARENTING_08": {},
            "REPARENTING_09": {},
            "REPARENTING_10": {},
            "REPARENTING_11": {},
            "REPARENTING_12": {}
        },
        "secui": {
            'SECUI_01': {'NUMBER_OF_SECURITY_ADMINS': 10, 'NUMBER_OF_USERS_TO_CREATE': 300,
                         'NUMBER_OF_ROLES_TO_ASSIGN': 5, 'THREAD_QUEUE_TIMEOUT': 2 * 60 * 60,
                         USER_ROLES: SECUI_01_USER_ROLES},
            'SECUI_02': {'NUMBER_OF_USERS': 30, 'NUMBER_OF_ROLES': 5, SCHEDULE_SLEEP: 24 * 60 * 60},
            'SECUI_03': {SCHEDULED_TIMES_STRINGS: ["00:00:00"]},
            'SECUI_05': {NUM_USERS: 50, USER_ROLES: ["SECURITY_ADMIN"], 'CREATED_ROLE_COUNT': 6},
            'SECUI_06': {'PKI_NAME': 'Secui_Six_{0}', USER_ROLES: ["PKI_Administrator"], NUM_USERS: 1},
            'SECUI_07': {'NUM_TARGET_GROUPS': 495, TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE,
                                                                                          NODES.MINI_LINK_Indoor]},
            'SECUI_08': {SCHEDULE_SLEEP: 60 * 24 * 60, 'NUM_TARGET_GROUPS': 5},
            'SECUI_12': {NUM_USERS: 1, USER_ROLES: ["SECURITY_ADMIN"], SCHEDULE_SLEEP: 60 * 15,
                         "USER_NAME": "RemoteUser_01",
                         "USER_PASSWORD": "RemotePassword_01", "authType": "REMOTEAUTHN", "remoteAuthProfile": "STANDARD",
                         "baseDN": "dc=acme,dc=com", "ldapConnectionMode": "LDAP", "userBindDNFormat": "uid=$user",
                         "bindDN": "cn=extldapadmin,ou=people,dc=acme,dc=com", "bindPwd": "Externalldapadmin01",
                         "NETWORK_TYPE": "small", "INTERVAL_DURATION": 24, "INITIAL_EXPIRATION": "01:00",
                         "CUSTOM_USER_ROLES": ["ACME_PKI_Operator", "ACME_NodeSecurity_Operator",
                                               "ACME_SecGW_Operator"],
                         "CUSTOM_TARGET_GROUPS": ["ACMENORTH", "ACMESOUTH", "NORTH"], "USER_AUTH_MODE": "remote",
                         "FEDERATED_USER_NAME": "fedacmeenduser2"}
        },
        "sev": {
            'SEV_01': {NUM_USERS: 5, USER_ROLES: ["SEV_Administrator", "SEV_Operator"], NUM_NODES: {NODES.ESC: 5},
                       NODE_FILTER: {NODES.ESC: {"node_version": ["22.Q3"]}}, SCHEDULE_SLEEP: 60 * 15,
                       CHECK_NODE_SYNC: True},
            'SEV_02': {NUM_USERS: 5, USER_ROLES: ["SEV_Administrator", "SEV_Operator"], NUM_NODES: {NODES.ESC: 5},
                       SCHEDULE_SLEEP: 60 * 15}
        },
        "shm": {
            'SHM_01': {NUM_NODES: {NODES.ERBS: -1}, SCHEDULED_TIMES_STRINGS: ["19:45:00"],
                       "PIB_VALUES": {"SMRS_ERBS_NoOf_BACKUP_FILES": "2"},
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["20:15:00"], 'NUM_NODES_PER_BATCH': 320, MAX_NODES: 320},
            'SHM_02': {TOTAL_NODES: 100, SCHEDULED_TIMES_STRINGS: ["12:00:00"],
                       NUM_NODES: {NODES.RADIONODE: 100},
                       "PIB_VALUES": {"SMRS_RadioNode_NoOf_BACKUP_FILES": "2"},
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ["ENodeB", "GNodeB"]}},
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["12:30:00"], 'NUM_NODES_PER_BATCH': 100, MAX_NODES: 100},
            'SHM_03': {'FILTERED_NODES_PER_HOST': 80, SCHEDULED_TIMES_STRINGS: ["06:30:00"],
                       NUM_NODES: {NODES.ERBS: -1},
                       SCHEDULED_DAYS: ['WEDNESDAY'], MAX_NODES: 200,
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"], SKIP_SYNC_CHECK: False,
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_04': {NUM_USERS: 1, USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"],
                       NUM_NODES: {NODES.ERBS: 320}, SCHEDULED_TIMES_STRINGS: ["11:00:00"], 'TIMEOUT': 1800,
                       SCHEDULED_DAYS: ['WEDNESDAY']},
            'SHM_05': {'FILTERED_NODES_PER_HOST': 100, MAX_NODES: 100, SCHEDULED_DAYS: ['THURSDAY'],
                       SCHEDULED_TIMES_STRINGS: ["06:30:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       NUM_NODES: {NODES.RADIONODE: -1}, EXCLUDE_NODES_FROM: ['SHM_06'], SKIP_SYNC_CHECK: False,
                       NODE_FILTER: {
                           NODES.RADIONODE: {'managed_element_type': ["ENodeB"], 'model_identity': ['', '-']}},
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1", "NUMBER_OF_SOFTWARE_PACKAGES_TO_RETAIN_FOR_RADIONODE": "5"}},
            'SHM_06': {NUM_USERS: 3, TOTAL_NODES: 3, SCHEDULE_SLEEP: 60 * 60,
                       SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.ROUTER6672, NODES.BSC,
                                              NODES.ROUTER6675],
                       "PIB_VALUES": {"SMRS_ERBS_NoOf_BACKUP_FILES": "2", "SMRS_RadioNode_NoOf_BACKUP_FILES": "2",
                                      "SMRS_Router6672_NoOf_BACKUP_FILES": "2",
                                      "SMRS_Router6675_NoOf_BACKUP_FILES": "2", "SMRS_BSC_NoOf_BACKUP_FILES": "2"},
                       EXCLUDE_NODES_FROM: ['SHM_01', 'SHM_18', 'SHM_03', 'SHM_24', 'SHM_05', 'ASU_01', 'NPA_01'],
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ["ENodeB"]}}, SKIP_SYNC_CHECK: False,
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator", "Ops_Operator", "WinFIOL_Operator",
                                    "Element_Manager_Operator", "FIELD_TECHNICIAN", "Scripting_Operator"] + COM_ROLES},
            'SHM_07': {NUM_USERS: 20, NUM_NODES: {NODES.ERBS: -1, NODES.RADIONODE: -1, NODES.MINI_LINK_Indoor: -1,
                                                  NODES.MINI_LINK_669x: -1},
                       SCHEDULE_SLEEP: 3000,
                       USER_ROLES: ['Shm_Administrator', 'Network_Explorer_Administrator']},
            'SHM_18': {NUM_NODES: {NODES.ERBS: 15}, SCHEDULED_DAYS: ['SUNDAY'], MAX_NODES: 15,
                       "PIB_VALUES": {"SMRS_ERBS_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["18:30:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["19:00:00"]},
            'SHM_19': {NUM_NODES: {}, MAX_NODES_TO_ALLOCATE: 1000, SCHEDULED_TIMES_STRINGS: ["19:00:00"],
                       SCHEDULED_DAYS: ['THURSDAY']},
            'SHM_20': {NUM_NODES: {}, MAX_NODES_TO_ALLOCATE: 1000, SCHEDULED_TIMES_STRINGS: ["19:00:00"],
                       SCHEDULED_DAYS: ['FRIDAY']},
            'SHM_21': {NUM_NODES: {}, SCHEDULED_TIMES_STRINGS: ["19:00:00"], SCHEDULED_DAYS: ['SATURDAY'], MAX_NODES_TO_ALLOCATE: 1000},
            'SHM_23': {'NODES_PER_HOST': 100, NUM_NODES: {NODES.MINI_LINK_Indoor: 50}, MAX_NODES: 50,
                       "PIB_VALUES": {"SMRS_MINILINKIndoor_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["02:30:00"],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["03:00:00"]},
            'SHM_24': {'NODES_PER_HOST': 100, NUM_NODES: {NODES.MINI_LINK_Indoor: 50},
                       SCHEDULED_TIMES_STRINGS: ["06:30:00"],
                       EXCLUDE_NODES_FROM: ['SHM_06'], "MLTN_TIMEOUT": 90, NUM_USERS: 1,
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"], SKIP_SYNC_CHECK: False,
                       SCHEDULED_DAYS: ['MONDAY'], MAX_NODES: 50, "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_25': {'FILTERED_NODES_PER_HOST': 80, NUM_NODES: {NODES.ERBS: -1}, MAX_NODES: 1000,
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["1:00:00"], SKIP_SYNC_CHECK: False,
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_26': {NUM_NODES: {NODES.ERBS: 16}, MAX_NODES: 16, "PIB_VALUES": {"SMRS_ERBS_NoOf_BACKUP_FILES": "2"}},
            'SHM_27': {'NODES_PER_HOST': 100, NUM_NODES: {NODES.SIU02: -1, NODES.TCU02: -1},
                       SCHEDULED_TIMES_STRINGS: ["06:30:00"],
                       NUM_USERS: 1, SCHEDULED_DAYS: ['SATURDAY'],
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"], SKIP_SYNC_CHECK: False,
                       MAX_NODES: 100, "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_31': {'NODES_PER_HOST': 84, NUM_NODES: {NODES.MINILINK_6352: -1},
                       SCHEDULED_TIMES_STRINGS: ["05:30:00"], NUM_USERS: 1, SCHEDULED_DAYS: ['TUESDAY'],
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"], 'TIMEOUT': 1800,
                       MAX_NODES: 50, "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       SKIP_SYNC_CHECK: False, "MAX_NODES_TO_ALLOCATE": 50, "MINIMUM_ALLOWABLE_NODE_COUNT": 15,
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_32': {'FILTERED_NODES_PER_HOST': 100, NUM_NODES: {NODES.MINILINK_6352: -1}, MAX_NODES: 50,
                       "PIB_VALUES": {"SMRS_MINILINK6352_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["02:00:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["02:30:00"],
                       'TIMEOUT': 1800, USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"], NUM_USERS: 1,
                       "MINIMUM_ALLOWABLE_NODE_COUNT": 15, "MAX_NODES_TO_ALLOCATE": 50},
            'SHM_33': {'NODES_PER_HOST': 100, TOTAL_NODES: 50, SUPPORTED_NODE_TYPES: [NODES.ROUTER6672],
                       MAX_NODES: 50, NUM_USERS: 1, SCHEDULED_TIMES_STRINGS: ["06:30:00"],
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"],
                       SCHEDULED_DAYS: ['SUNDAY'], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       SKIP_SYNC_CHECK: False, "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_34': {'NODES_PER_HOST': 100, TOTAL_NODES: 105, SUPPORTED_NODE_TYPES: [NODES.ROUTER6672],
                       MAX_NODES: 105, "PIB_VALUES": {"SMRS_Router6672_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["00:30:00", "02:00:00", "04:30:00", "08:00:00", "10:30:00", "13:00:00",
                                                 "15:30:00", "17:00:00", "19:30:00", "23:00:00"],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["01:00:00", "02:30:00", "05:00:00", "08:30:00", "11:00:00",
                                                          "13:30:00", "16:00:00", "17:30:00", "20:00:00", "23:30:00"]},
            'SHM_36': {'NODES_PER_HOST': 2, NUM_USERS: 1, NUM_NODES: {NODES.BSC: 20}, MAX_NODES: 20,
                       SCHEDULED_TIMES_STRINGS: ["06:00:00"], SCHEDULED_DAYS: ['FRIDAY'],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"], SKIP_SYNC_CHECK: True,
                       USER_ROLES: ["Shm_Administrator", "Ops_Operator", "WinFIOL_Operator",
                                    "Element_Manager_Operator", "FIELD_TECHNICIAN", "Scripting_Operator"] + COM_ROLES,
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_40': {NUM_USERS: 1, NUM_NODES: {NODES.ROUTER6675: 50}, SCHEDULED_DAYS: ['SUNDAY'],
                       SCHEDULED_TIMES_STRINGS: ["06:30:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       'NODES_PER_HOST': 20, MAX_NODES: 50, EXCLUDE_NODES_FROM: ['SHM_06'], SKIP_SYNC_CHECK: False,
                       USER_ROLES: ["Shm_Administrator", "Network_Explorer_Administrator"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_41': {'NODES_PER_HOST': 40, TOTAL_NODES: 50, MAX_NODES: 50, SUPPORTED_NODE_TYPES: [NODES.ROUTER6675],
                       "PIB_VALUES": {"SMRS_Router6675_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["23:00:00"], EXCLUDE_NODES_FROM: ['SHM_06'],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["23:30:00"]},
            'SHM_42': {'NODES_PER_HOST': 20, NUM_NODES: {NODES.MINI_LINK_669x: 50},
                       SCHEDULED_TIMES_STRINGS: ["03:15:00"],
                       EXCLUDE_NODES_FROM: ['SHM_06'], "MLTN_TIMEOUT": 90, NUM_USERS: 1, MAX_NODES: 50,
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"], SKIP_SYNC_CHECK: False,
                       'TIMEOUT': 1800, SCHEDULED_DAYS: ['MONDAY'],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["03:45:00"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_43': {'NODES_PER_HOST': 40, NUM_NODES: {NODES.MINI_LINK_669x: 50},
                       "PIB_VALUES": {"SMRS_MINILINKIndoor_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["19:00:00"],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["19:30:00"], EXCLUDE_NODES_FROM: ['SHM_06'], MAX_NODES: 50},
            'SHM_44': {NUM_NODES: {NODES.SCU: 300}, MAX_NODES: 300, SKIP_SYNC_CHECK: True, SCHEDULED_DAYS: ['FRIDAY'],
                       SCHEDULED_TIMES_STRINGS: ["10:30:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["11:00:00"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_47': {NUM_NODES: {NODES.RADIONODE: 384},
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                       MAX_NODES: 320, SCHEDULED_DAYS: ['WEDNESDAY'], SCHEDULED_TIMES_STRINGS: ["08:30:00"],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["09:00:00"]}
        },
        "top": {
            'TOP_01': {TOTAL_NODES: 10, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], NUM_USERS: 10,
                       USER_ROLES: ["Topology_Browser_Administrator"], LTE_CELL_CHECK: True, CHECK_NODE_SYNC: True,
                       NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "ENodeB|NodeB", "GNodeB"]}},
                       EXCLUDE_NODES_FROM: ["CMSYNC_02", "CMSYNC_04", "CMSYNC_06", "ENMCLI_02"],
                       'THREAD_QUEUE_TIMEOUT': 60 * 25}
        }
    }
}
