# ********************************************************************
# Name    : Sixty Network
# Summary : If a profile is not listed here in this file, please refer to default values config file (forty_network.py) instead.
# ********************************************************************

from basic_network import (USER_KEYS as USER, NODE_KEYS as NODE, TIME_KEYS as TIME, IMP_EXP_KEYS as IMP_EXP,
                           AMOS_USER_ROLES, CNX_RULEMODULES, NSX_RULEMODULES, GRX_RULEMODULES, FMX_RULEMODULES,
                           LTE_CELL_CHECK, NeTypesEnum as NODES, MAX_NODES, GEO_USER_ROLES, NUM_EVENTS,
                           MAX_NODES_TO_ALLOCATE, LARGE_BSC_ONLY, CHECK_NODE_SYNC, ERROR_HANDLING, ATTEMPT_RECOVERY,
                           TIMEOUT, SMALL_BSC_ONLY, STANDARD, GSM, CELL_TYPE, GERANCELL, THREAD_QUEUE_TIMEOUT,
                           NUM_CELLS_PER_USER, SKIP_SYNC_CHECK, COM_ROLES)
from profile_cmds import ENMCLI_COMMANDS, CMSYNC_MCD_BURST_MO_TYPE_SETTINGS, CELLMGT_MO_ATTRIBUTE_DATA, CMSYNC_45_AVC_BURST_MO_TYPE_SETTINGS

INTERFACE, FILETYPE, FLOW, IMPORT_TYPE, CREATE_DELETE_LIVE, CREATE_DELETE_CONFIG, UPDATE_LIVE, UPDATE_CONFIG = IMP_EXP
SCHEDULED_DAYS, SCHEDULE_SLEEP, SCHEDULED_TIMES_STRINGS = TIME
NUM_USERS, USER_ROLES = USER
NUM_NODES, SUPPORTED_NODE_TYPES, TOTAL_NODES, EXCLUDE_NODES_FROM, NODE_FILTER = NODE
TARGET_BSC_ID = "TARGET_BSC_ID"
TOTAL_TARGET_ALARMS = 4500000
FM_02_TOTAL_ALARMS = 4 * 5 * 60 * 24 * 40
FM_03_TOTAL_ALARMS = 4 * 60 * 8 * 200

sixty_k_network = {
    "sixty_k_network": {
        "amos": {
            'AMOS_01': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 130, NUM_USERS: 130, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ["AMOS_02", "AMOS_03", "AMOS_04", "AMOS_05", "AMOS_08", "ASU_01", "NPA_01"],
                        'VERIFY_TIMEOUT': 60 * 20,
                        SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute)
                                                  for hour in range(11, 15) for minute in ["00", "30"]],
                        'COMMANDS_PER_ITERATION': 68,
                        'COMMANDS': ["get upgradepackage", "get lp", "get pci", "get dcgm", "cabx"]},
            'AMOS_02': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 130, NUM_USERS: 130, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ["AMOS_01", "AMOS_03", "AMOS_04", "AMOS_05", "AMOS_08", "ASU_01", "NPA_01"],
                        'VERIFY_TIMEOUT': 60 * 20,
                        SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(str(hour).zfill(2), minute)
                                                  for hour in range(9, 17) for minute in ["00", "30"]],
                        'COMMANDS_PER_ITERATION': 68,
                        'COMMANDS': ["confb", "get PmService PmServiceId", "pst", "altuc"]},
            'AMOS_03': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 130, NUM_USERS: 130, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ['AMOS_01', 'AMOS_02', 'AMOS_04', 'AMOS_05', 'AMOS_08', "ASU_01", "NPA_01"],
                        'VERIFY_TIMEOUT': 60 * 20,
                        SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(str(hour).zfill(2), minute)
                                                  for hour in range(7, 19) for minute in ["00", "30"]],
                        'COMMANDS_PER_ITERATION': 68,
                        'COMMANDS': ["confd", "al", "alt", "altuc", "lst cell"]},
            'AMOS_04': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 129, NUM_USERS: 129, USER_ROLES: AMOS_USER_ROLES, 'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ["AMOS_01", "AMOS_02", "AMOS_03", "AMOS_05", "AMOS_08", "ASU_01", "NPA_01"],
                        'VERIFY_TIMEOUT': 60 * 20,
                        SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(str(hour).zfill(2), minute)
                                                  for hour in range(0, 24) for minute in ["00", "30"]],
                        'COMMANDS_PER_ITERATION': 68,
                        'COMMANDS': ["get ManagedElement", "fget sec noofusedAntenna", "st fdd", "st cell",
                                     "lst RfPort", "st termpointtoenb"]},
            'AMOS_05': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                        TOTAL_NODES: 60, NUM_USERS: 60, USER_ROLES: AMOS_USER_ROLES + ['Scripting_Operator'],
                        'MAX_AMOS_SESSIONS': 150,
                        EXCLUDE_NODES_FROM: ["AMOS_01", "AMOS_02", "AMOS_03", "AMOS_05", "AMOS_08", "ASU_01", "NPA_01"],
                        SCHEDULE_SLEEP: 60 * 10, 'COMMANDS_PER_ITERATION': 22, 'TIMEOUT': 10, 'NUM_PARALLEL': 1,
                        'COMMANDS': ["al", "kget pci", "lk EUtraNetwork=1", "getmom", "shget pci"]}
        },
        "aid": {},
        "ap": {},
        "apt": {},
        "asr_l": {
            'ASR_L_01': {NUM_NODES: {NODES.ERBS: -1, NODES.RADIONODE: -1},
                         NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                         USER_ROLES: ["ASR_Administrator", "ASR-L_Administrator", "Cmedit_Administrator"],
                         "SLEEP_TIME": 60, "NB_IP": "", "PORT": ""}
        },
        "asr_n": {
            'ASR_N_01': {NUM_NODES: {NODES.RADIONODE: -1},
                         NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['GNodeB']}},
                         USER_ROLES: ["ASR_Administrator", "ASR-L_Administrator", "Cmedit_Administrator"],
                         "SLEEP_TIME": 60, "NB_IP": "", "PORT": ""}
        },
        "asu": {},
        "bur": {},
        "ca": {
            'CA_01': {NUM_USERS: 1, USER_ROLES: ['CM_Audit_Operator'], 'RETRIES': 18, 'INTERVAL': 900,
                      SCHEDULED_TIMES_STRINGS: ['00:30:00']}
        },
        'cbrs': {},
        "cellmgt": {
            'CELLMGT_07': {SUPPORTED_NODE_TYPES: [NODES.RNC], TOTAL_NODES: 1, USER_ROLES: ["ADMINISTRATOR"],
                           'MO_TYPE': 'UtranCell', 'MO_ATTRIBUTE_DATA': CELLMGT_MO_ATTRIBUTE_DATA,
                           'REQUIRED_NUMBER_OF_NODES': 1, 'REQUIRED_NUMBER_OF_CELLS_PER_NODE': 64,
                           SCHEDULED_TIMES_STRINGS: ["11:30:00", "23:30:00"]},
            'CELLMGT_13': {USER_ROLES: ["ADMINISTRATOR"], NUM_USERS: 3, NUM_NODES: {NODES.BSC: 3},
                           "NUM_CELLS_PER_USER": 100, CHECK_NODE_SYNC: True,
                           "RELATION_TYPE": "ExternalGeranCellRelation", STANDARD: GSM,
                           CELL_TYPE: GERANCELL, LARGE_BSC_ONLY: False, "RELATIONS_TO_DELETE": [],
                           SCHEDULED_TIMES_STRINGS: ["01:55:00", "03:00:00", "20:30:00", "22:50:00"],
                           "RESERVED_CGI_VALUE": {"mnc": 999, "mcc": 999, "lac": 9998},
                           "MO_ID_START_RANGE": 1, EXCLUDE_NODES_FROM: ["CELLMGT_15", "CMIMPORT_18", "CMIMPORT_19",
                                                                        "CMIMPORT_21", "CMIMPORT_22"]},
            'CELLMGT_14': {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: 15}, NUM_USERS: 15,
                           THREAD_QUEUE_TIMEOUT: 60 * 15, 'UI_DISPLAY_LIMIT': 50,
                           STANDARD: GSM, CELL_TYPE: GERANCELL,
                           SCHEDULED_TIMES_STRINGS: ['00:45:00', '01:45:00', '02:45:00', '03:45:00', '04:45:00',
                                                     '05:45:00', '06:45:00', '07:45:00', '08:45:00', '09:45:00',
                                                     '10:45:00', '11:45:00', '12:45:00', '13:45:00', '14:45:00',
                                                     '15:45:00', '16:45:00', '17:45:00', '18:45:00', '19:45:00',
                                                     '20:45:00', '21:45:00', '22:45:00', '23:45:00']},
            'CELLMGT_15': {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, NUM_CELLS_PER_USER: 3,
                           NUM_USERS: 40,
                           THREAD_QUEUE_TIMEOUT: 60 * 5, STANDARD: GSM, 'REMOVE_RESERVED_GERANCELLS': True,
                           CELL_TYPE: GERANCELL, LARGE_BSC_ONLY: False, CHECK_NODE_SYNC: True,
                           MAX_NODES_TO_ALLOCATE: 40, EXCLUDE_NODES_FROM: ["ENMCLI_06", "ENMCLI_07", "OPS_01",
                                                                           "CMIMPORT_19", "CMIMPORT_18", "CELLMGT_13"],
                           SCHEDULED_TIMES_STRINGS: ['09:35:00', '10:35:00', '11:35:00', '12:35:00', '13:35:00',
                                                     '14:35:00', '15:35:00', '16:35:00', '17:35:00', '18:35:00']}
        },
        "cli_mon": {},
        "cmevents_nbi": {},
        "cmexport": {
            'CMEXPORT_03': {NUM_NODES: {NODES.ERBS: -1, NODES.RADIONODE: -1, NODES.RNC: -1, NODES.RBS: -1,
                                        NODES.Shared_CNF: -1},
                            'FILETYPE': 'dynamic',
                            NUM_USERS: 20, 'NUMBER_OF_EXPORTS': 20, USER_ROLES: ['CM_REST_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ["03:45:00", "08:45:00", "14:15:00", "21:15:00"],
                            'THREAD_QUEUE_TIMEOUT': 5400},
            'CMEXPORT_12': {
                "ENM_NE_TYPES": [NODES.ERBS, NODES.RADIONODE, NODES.RBS, NODES.RNC, NODES.SGSN_MME, NODES.MGW,
                                 NODES.BSC, NODES.Shared_CNF],
                SCHEDULED_TIMES_STRINGS: ["18:00:00"], 'FILETYPE': 'dynamic',
                'NODE_BATCH_SIZE': 500, NUM_USERS: 1, USER_ROLES: ['CM_REST_Administrator'],
                INTERFACE: 'NBI', SCHEDULED_DAYS: ['SUNDAY', 'TUESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY']},
            'CMEXPORT_21': {NUM_NODES: {NODES.BSC: -1}, FILETYPE: '3GPP',
                            SCHEDULED_TIMES_STRINGS: ["09:15:00"], NUM_USERS: 1, USER_ROLES: ['Cmedit_Administrator'],
                            'BATCH_MO_SIZE': 100, 'MO_VALUES': {'GeranCell': 8000}, MAX_NODES_TO_ALLOCATE: 1},
            'CMEXPORT_22': {'FILETYPE': '3GPP', SCHEDULED_TIMES_STRINGS: ["02:45:00"],
                            NUM_USERS: 1, USER_ROLES: ['Cmedit_Administrator'], "FILE_IN": "GSM_EXPORT_FILTER.txt",
                            NUM_NODES: {NODES.BSC: -1}, LARGE_BSC_ONLY: False},
            'CMEXPORT_26': {NUM_NODES: {NODES.BSC: -1}, SCHEDULED_TIMES_STRINGS: ["10:45:00"], 'FILETYPE': '3GPP',
                            'BATCH_MO_SIZE': 100, 'MO_VALUES': {'GeranCell': 8000}, NUM_USERS: 1,
                            USER_ROLES: ['Cmedit_Administrator'], MAX_NODES_TO_ALLOCATE: 1,
                            "FILE_IN": "CmExport_26_FilterFile.txt", 'BATCH_FILTER': 'true'},
            'CMEXPORT_27': {NUM_NODES: {NODES.Shared_CNF: -1}, SCHEDULED_TIMES_STRINGS: ["16:00:00"],
                            NODE_FILTER: {NODES.Shared_CNF: {'network_function': ['vCU-CP']}},
                            'FILETYPE': 'dynamic', INTERFACE: 'NBI', "FILE_IN": "CmExport_27_FilterFile.txt",
                            NUM_USERS: 1, USER_ROLES: ['CM_REST_Administrator', 'CM_REST_Operator']}
        },
        "cmimport": {
            'CMIMPORT_18': {MAX_NODES_TO_ALLOCATE: 1, NUM_NODES: {NODES.BSC: -1}, 'BATCH_MO_SIZE': 5,
                            CHECK_NODE_SYNC: True,
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            EXCLUDE_NODES_FROM: ["CELLMGT_13", "CELLMGT_15", "CMIMPORT_19", "CMIMPORT_21",
                                                 "CMIMPORT_22"],
                            'MO_VALUES': {'ExternalGeranCellRelation': 2048}, LARGE_BSC_ONLY: False,
                            'MOS_ATTRS': {'ExternalGeranCellRelation': ["awOffset", "bqOffset", "bqOffsetAfr",
                                                                        "bqOffsetAwb", "cand",
                                                                        "externalGeranCellRelationId", "gprsValid",
                                                                        "hiHyst", "kHyst", "kOffset", "lHyst",
                                                                        "lOffset", "loHyst", "offset", "pROffset",
                                                                        "relType", "tRHyst", "tROffset"]},
                            SCHEDULED_TIMES_STRINGS: ['02:40:01', '03:40:01', '20:20:01', '23:20:01'], FILETYPE: '3GPP',
                            INTERFACE: 'NBIv2', FLOW: 'live_config', IMPORT_TYPE: CREATE_DELETE_LIVE,
                            ERROR_HANDLING: 'stop-on-error', ATTEMPT_RECOVERY: False, TIMEOUT: 25 * 60},
            'CMIMPORT_19': {'MO_VALUES': {'GeranCellRelation': 1000}, SMALL_BSC_ONLY: True, CHECK_NODE_SYNC: True,
                            'MOS_ATTRS': {'GeranCellRelation': ["awOffset", "bqOffset", "bqOffsetAfr", "bqOffsetAwb",
                                                                "cand", "cs", "geranCellRelationId", "gprsValid",
                                                                "hiHyst", "kHyst", "kOffset", "lHyst", "lOffset",
                                                                "loHyst", "offset", "pROffset", "relType",
                                                                "relationDirection", "tRHyst", "tROffset"]},
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'], FILETYPE: '3GPP',
                            MAX_NODES_TO_ALLOCATE: 24, NUM_NODES: {NODES.BSC: -1}, 'BATCH_MO_SIZE': 5,
                            SCHEDULED_TIMES_STRINGS: ['04:40:01'], FLOW: 'live_config',
                            IMPORT_TYPE: CREATE_DELETE_LIVE, INTERFACE: 'NBIv2',
                            ERROR_HANDLING: ["continue-on-error-node", "parallel"],
                            EXCLUDE_NODES_FROM: ["CELLMGT_13", "CELLMGT_15", "CMIMPORT_18", "CMIMPORT_21",
                                                 "CMIMPORT_22"],
                            ATTEMPT_RECOVERY: False, TIMEOUT: 30 * 60},
            "CMIMPORT_20": {SUPPORTED_NODE_TYPES: [NODES.BSC], TOTAL_NODES: 95, CHECK_NODE_SYNC: True,
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            'MO_VALUES': {'GeranCell': 100},
                            'MOS_ATTRS': {'GeranCell': ['irc', 'xRange', 'state', 'fnOffset', 'bcchType']},
                            'MOS_DEFAULT': {
                                'GeranCell': [('irc', "ON"), ('xRange', "NO"), ('state', "HALTED"), ('fnOffset', 0),
                                              ('bcchType', "NCOMB")]},
                            'MOS_MODIFY': {
                                'GeranCell': [('irc', "OFF"), ('xRange', "YES"), ('state', "ACTIVE"), ('fnOffset', 1),
                                              ('bcchType', "COMB")]},
                            'BATCH_MO_SIZE': 100, FILETYPE: '3GPP', SCHEDULED_TIMES_STRINGS: ['07:50:00'],
                            INTERFACE: 'NBIv2', IMPORT_TYPE: UPDATE_LIVE, ATTEMPT_RECOVERY: False,
                            ERROR_HANDLING: ['continue-on-error-node', 'sequential'], FLOW: 'live_config',
                            TIMEOUT: 60 * 60},
            'CMIMPORT_21': {'MO_VALUES': {'ExternalGeranCellRelation': 100}, SMALL_BSC_ONLY: True,
                            'MOS_ATTRS': {'ExternalGeranCellRelation': ['awOffset', 'bqOffset', 'bqOffsetAfr',
                                                                        'bqOffsetAwb', 'cand',
                                                                        'externalGeranCellRelationId', 'gprsValid',
                                                                        'hiHyst', 'kHyst', 'kOffset', 'lHyst',
                                                                        'lOffset', 'loHyst', 'offset', 'pROffset',
                                                                        'relType', 'tRHyst', 'tROffset']},
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'], FILETYPE: 'dynamic',
                            MAX_NODES_TO_ALLOCATE: 1, NUM_NODES: {NODES.BSC: -1}, 'BATCH_MO_SIZE': 5,
                            CHECK_NODE_SYNC: True,
                            SCHEDULED_TIMES_STRINGS: ['01:35:00', '01:45:00', '21:25:00', '21:40:00'],
                            FLOW: 'live_config', IMPORT_TYPE: CREATE_DELETE_LIVE, ERROR_HANDLING: 'stop-on-error',
                            INTERFACE: 'NBIv2', EXCLUDE_NODES_FROM: ["CELLMGT_13", "CMIMPORT_19", "CMIMPORT_18",
                                                                     "CMIMPORT_22"],
                            ATTEMPT_RECOVERY: False, TIMEOUT: 15 * 60},
            'CMIMPORT_22': {MAX_NODES_TO_ALLOCATE: 10, NUM_NODES: {NODES.BSC: -1}, CHECK_NODE_SYNC: True,
                            "MOS_PER_NODE": 30, "MO_ID_START_RANGE": 1, "PARENT_MO": "GeranCellM",
                            "TARGET_MO": "GeranCell", "MO_ATTRS": {"geranCellId": 0, "cSysType": "GSM900", "cgi": 0},
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ['05:00:01', '06:00:01'], FLOW: 'live_config',
                            IMPORT_TYPE: CREATE_DELETE_LIVE, INTERFACE: 'NBIv2',
                            EXCLUDE_NODES_FROM: ["CELLMGT_13", "CMIMPORT_18", "CMIMPORT_19", "CMIMPORT_21"],
                            "NODES_PER_JOB": 5, LARGE_BSC_ONLY: False, "CGI_ROOT_VALUE": "999-999-9999",
                            ATTEMPT_RECOVERY: False, TIMEOUT: 15 * 60},
            'CMIMPORT_23': {TOTAL_NODES: 25, SUPPORTED_NODE_TYPES: [NODES.EPG_OI], "MOS_PER_NODE": 400,
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            FILETYPE: 'dynamic', INTERFACE: 'NBIv2', FLOW: 'live_config',
                            SCHEDULED_TIMES_STRINGS: ['01:25:01'],
                            ERROR_HANDLING: ['continue-on-error-node', 'sequential'],
                            IMPORT_TYPE: CREATE_DELETE_LIVE, TIMEOUT: 90 * 60, ATTEMPT_RECOVERY: False},
            'CMIMPORT_27': {USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ['21:00:01'], SCHEDULED_DAYS: ['SATURDAY', 'SUNDAY'],
                            FILETYPE: 'dynamic', FLOW: 'live_config', INTERFACE: 'NBIv2',
                            ERROR_HANDLING: 'continue-on-error-node', ATTEMPT_RECOVERY: False,
                            IMPORT_TYPE: CREATE_DELETE_LIVE, TIMEOUT: 180 * 60, 'BSC_ID': 'M47B94',
                            'EXPECTED_NUM_CHANGES': {'delete': 450, 'create': 33465}},
            'CMIMPORT_28': {SUPPORTED_NODE_TYPES: [NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['GNodeB']}},
                            TOTAL_NODES: 150, USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            'BATCH_MO_SIZE': 100, FILETYPE: 'dynamic', INTERFACE: 'NBIv2', FLOW: 'live_config',
                            SCHEDULED_TIMES_STRINGS: ['04:15:00', '08:50:00', '10:50:00', '13:50:00', '22:40:00'],
                            ERROR_HANDLING: 'continue-on-error-node', IMPORT_TYPE: UPDATE_LIVE,
                            'MO_VALUES': {'EUtranCellRelation': 100},
                            'MOS_ATTRS': {'EUtranCellRelation': ['userLabel']},
                            'MOS_DEFAULT': {'EUtranCellRelation': ('userLabel', 'null')},
                            'MOS_MODIFY': {'EUtranCellRelation': ('userLabel', 'cmimport_28')},
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'],
                            TIMEOUT: 60 * 60},
            'CMIMPORT_29': {SUPPORTED_NODE_TYPES: [NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                            TOTAL_NODES: 500, USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            'MO_VALUES': {'EUtranCellRelation': 10}, 'BATCH_MO_SIZE': 100,
                            SCHEDULED_TIMES_STRINGS: ['04:50:00', '05:05:00', '05:20:00', '06:40:00', '06:55:00',
                                                      '07:10:00', '08:35:00', '09:25:00', '11:15:00', '11:20:00',
                                                      '11:25:00', '11:40:00', '14:10:00', '14:25:00', '17:00:00',
                                                      '19:30:00', '19:45:00', '20:00:00', '20:45:00', '21:15:00'],
                            FILETYPE: 'dynamic', INTERFACE: 'NBIv2',
                            FLOW: 'live_config', ERROR_HANDLING: 'continue-on-error-node', IMPORT_TYPE: UPDATE_LIVE,
                            'MOS_DEFAULT': {'EUtranCellRelation': ('isRemoveAllowed', 'true')},
                            'MOS_MODIFY': {'EUtranCellRelation': ('isRemoveAllowed', 'false')},
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'],
                            TIMEOUT: 60 * 60},
            'CMIMPORT_30': {SUPPORTED_NODE_TYPES: [NODES.RADIONODE],
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                            TOTAL_NODES: 1000, USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            'MO_VALUES': {'EUtranFreqRelation': 1}, 'BATCH_MO_SIZE': 1,
                            SCHEDULED_TIMES_STRINGS: ['04:00:00', '04:35:00', '05:35:00', '08:20:00', '09:10:00',
                                                      '10:35:00', '11:10:00', '13:20:00', '13:55:00', '17:15:00',
                                                      '19:15:00', '20:15:00', '20:30:00', '21:00:00', '21:30:00'],
                            SCHEDULED_DAYS: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY",
                                             "SATURDAY", "SUNDAY"],
                            FILETYPE: 'dynamic', INTERFACE: 'NBIv2',
                            FLOW: 'live_config', ERROR_HANDLING: ['continue-on-error-node', "parallel"],
                            IMPORT_TYPE: UPDATE_LIVE,
                            'MOS_ATTRS': {'EUtranFreqRelation': ['userLabel']},
                            'MOS_DEFAULT': {'EUtranFreqRelation': ('userLabel', 'import_1k')},
                            'MOS_MODIFY': {'EUtranFreqRelation': ('userLabel', 'null')},
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'],
                            TIMEOUT: 60 * 60},
            'CMIMPORT_31': {SUPPORTED_NODE_TYPES: [NODES.RADIONODE], 'TIMES_PER_DAY': 6000,
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                            TOTAL_NODES: 1, USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            'BATCH_MO_SIZE': 2, FILETYPE: 'dynamic', INTERFACE: 'NBIv2', FLOW: 'live_config',
                            SCHEDULED_TIMES_STRINGS: ['00:00:00'], 'NUM_ITERATIONS': 6000,
                            ERROR_HANDLING: ["continue-on-error-node", "parallel"], IMPORT_TYPE: UPDATE_LIVE,
                            'MO_VALUES': {'EUtranCellFDD': 2},
                            'MOS_ATTRS': {'EUtranCellFDD': ['userLabel']},
                            'MOS_DEFAULT': {'EUtranCellFDD': ('userLabel', 'sonJob_1')},
                            'MOS_MODIFY': {'EUtranCellFDD': ('userLabel', 'null')},
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'], TIMEOUT: 60 * 60},
            'CMIMPORT_32': {SUPPORTED_NODE_TYPES: [NODES.RADIONODE], 'TIMES_PER_DAY': 6000,
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                            TOTAL_NODES: 1, USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            'BATCH_MO_SIZE': 2, FILETYPE: 'dynamic', INTERFACE: 'NBIv2', FLOW: 'live_config',
                            SCHEDULED_TIMES_STRINGS: ['00:00:00'], 'NUM_ITERATIONS': 6000,
                            ERROR_HANDLING: ["continue-on-error-node", "parallel"], IMPORT_TYPE: UPDATE_LIVE,
                            'MO_VALUES': {'EUtranCellFDD': 2},
                            'MOS_ATTRS': {'EUtranCellFDD': ['userLabel']},
                            'MOS_DEFAULT': {'EUtranCellFDD': ('userLabel', 'sonJob_2')},
                            'MOS_MODIFY': {'EUtranCellFDD': ('userLabel', 'null')},
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'], TIMEOUT: 60 * 60},
            'CMIMPORT_33': {SUPPORTED_NODE_TYPES: [NODES.RADIONODE], 'TIMES_PER_DAY': 6000,
                            NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                            TOTAL_NODES: 1, USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            'BATCH_MO_SIZE': 2, FILETYPE: 'dynamic', INTERFACE: 'NBIv2', FLOW: 'live_config',
                            SCHEDULED_TIMES_STRINGS: ['00:00:00'], 'NUM_ITERATIONS': 6000,
                            ERROR_HANDLING: ["continue-on-error-node", "parallel"], IMPORT_TYPE: UPDATE_LIVE,
                            'MO_VALUES': {'EUtranCellFDD': 2},
                            'MOS_ATTRS': {'EUtranCellFDD': ['userLabel']},
                            'MOS_DEFAULT': {'EUtranCellFDD': ('userLabel', 'sonJob_3')},
                            'MOS_MODIFY': {'EUtranCellFDD': ('userLabel', 'null')},
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'], TIMEOUT: 60 * 60},
            'CMIMPORT_34': {'MO_VALUES': {'NRFrequency': 24, 'EUtranFrequency': 16,
                                          'ExternalEUtranCell': 1008, 'TermPointToENB': 2048,
                                          'ExternalNRCellCU': 2048, 'NRFreqRelation': 6048,
                                          'EUtranFreqRelation': 4096, 'EUtranCellRelation': 1008, 'NRCellRelation': 34272},
                            'MOS_ATTRS': {'NRFrequency': ['smtcScs', 'arfcnValueNRDl', 'id'],
                                          'EUtranFrequency': ['id', 'arfcnValueEUtranDl'],
                                          'ExternalEUtranCell': ['id'],
                                          'TermPointToENB': ['id'],
                                          'ExternalNRCellCU': ['plmnIdList', 'nRFrequencyRef', 'nRPCI', 'id'],
                                          'NRFreqRelation': ['nRFrequencyRef', 'id'],
                                          'EUtranFreqRelation': ['eUtranFrequencyRef', 'id'],
                                          'EUtranCellRelation': ['adjacentCell', 'id'],
                                          'NRCellRelation': ['nRFreqRelationRef', 'adjacentNRCellRef', 'id']},
                            USER_ROLES: ['CM_REST_Administrator', 'CM_REST_Operator'], ATTEMPT_RECOVERY: False,
                            NODE_FILTER: {NODES.Shared_CNF: {"network_function": ["vCU-CP"]}}, TOTAL_NODES: 1,
                            SUPPORTED_NODE_TYPES: [NODES.Shared_CNF], INTERFACE: 'NBIv2', 'BATCH_MO_SIZE': 4,
                            SCHEDULED_TIMES_STRINGS: ['10:30:00'], FILETYPE: 'dynamic', FLOW: 'live_config',
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'],
                            ERROR_HANDLING: ["continue-on-error-node", 'sequential'], IMPORT_TYPE: CREATE_DELETE_LIVE,
                            TIMEOUT: 60 * 60},
            'CMIMPORT_35': {'MO_VALUES': {'cmp': 1, 'EUtranFreqRelation': 6144,
                                          'ExternalGNBCUCPFunction': 2048,
                                          'NRCellCU': 2048, 'NRFreqRelation': 10240},
                            'MOS_ATTRS': {'cmp': ['renewal-mode'],
                                          'EUtranFreqRelation': ['presenceAntennaPort1'],
                                          'ExternalGNBCUCPFunction': ['isRemoveAllowed'],
                                          'NRCellCU': ['transmitSib2'], 'NRFreqRelation': ['mdtMeasOn']},
                            'MOS_DEFAULT': {'cmp': ('renewal-mode', 'automatic'),
                                            'EUtranFreqRelation': ('presenceAntennaPort1', 'true'),
                                            'ExternalGNBCUCPFunction': ('isRemoveAllowed', 'true'),
                                            'NRCellCU': ('transmitSib2', 'true'),
                                            'NRFreqRelation': ('mdtMeasOn', 'true')},
                            'MOS_MODIFY': {'cmp': ('renewal-mode', 'manual'),
                                           'EUtranFreqRelation': ('presenceAntennaPort1', 'false'),
                                           'ExternalGNBCUCPFunction': ('isRemoveAllowed', 'false'),
                                           'NRCellCU': ('transmitSib2', 'false'),
                                           'NRFreqRelation': ('mdtMeasOn', 'false')},
                            USER_ROLES: ['CM_REST_Administrator', 'CM_REST_Operator'],
                            NODE_FILTER: {NODES.Shared_CNF: {'network_function': ['vCU-CP']}},
                            TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [NODES.Shared_CNF], INTERFACE: 'NBIv2',
                            SCHEDULED_TIMES_STRINGS: ['10:30:00'], SCHEDULED_DAYS: ['MONDAY'],
                            FILETYPE: 'dynamic', FLOW: 'live_config',
                            EXCLUDE_NODES_FROM: ['CMSYNC_01', 'CMSYNC_02', 'CMSYNC_04', 'CMSYNC_06'],
                            ERROR_HANDLING: ["continue-on-error-node"], 'BATCH_MO_SIZE': 4,
                            IMPORT_TYPE: UPDATE_LIVE, TIMEOUT: 60 * 60}
        },
        "cmsync": {
            'CMSYNC_SETUP': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], SCHEDULE_SLEEP: 24 * 24 * 60,
                             "MSCM_RATIO": 0.5, "MSCMCE_RATIO": 0.5, "MAX_MOS_PER_RNC": 500, "VALUES_PER_PROFILE":
                                 {"CMSYNC_01": 0.3294, "CMSYNC_02": 0.3835, "CMSYNC_04": 0.1435, "CMSYNC_06": 0.1436},
                             "MAX_MOS_MSCMCE": 76000},
            'CMSYNC_01': {NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                          "BURST_TYPE": "MCD", 'NOTIFICATION_INFO': CMSYNC_MCD_BURST_MO_TYPE_SETTINGS,
                          "ME_TYPE_NODES_PERCENTAGE": {"ENodeB": 10, "GNodeB": 90},
                          SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                    for minute in range(0, 60, 30)],
                          EXCLUDE_NODES_FROM: ["CMIMPORT_01", "CMIMPORT_02", "CMIMPORT_03", "CMIMPORT_08",
                                               "CMIMPORT_11", "CMIMPORT_12", "CMIMPORT_13", "CMIMPORT_17", "TOP_01",
                                               "CMSYNC_02", "CMSYNC_04", "CMSYNC_06", "CELLMGT_01", "CELLMGT_02"],
                          'CELL_CARDINALITY_NES': [NODES.ERBS, NODES.RADIONODE],
                          'BURST_DURATION': 1800, "NO_UPGIND": True, LTE_CELL_CHECK: True},
            'CMSYNC_35': {TOTAL_NODES: 1, SUPPORTED_NODE_TYPES: [NODES.BSC],
                          SCHEDULED_DAYS: ["SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY",
                                           "SATURDAY"], 'BATCH_MO_SIZE': 100, 'MO_VALUES': {'GeranCell': 8000},
                          SCHEDULED_TIMES_STRINGS: ["01:30:00"]},
            'CMSYNC_44': {},
            'CMSYNC_45': {NUM_NODES: {NODES.Shared_CNF: 12},
                          NODE_FILTER: {NODES.Shared_CNF: {'network_function': ['vCU-CP']}},
                          'UPDATED_AVG_PER_NODE': 3.6,
                          SCHEDULE_SLEEP: 86400, 'NOTIFICATION_INFO': CMSYNC_45_AVC_BURST_MO_TYPE_SETTINGS,
                          'BURST_DURATION': 86400, SCHEDULED_TIMES_STRINGS: ["00:00:00"]}
        },
        "configuration_template": {},
        "doc": {},
        "dynamic_crud": {
            'DYNAMIC_CRUD_01': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 10},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                SCHEDULE_SLEEP: 30 * 60,
                                "REQ_COUNTS": {"REQ_1_2_3": 250, "REQ_4_5_6": 1250,
                                               "REQ_7": 17, "REQ_8": 17, "REQ_9": 17, "REQ_10": 16}},
            'DYNAMIC_CRUD_03': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 140},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                SCHEDULED_TIMES_STRINGS: ["09:30:00", "21:30:00"], "NUMBER_OF_THREADS": 50,
                                "REQ_COUNTS": {"REQ_1_2_3": 1000}, EXCLUDE_NODES_FROM: ["DYNAMIC_CRUD_05"],
                                "NODES_PER_HOST": 10, MAX_NODES: 125},
            'DYNAMIC_CRUD_04': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 10},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                SCHEDULED_TIMES_STRINGS: ["03:30:00", "07:30:00", "11:30:00", "15:30:00", "19:30:00",
                                                          "23:30:00"],
                                "NUMBER_OF_THREADS": 50, "REQ_COUNTS": {"REQ_1_2_3": 10000}},
            'DYNAMIC_CRUD_05': {NUM_USERS: 1, USER_ROLES: ['ADMINISTRATOR'], NUM_NODES: {NODES.RADIONODE: 30},
                                NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]}},
                                "NUMBER_OF_THREADS": 5, SCHEDULED_TIMES_STRINGS: ["02:30:00", "14:30:00"],
                                "REQ_COUNTS": {"PATCH": 100}, EXCLUDE_NODES_FROM: ["DYNAMIC_CRUD_03"],
                                "NODES_PER_HOST": 5, MAX_NODES: 15}
        },
        "ebsl": {},
        "ebsn": {
            "EBSN_05": {NUM_NODES: {NODES.RADIONODE: -1}, NUM_EVENTS: 1.0, 'NUM_COUNTERS': 1.0, "EBS_EVENTS": True,
                        USER_ROLES: ["ADMINISTRATOR", 'Cmedit_Administrator', "PM_Operator"], 'POLL_SCANNERS': True,
                        NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ["GNodeB"]}},
                        'CELL_TRACE_CATEGORY': "CELLTRACE_NRAN_AND_EBSN_STREAM", "EVENT_FILTER": "cellTraceNRan",
                        'DEFINER': "CELLTRACENRAN_SubscriptionAttributes", 'SLEEP_TIME': 240}
        },
        "ebsm": {},
        "em": {
            'EM_01': {SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_669x], TOTAL_NODES: 100, NUM_USERS: 75,
                      'TOTAL_NODES_NON_RACK': 75, 'NUM_USERS_RACK': 100,
                      SCHEDULED_TIMES_STRINGS: ["00:30:00", "06:30:00", "12:30:00", "18:30:00"],
                      "PARALLEL_SESSIONS_LAUNCH": 3,
                      USER_ROLES: ['Element_Manager_Operator', 'ENodeB_Application_Administrator',
                                   'GNodeB_Application_Administrator', 'Network_Explorer_Operator',
                                   'RemoteDesktop_Operator', 'DesktopSession_Administrator']}
        },
        "enmcli": {
            'ENMCLI_02': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], TOTAL_NODES: 97, LTE_CELL_CHECK: True,
                          NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}}, NUM_USERS: 97,
                          USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator'],
                          SCHEDULE_SLEEP: 60 * 15, EXCLUDE_NODES_FROM: ["TOP_01"]},
            'ENMCLI_03': {SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], TOTAL_NODES: 2, NUM_USERS: 100,
                          NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB', 'GNodeB']}},
                          'SCHEDULE_SLEEP': 900, 'enmcli_commands_list': ENMCLI_COMMANDS, LTE_CELL_CHECK: True,
                          USER_ROLES: ['Cmedit_Operator', 'Scripting_Operator', 'FM_Operator',
                                       'Lcm_Administrator', 'NodeSecurity_Operator', 'Autoprovisioning_Operator',
                                       'ADMINISTRATOR', 'SECURITY_ADMIN'], 'total_commands_sec': 1.0,
                          'percentage_cm_bas': 22.5, 'percentage_cm_std': 45, 'percentage_cm_adv': 22.5,
                          'percentage_alarm': 5, 'percentage_secadm': 5},
            'ENMCLI_05': {TOTAL_NODES: 6250, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE], NUM_USERS: 1,
                          USER_ROLES: ['Cmedit_Administrator', 'Network_Explorer_Administrator']},
            'ENMCLI_06': {NUM_USERS: 5, USER_ROLES: ['Cmedit_Administrator'], CHECK_NODE_SYNC: True,
                          NUM_NODES: {NODES.BSC: 50}, 'NUM_COMMANDS': 10, 'THREAD_QUEUE_TIMEOUT': 60 * 60,
                          SCHEDULED_TIMES_STRINGS: ['09:00:00', '10:00:00', '11:00:00', '12:00:00', '13:00:00',
                                                    '14:00:00', '15:00:00', '16:00:00', '17:00:00', '18:00:00'],
                          EXCLUDE_NODES_FROM: ["ENMCLI_07", "CELLMGT_15"]},
            'ENMCLI_07': {NUM_USERS: 2, USER_ROLES: ['Cmedit_Administrator'], NUM_NODES: {NODES.BSC: 1},
                          SCHEDULED_TIMES_STRINGS: ["09:00:00"], 'SLEEP_TIME_BETWEEN_COMMANDS': 60,
                          'DAILY_ITERATION_COUNT_LIMIT': 102, CHECK_NODE_SYNC: True,
                          EXCLUDE_NODES_FROM: ["ENMCLI_06", "CELLMGT_15"]},
            'ENMCLI_09': {NUM_USERS: 1, USER_ROLES: ['Cmedit_Administrator'], NUM_NODES: {NODES.Shared_CNF: -1},
                          NODE_FILTER: {NODES.Shared_CNF: {'network_function': ['vCU-CP']}}, SCHEDULED_TIMES_STRINGS: ["15:00:00"]},
            'ENMCLI_10': {NUM_USERS: 1, NUM_NODES: {NODES.Shared_CNF: -1},
                          NODE_FILTER: {NODES.Shared_CNF: {'network_function': ['vCU-CP']}},
                          USER_ROLES: ["Cmedit_Administrator"], SCHEDULED_TIMES_STRINGS: ["14:45:00"]}
        },
        "esm": {},
        "esm_nbi": {
            'ESM_NBI_01': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'ROP_INTERVAL': 15,
                           SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                     for minute in range(0, 60, 15)]}
        },
        "fm": {
            'FM_0506': {NUM_NODES: {NODES.ERBS: -1, NODES.RADIONODE: -1, NODES.MGW: -1, NODES.SGSN_MME: -1,
                                    NODES.ROUTER6672: -1, NODES.RNC: -1, NODES.RBS: -1, NODES.BSC: -1,
                                    NODES.MSC_DB_BSP: -1,
                                    NODES.MSC_BC_IS: -1,
                                    NODES.MSC_BC_BSP: -1, NODES.SIU02: -1, NODES.TCU02: -1, NODES.MINI_LINK_Indoor: -1,
                                    NODES.ROUTER6675: -1, NODES.MINI_LINK_669x: -1, NODES.CCDM: -1,
                                    NODES.Shared_CNF: -1},
                        USER_ROLES: ["FM_Administrator"], NUM_USERS: 1,
                        'SETUP_STEPS': {"CEASE_ALARM": True, "AUTO_ACK": True, "DELAYED_ACK": True}},
            'FM_01': {
                SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672,
                                       NODES.BSC, NODES.SGSN_MME,
                                       NODES.MSC_DB_BSP, NODES.MSC_BC_BSP, NODES.MSC_BC_IS, NODES.SIU02, NODES.TCU02,
                                       NODES.MINI_LINK_Indoor,
                                       NODES.ROUTER6675, NODES.MINI_LINK_669x, NODES.CCDM, NODES.Shared_CNF],
                EXCLUDE_NODES_FROM: ["FM_02", "FM_03"], 'AML_RATE': 1.0, 'AML_RATIO': 0.5,
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                TOTAL_NODES: 200, 'BSC_BURST_RATE': 0.038, 'MSC_BURST_RATE': 0.038,
                'FM_01_TOTAL_ALARMS': TOTAL_TARGET_ALARMS - (FM_02_TOTAL_ALARMS + FM_03_TOTAL_ALARMS),
                'DURATION': 3660, SCHEDULE_SLEEP: 3600,
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('EXTERNAL ALARM', 'major'),
                    ('CCITT7 SIGNALLING LINK FAILURE', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_02': {
                SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672,
                                       NODES.BSC, NODES.SGSN_MME,
                                       NODES.MSC_DB_BSP, NODES.MSC_BC_BSP, NODES.MSC_BC_IS, NODES.SIU02, NODES.TCU02,
                                       NODES.MINI_LINK_Indoor,
                                       NODES.ROUTER6675, NODES.MINI_LINK_669x, NODES.CCDM, NODES.Shared_CNF],
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                TOTAL_NODES: 300, 'BURST_RATE': 40, 'DURATION': 300, SCHEDULE_SLEEP: 900,
                EXCLUDE_NODES_FROM: ["FM_01", "FM_03"], 'AML_RATE': 2.0, 'AML_RATIO': 0.5,
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('EXTERNAL ALARM', 'major'),
                    ('CCITT7 SIGNALLING LINK FAILURE', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_03': {
                SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672,
                                       NODES.BSC, NODES.SGSN_MME,
                                       NODES.MSC_DB_BSP, NODES.MSC_BC_BSP, NODES.MSC_BC_IS, NODES.SIU02, NODES.TCU02,
                                       NODES.MINI_LINK_Indoor,
                                       NODES.ROUTER6675, NODES.MINI_LINK_669x, NODES.CCDM, NODES.Shared_CNF],
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                TOTAL_NODES: 1000, 'BURST_RATE': 200, 'DURATION': 240, 'AML_RATE': 10.0, 'AML_RATIO': 0.5,
                SCHEDULED_TIMES_STRINGS: ['00:00:00', '02:45:00', '06:00:00', '09:35:00', '12:10:00',
                                          '14:45:00', '18:00:00', '21:00:00'],
                EXCLUDE_NODES_FROM: ["FM_01", "FM_02"],
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('EXTERNAL ALARM', 'major'),
                    ('CCITT7 SIGNALLING LINK FAILURE', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_31': {'SERVICE': 'fmalarmprocessing', 'PARAMETERS': [('alarmOverloadProtectionOn', 'true'),
                                                                     ('alarmOverloadProtectionThreshold', '55200'),
                                                                     ('alarmOverloadProtectionLowerThreshold', '70')]},
            'FM_32': {
                SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672,
                                       NODES.BSC, NODES.SGSN_MME,
                                       NODES.MSC_DB_BSP, NODES.MSC_BC_BSP, NODES.MSC_BC_IS, NODES.SIU02, NODES.TCU02,
                                       NODES.MINI_LINK_Indoor],
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                TOTAL_NODES: 500, 'BURST_RATE': 400, 'DURATION': 300, 'AML_RATE': 0.0, 'AML_RATIO': 0.0,
                EXCLUDE_NODES_FROM: ["FM_01", "FM_02", "FM_03"],
                'ALARM_SIZE_DISTRIBUTION': [10, 100],
                'ALARM_PROBLEM_DISTRIBUTION': [('', 'major'), ('', 'minor')], SCHEDULED_TIMES_STRINGS: ["20:00:00"]}
        },
        "fmx": {
            'FMX_01': {SCHEDULE_SLEEP: 60 * 60, USER_ROLES: ["FMX_Administrator"], 'execute_on_transport': False,
                       FMX_RULEMODULES: NSX_RULEMODULES + CNX_RULEMODULES + GRX_RULEMODULES}
        },
        "ftpes": {},
        "fan": {
            'FAN_01': {},
            'FAN_02': {},
            'FAN_03': {},
            'FAN_04': {},
            'FAN_11': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator"], 'ROP_INTERVAL': 15,
                       'FILES_FETCH_TIME_IN_MINS': 13, 'NUM_OF_BATCHES': 1, 'NUM_OF_CURL_PARALLEL_REQUESTS': 200,
                       'DATA_TYPES': ['PM_STATISTICAL_1MIN', 'PM_STATISTICAL_5MIN', 'PM_STATISTICAL',
                                      'PM_STATISTICAL_30MIN', 'PM_STATISTICAL_1HOUR', 'PM_STATISTICAL_12HOUR',
                                      'PM_STATISTICAL_24HOUR', 'PM_CELLTRACE', 'PM_CELLTRACE_CUCP',
                                      'PM_CELLTRACE_CUUP', 'PM_CELLTRACE_DU', 'PM_UETRACE',
                                      'PM_UETRACE_CUCP', 'PM_UETRACE_CUUP', 'PM_UETRACE_DU',
                                      'PM_EBS', 'PM_EBM', 'PM_CTUM', 'PM_UETR', 'PM_CTR', 'PM_GPEH',
                                      'PM_CELLTRAFFIC', 'PM_EBSM_3GPP', 'PM_EBSM_ENIQ', 'PM_EBSL', 'PM_EBSN_DU',
                                      'PM_EBSN_CUCP', 'PM_EBSN_CUUP', 'PM_BSC_PERFORMANCE_EVENT',
                                      'PM_BSC_PERFORMANCE_CTRL', 'PM_BSC_RTT',
                                      'PM_BSC_PERFORMANCE_EVENT_STATISTICS',
                                      'PM_BSC_PERFORMANCE_EVENT_RAW', 'PM_BSC_PERFORMANCE_EVENT_MONITORS'],
                       SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                 for minute in range(0, 60, 15)], "POD_CPU": "5000m",
                       "POD_MEMORY": "1Gi", "SERVICE_FORWARD_PORT": 'fan-11', "DATA_TYPES_UPDATE_TIME": "00:00"},
            'FAN_12': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator"], 'ROP_INTERVAL': 15,
                       'FILES_FETCH_TIME_IN_MINS': 13, 'NUM_OF_BATCHES': 1, 'NUM_OF_CURL_PARALLEL_REQUESTS': 50,
                       'DATA_TYPES': ['PM_EBSL', 'PM_EBSN_CUCP', 'PM_EBSN_CUUP', 'PM_EBSN_DU',
                                      'PM_STATISTICAL', 'PM_STATISTICAL_12HOUR', 'PM_STATISTICAL_1HOUR',
                                      'PM_STATISTICAL_1MIN', 'PM_STATISTICAL_24HOUR', 'PM_STATISTICAL_30MIN',
                                      'PM_STATISTICAL_5MIN', 'PM_EBSM_3GPP', 'PM_EBSM_ENIQ', 'PM_BSC_BAR',
                                      'PM_BSC_MRR', 'PM_BSC_PERFORMANCE_EVENT_STATISTICS', 'TOPOLOGY_*'],
                       SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                 for minute in range(0, 60, 15)], "POD_CPU": "3000m",
                       "POD_MEMORY": "1Gi", "SERVICE_FORWARD_PORT": 'fan-12', 'DESIRED_TIME': '02:00',
                       "DATA_TYPES_UPDATE_TIME": "00:00"},
            'FAN_13': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator"], 'ROP_INTERVAL': 15,
                       'FILES_FETCH_TIME_IN_MINS': 13, 'NUM_OF_BATCHES': 1, 'NUM_OF_CURL_PARALLEL_REQUESTS': 200,
                       'DATA_TYPES': ['PM_STATISTICAL', 'PM_STATISTICAL_1MIN', 'PM_CELLTRACE',
                                      'PM_UETR', 'PM_GPEH', 'PM_UETRACE', 'PM_CTR',
                                      'PM_CELLTRACE_CUCP', 'PM_CELLTRACE_CUUP', 'PM_CELLTRACE_DU'],
                       SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                 for minute in range(0, 60, 15)], "POD_CPU": "3000m",
                       "POD_MEMORY": "1Gi", "SERVICE_FORWARD_PORT": 'fan-13', "DATA_TYPES_UPDATE_TIME": "00:00"},
            'FAN_14': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator"], 'ROP_INTERVAL': 15,
                       'FILES_FETCH_TIME_IN_MINS': 13, 'NUM_OF_BATCHES': 1, 'NUM_OF_CURL_PARALLEL_REQUESTS': 200,
                       'DATA_TYPES': ['PM_STATISTICAL_1MIN', 'PM_STATISTICAL_5MIN', 'PM_STATISTICAL',
                                      'PM_STATISTICAL_30MIN', 'PM_STATISTICAL_1HOUR', 'PM_STATISTICAL_12HOUR',
                                      'PM_STATISTICAL_24HOUR', 'PM_CELLTRACE', 'PM_CELLTRACE_CUCP',
                                      'PM_CELLTRACE_CUUP', 'PM_CELLTRACE_DU', 'PM_UETRACE', 'PM_UETRACE_CUCP',
                                      'PM_UETRACE_CUUP', 'PM_UETRACE_DU', 'PM_EBS', 'PM_EBM', 'PM_CTUM',
                                      'PM_UETR', 'PM_CTR', 'PM_GPEH', 'PM_CELLTRAFFIC', 'PM_EBSM_3GPP',
                                      'PM_EBSM_ENIQ', 'PM_EBSL', 'PM_EBSN_DU', 'PM_EBSN_CUCP', 'PM_EBSN_CUUP',
                                      'PM_BSC_PERFORMANCE_EVENT', 'PM_BSC_PERFORMANCE_CTRL', 'PM_BSC_RTT',
                                      'PM_BSC_PERFORMANCE_EVENT_STATISTICS', 'PM_BSC_PERFORMANCE_EVENT_RAW',
                                      'PM_BSC_PERFORMANCE_EVENT_MONITORS'],
                       SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                 for minute in range(0, 60, 15)], "POD_CPU": "3000m",
                       "POD_MEMORY": "1Gi", "SERVICE_FORWARD_PORT": 'fan-14', "DATA_TYPES_UPDATE_TIME": "00:00"}
        },
        "fs_quotas": {
            "FS_QUOTAS_01": {USER_ROLES: ["Scripting_Operator", "SECURITY_ADMIN"], "CEPH_QUOTA_LIMIT": 300,
                             "FILE_SIZE": "150M", "USER_NAME": "cephtest_1",
                             SCHEDULED_DAYS: ["THURSDAY"], SCHEDULED_TIMES_STRINGS: ['11:30:00'],
                             "RUN_UNTIL": "12:30:00"}
        },
        "geo_r": {
            'GEO_R_01': {SCHEDULED_TIMES_STRINGS: ["05:00:00", "11:00:00", "17:00:00", "23:00:00"],
                         USER_ROLES: GEO_USER_ROLES, "EXPORT_SIZE": "5", "MAX_FM_HISTORY_SIZE": "5"}
        },
        "ha": {},
        "launcher": {},
        "lcm": {},
        "lkf": {
            'LKF_01': {NUM_USERS: 1, USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"],
                       NUM_NODES: {NODES.RADIONODE: 1280}, 'FILTERED_NODES_PER_HOST': 40,
                       SCHEDULED_TIMES_STRINGS: ["14:00:00"], SCHEDULED_DAYS: ["THURSDAY"],
                       MAX_NODES: 1280, 'NUM_NODES_PER_BATCH': 200,
                       NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ["GNodeB"]}}},
        },
        "logviewer": {},
        "lt_syslog_stream": {
            'LT_SYSLOG_STREAM_01': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], "NUM_OF_LOGS": 100,
                                    SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute)
                                                              for hour in range(00, 24)
                                                              for minute in range(0, 60, 28) if minute in [28, 56]]}
        },
        "ncm_mef_lcm": {},
        "ncm_l3_vpn": {},
        "ncm_mef": {},
        "ncm_vpn_sd": {},
        "neo4j": {
            'NEO4J_01': {"SLEEP_TIME": 28 * 60}
        },
        "netex": {
            'NETEX_05': {NUM_USERS: 5, USER_ROLES: ['Network_Explorer_Administrator', 'Cmedit_Operator'],
                         SCHEDULE_SLEEP: 60 * 60, "SLEEP_TIME_BEFORE_CLEANUP": 60},
            'NETEX_08': {NUM_USERS: 1, NUM_NODES: {NODES.Shared_CNF: -1},
                         NODE_FILTER: {NODES.Shared_CNF: {'network_function': ['vCU-CP']}},
                         USER_ROLES: ['Cmedit_Operator', 'Cmedit_Administrator'],
                         SCHEDULED_TIMES_STRINGS: ["15:00:00"], SCHEDULED_DAYS: ["MONDAY"]},

        },
        "netview": {},
        "network": {},
        "nhc": {
            'NHC_01': {"NHC_SLEEP": 30, NUM_USERS: 1, "START_TIME": "19:55:00", "STOP_TIME": "05:55:00",
                       USER_ROLES: ["Nhc_Operator"],
                       SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.MGW, NODES.RNC, NODES.RBS],
                       TOTAL_NODES: 500}
        },
        "nhm": {
            'NHM_SETUP': {TOTAL_NODES: 4000, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE],
                          'TRANSPORT_SETUP': False,
                          'NUMBER_OF_INSTANCES_REQUIRED': 1320000.0, 'INSTANCES_GENERATED_BY_NPA_01': 8000.0,
                          'MAX_NUMBER_OF_CUSTOM_KPIS': 150,
                          NODE_FILTER: {NODES.RADIONODE: {'managed_element_type': ['ENodeB']}},
                          'REPORTING_OBJECT_02': {'RNC': ['UtranCell'], 'ERBS': ['EUtranCellFDD', 'EUtranCellTDD'],
                                                  'RadioNode': ['EUtranCellFDD', 'EUtranCellTDD']},
                          'REPORTING_OBJECT_01': {'ERBS': 'ENodeBFunction', 'RadioNode': 'ENodeBFunction'},
                          'SUPPORTED_TYPES_CUSTOM_CELL_LEVEL_KPI': ['ERBS', 'RadioNode'],
                          'UNSUPPORTED_TYPES_NODE_LEVEL_KPI': ['RNC'],
                          USER_ROLES: ['NHM_Administrator', 'Cmedit_Administrator'], 'NUM_KPIS_01': 18,
                          'UNSUPPORTED_KPIS': [['Added_E-RAB_Establishment_Success_Rate_per_QCI'],
                                               ['Average_DL_MAC_DRB_Latency_per_QCI'],
                                               ['Average_DL_PDCP_UE_DRB_Throughput_per_QCI'],
                                               ['Average_DL_UE_PDCP_DRB_Latency_per_QCI'],
                                               ['E-RAB_Retainability_Percentage_Lost_per_QCI'],
                                               ['E-RAB_Retainability_Session_Time_Normalized_per_QCI_Loss_Rate'],
                                               ['Initial_E-RAB_Establishment_Success_Rate_per_QCI'],
                                               ['UL_Packet_Loss_Rate_per_QCI'],
                                               ['Added_E-RAB_Establishment_Success_Rate_for_Emergency_Calls'],
                                               ['E-RAB_Retainability_Percentage_Lost_for_Emergency_Calls'],
                                               ['Initial_E-RAB_Establishment_Success_Rate_for_Emergency_Calls'],
                                               ['Average_DRB_Latency_DRX_Active-State_UL_In-Sync'],
                                               ['Average_DRB_Latency_with_DRX_Active-State_UL_Out-of-Sync'],
                                               ['Average_DRB_Latency_with_DRX_Inactive-State_UL_In-Sync'],
                                               ['Average_UL_UE_Throughput_per_LCG'],
                                               ['Handover_Failure'],
                                               ['Downlink_PRB_Utilization'],
                                               ['PDCCH_Utilization'],
                                               ['Uplink_PRB_Utilization']]}
        },
        "nhm_rest_nbi": {},
        "nodecli": {},
        "nodesec": {
            'NODESEC_15': {TOTAL_NODES: 1000, SUPPORTED_NODE_TYPES: [NODES.RADIONODE, NODES.ERBS, NODES.RNC, NODES.RBS,
                                                                     NODES.MGW, NODES.DSC, NODES.EPG, NODES.MTAS,
                                                                     NODES.ROUTER6672, NODES.ROUTER6675,
                                                                     NODES.SGSN_MME],
                           NUM_USERS: 20, SCHEDULED_TIMES_STRINGS: ['08:00:00'], 'RUN_UNTIL': '18:00:00',
                           THREAD_QUEUE_TIMEOUT: 4 * 60 * 60, 'NODE_REQUEST_CREDENTIALS_TIME': 5},
            'NODESEC_16': {NUM_USERS: 1, "NUM_OF_NODES": 1000, USER_ROLES: ['ldaprenewer'],
                           "CAPABILITIES": {"ldap": ["update", "patch"], "cm_editor": ["read"]},
                           SCHEDULED_TIMES_STRINGS: ['05:00:00']},
            "NODESEC_17": {NUM_USERS: 1, USER_ROLES: ["proxycleanupper"],
                           "CAPABILITIES": {"nodesec_proxy": ["read", "update", "delete"]},
                           "INACTIVE_HOURS": 48, SCHEDULED_TIMES_STRINGS: ["22:30:00"], "SCHEDULE_SLEEP_DAYS": 2},
            'NODESEC_18': {NUM_USERS: 1, NUM_NODES: {NODES.SGSN_MME: -1},
                           USER_ROLES: ['sshkeymaker'], "CAPABILITIES": {"sshkey": ["create", "delete"],
                                                                         "cm_editor": ["read"]},
                           SCHEDULED_TIMES_STRINGS: ["03:00:00"], SCHEDULED_DAYS: ["MONDAY"]}

        },
        "npa": {
            'NPA_01': {NUM_USERS: 1, SCHEDULE_SLEEP: 60 * 60 * 24 * 7, 'NUMBER_OF_FLOWS': 5, 'NUMBER_OF_CELLS': 500,
                       USER_ROLES: ['Flowautomation_Operator', 'Cmedit_Operator', 'NHM_Operator', 'NHM_Administrator',
                                    'Nhc_Administrator', 'Shm_Administrator'],
                       'NODE_VERSION_FORMAT': ["20.Q1", "20.Q2", "20.Q3", "20.Q4", "21.Q1", "21.Q2", "21.Q3", "21.Q4"],
                       'CELL_TYPE': {'RadioNode': ['EUtranCellFDD', 'EUtranCellTDD']}, 'KPI_ADJUST': 1}
        },
        "nvs": {},
        "nas_outage": {
        },
        "migration": {},
        "ops": {},
        "parmgt": {
            'PARMGT_01': {NUM_USERS: 14, USER_ROLES: ["Parameter_Management_Administrator", "Cmedit_Administrator"],
                          TOTAL_NODES: 1400, SUPPORTED_NODE_TYPES: [NODES.RADIONODE, NODES.Shared_CNF],
                          NODE_FILTER: {NODES.RADIONODE: {"managed_element_type": ["ENodeB", "GNodeB"]},
                                        NODES.Shared_CNF: {'network_function': ['vCU-CP']}},
                          SCHEDULED_TIMES_STRINGS: ["06:00:00"], "DAILY_SLEEP": 23 * 60 * 60 + 40 * 60,
                          "NUMBER_OF_ITERATIONS": 32, "TIME_IN_MINUTES_BETWEEN_ITERATIONS": 15},
            'PARMGT_03': {NUM_USERS: 1, USER_ROLES: ["Parameter_Management_Administrator"], "NUMBER_OF_MOS": 60000,
                          SCHEDULED_TIMES_STRINGS: ["14:00:00"], SCHEDULED_DAYS: ["FRIDAY"]}
        },
        "plm": {},
        "pkiadmin": {},
        "pm_rest_nbi": {
            "PM_REST_NBI_01": {NUM_NODES: {NODES.RADIONODE: -1}, 'NUM_COUNTERS': 500,
                               USER_ROLES: ["PMIC_NBI_Administrator", 'PMIC_NBI_Operator',
                                            'Cmedit_Administrator', "PM_Operator"],
                               "DEFINER": "STATISTICAL_SubscriptionAttributes",
                               "SUBSCRIPTION_COUNT": 5,
                               SCHEDULE_SLEEP: 60 * 60 * 6,
                               "TECHNOLOGY_DOMAIN": 'EPS', SCHEDULED_TIMES_STRINGS: ["03:45:00"]},
            "PM_REST_NBI_02": {NUM_NODES: {NODES.RADIONODE: -1}, 'NUM_COUNTERS': 500,
                               USER_ROLES: ["PMIC_NBI_Administrator", 'PMIC_NBI_Operator',
                                            'Cmedit_Administrator', "PM_Operator"],
                               "DEFINER": "STATISTICAL_SubscriptionAttributes",
                               "SUBSCRIPTION_COUNT": 100, "WAIT_TIME": 300,
                               "TECHNOLOGY_DOMAIN": 'EPS', SCHEDULED_TIMES_STRINGS: ["00:00:00"]}
        },
        "pm": {
            'PM_49': {NUM_USERS: 1, USER_ROLES: ["Scripting_Operator", "FNT_Pushservice_Administrator",
                                                 "Cmedit_Administrator", "CM_REST_Administrator"],
                      "CM_BULK_GEN_START_TIME": "09:00:00", "PUSH_SERVICE_TERMINATE_VM_IP": "10.232.47.72",
                      "PUSH_SERVICE_TERMINATE_VM_PASSWORD": "shroot12"},
            'PM_101': {},
            'PM_102': {NUM_NODES: {NODES.Shared_CNF: -1}, NODE_FILTER: {NODES.Shared_CNF: {'network_function': ['vCU-CP']}},
                       USER_ROLES:
                           ["PMIC_NBI_Administrator", 'PMIC_NBI_Operator', 'Cmedit_Administrator', "PM_Operator"],
                       "DEFINER": "STATISTICAL_SubscriptionAttributes"},
            'PM_103': {NUM_NODES: {NODES.Shared_CNF: -1}, NODE_FILTER: {NODES.Shared_CNF: {'network_function': ['vCU-UP']}},
                       USER_ROLES:
                           ["PMIC_NBI_Administrator", 'PMIC_NBI_Operator', 'Cmedit_Administrator', "PM_Operator"],
                       "DEFINER": "STATISTICAL_SubscriptionAttributes"},
            'PM_104': {NUM_NODES: {NODES.Shared_CNF: -1}, NODE_FILTER: {NODES.Shared_CNF: {'network_function': ['vDU']}},
                       USER_ROLES:
                           ["PMIC_NBI_Administrator", 'PMIC_NBI_Operator', 'Cmedit_Administrator', "PM_Operator"],
                       "DEFINER": "STATISTICAL_SubscriptionAttributes"}
        },
        "reparenting": {
            "REPARENTING_01": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["09:00:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 3600,
                               MAX_NODES_TO_ALLOCATE: 2},
            "REPARENTING_02": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["09:15:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 6460,
                               MAX_NODES_TO_ALLOCATE: 2},
            "REPARENTING_03": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["10:00:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 3600,
                               MAX_NODES_TO_ALLOCATE: 2},
            "REPARENTING_04": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["10:15:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 3600,
                               MAX_NODES_TO_ALLOCATE: 2},
            "REPARENTING_05": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["10:30:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 3600,
                               MAX_NODES_TO_ALLOCATE: 2},
            "REPARENTING_06": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["10:45:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 3600,
                               MAX_NODES_TO_ALLOCATE: 2},
            "REPARENTING_07": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["11:00:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 3600,
                               MAX_NODES_TO_ALLOCATE: 2, TARGET_BSC_ID: "M47B94"},
            "REPARENTING_08": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["12:00:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 3600,
                               MAX_NODES_TO_ALLOCATE: 2},
            "REPARENTING_09": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["13:00:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 3600,
                               MAX_NODES_TO_ALLOCATE: 2},
            "REPARENTING_10": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["13:15:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 3600,
                               MAX_NODES_TO_ALLOCATE: 2},
            "REPARENTING_11": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["13:30:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 3600,
                               MAX_NODES_TO_ALLOCATE: 2},
            "REPARENTING_12": {USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.BSC: -1}, "MAX_CELLS": 450,
                               SCHEDULED_TIMES_STRINGS: ["13:45:00"], CHECK_NODE_SYNC: True, SCHEDULED_DAYS: ['SUNDAY'],
                               'MO_VALUES': {'GeranCell': 450}, 'BATCH_MO_SIZE': 100, 'TIMEOUT': 5670,
                               MAX_NODES_TO_ALLOCATE: 2}
        },
        "secui": {},
        "sev": {
            'SEV_01': {NUM_USERS: 5, USER_ROLES: ["SEV_Administrator", "SEV_Operator"], NUM_NODES: {NODES.ESC: 5},
                       NODE_FILTER: {NODES.ESC: {"node_version": ["22.Q3"]}}, SCHEDULE_SLEEP: 60 * 15,
                       CHECK_NODE_SYNC: True},
            'SEV_02': {NUM_USERS: 5, USER_ROLES: ["SEV_Administrator", "SEV_Operator"], NUM_NODES: {NODES.ESC: 5},
                       SCHEDULE_SLEEP: 60 * 15}
        },
        "shm": {
            'SHM_36': {'NODES_PER_HOST': 2, NUM_USERS: 1, NUM_NODES: {NODES.BSC: 20}, MAX_NODES: 20,
                       SCHEDULED_TIMES_STRINGS: ["06:00:00"], SCHEDULED_DAYS: ['FRIDAY'],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"], SKIP_SYNC_CHECK: True,
                       USER_ROLES: ["Shm_Administrator", "Ops_Operator", "WinFIOL_Operator",
                                    "Element_Manager_Operator", "FIELD_TECHNICIAN", "Scripting_Operator"] + COM_ROLES,
                       "PKG_PIB_VALUES": {}},
            'SHM_39': {'NODES_PER_HOST': 1, NUM_NODES: {NODES.BSC: 5}, SCHEDULED_DAYS: ["MONDAY"], 'TIMEOUT': 1800,
                       SCHEDULED_TIMES_STRINGS: ["23:00:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["23:30:00"],
                       "PIB_VALUES": {"SMRS_BSC_NoOf_BACKUP_FILES": "2"},
                       SKIP_SYNC_CHECK: True, EXCLUDE_NODES_FROM: ['SHM_06'],
                       NUM_USERS: 1, USER_ROLES: ["Shm_Administrator", "Ops_Operator", "WinFIOL_Operator",
                                                  "FIELD_TECHNICIAN", "Element_Manager_Operator",
                                                  "Scripting_Operator"] + COM_ROLES, MAX_NODES: 5},
        },
        "top": {
            'TOP_01': {TOTAL_NODES: 100, SUPPORTED_NODE_TYPES: [NODES.ERBS, NODES.RADIONODE, NODES.Shared_CNF],
                       NUM_USERS: 100,
                       USER_ROLES: ["Topology_Browser_Administrator"], LTE_CELL_CHECK: True, CHECK_NODE_SYNC: True,
                       NODE_FILTER: {"RadioNode": {"managed_element_type": ["ENodeB", "ENodeB|NodeB", "GNodeB"]},
                                     NODES.Shared_CNF: {'network_function': ['vCU-CP']}},
                       EXCLUDE_NODES_FROM: ["CMSYNC_02", "CMSYNC_04", "CMSYNC_06", "CMSYNC_01", "ENMCLI_02"],
                       'THREAD_QUEUE_TIMEOUT': 60 * 25}
        }
    }
}
