import datetime

from basic_network import (IMP_EXP_KEYS as IMP_EXP, USER_KEYS as USER, NODE_KEYS as NODE, TIME_KEYS as TIME,
                           THREAD_QUEUE_TIMEOUT, SKIP_SYNC_CHECK, ERROR_HANDLING, TIMEOUT, NSX_RULEMODULES,
                           FMX_RULEMODULES, MAX_NODES, MAX_NODES_TO_ALLOCATE, SECUI_01_USER_ROLES, COM_ROLES,
                           CHECK_NODE_SYNC, NeTypesEnum as NODES)
from profile_cmds import ROUTER_6000_AVC_BURST_MO_TYPE_SETTINGS

SCHEDULED_DAYS, SCHEDULE_SLEEP, SCHEDULED_TIMES_STRINGS = TIME
NUM_USERS, USER_ROLES = USER
NUM_NODES, SUPPORTED_NODE_TYPES, TOTAL_NODES, EXCLUDE_NODES_FROM, NODE_FILTER = NODE
INTERFACE, FILETYPE, FLOW, IMPORT_TYPE, CREATE_DELETE_LIVE, CREATE_DELETE_CONFIG, UPDATE_LIVE, UPDATE_CONFIG = IMP_EXP
TOTAL_TARGET_ALARMS = 719625
FM_02_TOTAL_ALARMS = 4 * 5 * 60 * 24 * 8
FM_03_TOTAL_ALARMS = 4 * 60 * 8 * 32

soem_five_k_network = {
    "soem_five_k_network": {
        "amos": {},
        "aid": {},
        "ap": {},
        "apt": {
            'APT_01': {},
        },
        "asr_l": {},
        "asr_n": {},
        "asu": {},
        "bur": {},
        "ca": {},
        'cbrs': {},
        "cellmgt": {},
        "cli_mon": {
            'CLI_MON_03': {SCHEDULE_SLEEP: 60 * 60 * 2}
        },
        "cmevents_nbi": {
            'CMEVENTS_NBI_01': {SCHEDULE_SLEEP: 60, NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'EVENT_LIMIT': 20000},
            'CMEVENTS_NBI_02': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'NUM_SUBSCRIBERS': 2}
        },
        "cmexport": {
            'CMEXPORT_14': {SCHEDULED_TIMES_STRINGS: ["19:00:00"],
                            "ENM_NE_TYPES": [NODES.ROUTER6274, NODES.ROUTER6672, NODES.ROUTER6675, NODES.FRONTHAUL_6020,
                                             NODES.FRONTHAUL_6080,
                                             NODES.MINI_LINK_Indoor, NODES.CISCO_ASR900, NODES.MINILINK_6352,
                                             NODES.MINI_LINK_669x, NODES.JUNIPER_MX],
                            'FILETYPE': 'dynamic', NUM_USERS: 1, USER_ROLES: ['CM_REST_Administrator'],
                            INTERFACE: 'NBI'},
            'CMEXPORT_17': {NUM_USERS: 1, USER_ROLES: ['Cmedit_Operator', 'CM_REST_Administrator'],
                            'FILE_RETENTION_TIME': 30 * 60, SCHEDULE_SLEEP: 15 * 60},
            'CMEXPORT_23': {SCHEDULED_TIMES_STRINGS: ["10:50:00"],
                            TIMEOUT: 120,
                            NUM_USERS: 1, USER_ROLES: ['Cmedit_Operator', 'CM_REST_Administrator'],
                            NUM_NODES: {NODES.MINILINK_6352: -1, NODES.MINI_LINK_669x: -1},
                            "NODE_REGEX": "*ML6691*;*MLTN*;*ML6352*",
                            'FILETYPE': '3GPP',
                            "FILE_IN": "CmExport_23_FilterFile.txt"},
        },
        "cmimport": {
            'CMIMPORT_10': {SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675], TOTAL_NODES: 500,
                            'BATCH_MO_SIZE': 50,
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            SCHEDULED_TIMES_STRINGS: ['02:10:00'],
                            'MO_VALUES': {'SwItem': 4}, 'MOS_ATTRS': {'SwItem': ['userLabel']},
                            FILETYPE: 'dynamic', EXCLUDE_NODES_FROM: ['CMSYNC_11', 'CMSYNC_15'],
                            FLOW: 'live_config', IMPORT_TYPE: UPDATE_LIVE, INTERFACE: 'NBIv2',
                            'MOS_DEFAULT': {'SwItem': ('userLabel', 'default')},
                            'MOS_MODIFY': {'SwItem': ('userLabel', 'modify')},
                            ERROR_HANDLING: 'continue-on-error-node', TIMEOUT: 90 * 60},
            'CMIMPORT_25': {FILETYPE: 'dynamic', 'BATCH_MO_SIZE': 100,
                            USER_ROLES: ['Cmedit_Administrator', 'CM_REST_Administrator'],
                            TOTAL_NODES: 1000, SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_669x],
                            SCHEDULED_TIMES_STRINGS: ['08:50:01'], SCHEDULED_DAYS: ['SUNDAY'],
                            'MO_VALUES': {'L2VlanConnection': 2, 'L2VlanEndPoint': 2, 'SwitchPortConfig': 2,
                                          'PriorityMapping': 2, 'Ethernet': 2},
                            'MOS_ATTRS': {'L2VlanConnection': ['name'], 'L2VlanEndPoint': ['untaggedPort'],
                                          'SwitchPortConfig': ['pvid'], 'PriorityMapping': ['trafficClass'],
                                          'Ethernet': ['defaultNetworkPriority']},
                            'MOS_DEFAULT': {'L2VlanConnection': ('name', 'Default VLAN'),
                                            'L2VlanEndPoint': ('untaggedPort', 'false'),
                                            'SwitchPortConfig': ('pvid', 0), 'PriorityMapping': ('trafficClass', 0),
                                            'Ethernet': ('defaultNetworkPriority', 0)},
                            'MOS_MODIFY': {'L2VlanConnection': ('name', 'UpdatedTestVlan1'),
                                           'L2VlanEndPoint': ('untaggedPort', 'true'),
                                           'SwitchPortConfig': ('pvid', 100), 'PriorityMapping': ('trafficClass', 7),
                                           'Ethernet': ('defaultNetworkPriority', 7)},
                            FLOW: 'live_config', IMPORT_TYPE: UPDATE_LIVE, TIMEOUT: 90 * 60}
        },
        "cmsync": {
            'CMSYNC_11': {},
            'CMSYNC_15': {TOTAL_NODES: 500, SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675],
                          SCHEDULE_SLEEP: 1800,
                          'NOTIFICATION_INFO': ROUTER_6000_AVC_BURST_MO_TYPE_SETTINGS, 'ROUTER_SUPPORT': 5000,
                          EXCLUDE_NODES_FROM: ['CMIMPORT_10'], 'BURST_DURATION': 1800},
            'CMSYNC_26': {NUM_NODES: {NODES.MINILINK_6352: 1}, SCHEDULED_TIMES_STRINGS: ["01:30:00"]},
            'CMSYNC_28': {NUM_NODES: {NODES.ROUTER6274: 1}, SCHEDULED_TIMES_STRINGS: ["05:00:00"]},
            'CMSYNC_33': {TOTAL_NODES: 1000, SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675],
                          SCHEDULED_DAYS: ["THURSDAY"],
                          SCHEDULED_TIMES_STRINGS: ["17:30:00"]},
            'CMSYNC_34': {TOTAL_NODES: 1000, SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_Indoor, NODES.MINI_LINK_669x],
                          SCHEDULED_DAYS: ["THURSDAY"],
                          SCHEDULED_TIMES_STRINGS: ["01:30:00"]},
            'CMSYNC_37': {NUM_NODES: {NODES.FRONTHAUL_6020: 1}, SCHEDULED_TIMES_STRINGS: ["22:45:00"]},
            'CMSYNC_38': {NUM_NODES: {NODES.JUNIPER_MX: 1}, SCHEDULED_TIMES_STRINGS: ["22:15:00"]}
        },
        "configuration_template": {},
        "doc": {},
        "dynamic_crud": {},
        "ebsl": {},
        "ebsn": {},
        "ebsm": {},
        "em": {
            'EM_01': {SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_669x], TOTAL_NODES: 100, NUM_USERS: 50,
                      'TOTAL_NODES_NON_RACK': 50, 'NUM_USERS_RACK': 100,
                      SCHEDULED_TIMES_STRINGS: ["00:30:00", "06:30:00", "12:30:00", "18:30:00"],
                      "PARALLEL_SESSIONS_LAUNCH": 2,
                      USER_ROLES: ['Element_Manager_Operator', 'ENodeB_Application_Administrator',
                                   'GNodeB_Application_Administrator', 'Network_Explorer_Operator',
                                   'RemoteDesktop_Operator', 'DesktopSession_Administrator']}
        },
        "enmcli": {},
        "esm": {},
        "esm_nbi": {},
        "fm": {
            'FM_0506': {NUM_NODES: {NODES.MGW: -1, NODES.ROUTER6672: -1, NODES.RNC: -1, NODES.RBS: -1, NODES.SIU02: -1,
                                    NODES.TCU02: -1, NODES.SGSN_MME: -1, NODES.MINI_LINK_Indoor: -1,
                                    NODES.ROUTER6675: -1, NODES.MINI_LINK_669x: -1, NODES.CCDM: -1},
                        USER_ROLES: ["FM_Administrator"], NUM_USERS: 1,
                        'SETUP_STEPS': {"CEASE_ALARM": True, "AUTO_ACK": True, "DELAYED_ACK": True}},
            'FM_01': {
                SUPPORTED_NODE_TYPES: [NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672, NODES.SIU02, NODES.TCU02,
                                       NODES.SGSN_MME, NODES.MINI_LINK_Indoor,
                                       NODES.ROUTER6675, NODES.MINI_LINK_669x, NODES.CCDM],
                TOTAL_NODES: 20, 'BSC_BURST_RATE': 0.038, 'MSC_BURST_RATE': 0.038,
                'FM_01_TOTAL_ALARMS': TOTAL_TARGET_ALARMS - (FM_02_TOTAL_ALARMS + FM_03_TOTAL_ALARMS),
                'DURATION': 3660, 'SCHEDULE_SLEEP': 3600, EXCLUDE_NODES_FROM: ["FM_02", "FM_03"], 'AML_RATE': 0.05,
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'], 'AML_RATIO': 0.1,
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_02': {
                SUPPORTED_NODE_TYPES: [NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672, NODES.SIU02, NODES.TCU02,
                                       NODES.SGSN_MME, NODES.MINI_LINK_Indoor,
                                       NODES.ROUTER6675, NODES.MINI_LINK_669x, NODES.CCDM],
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                TOTAL_NODES: 225, 'BURST_RATE': 8, 'DURATION': 300, SCHEDULE_SLEEP: 900,
                EXCLUDE_NODES_FROM: ["FM_01", "FM_03"], 'AML_RATE': 0.5, 'AML_RATIO': 0.1,
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_03': {
                SUPPORTED_NODE_TYPES: [NODES.MGW, NODES.RNC, NODES.RBS, NODES.ROUTER6672, NODES.SIU02, NODES.TCU02,
                                       NODES.SGSN_MME, NODES.MINI_LINK_Indoor,
                                       NODES.ROUTER6675, NODES.MINI_LINK_669x, NODES.CCDM],
                TOTAL_NODES: 750, 'BURST_RATE': 32, 'DURATION': 240, 'AML_RATE': 2.0, 'AML_RATIO': 0.1,
                SCHEDULED_TIMES_STRINGS: ['00:00:00', '02:45:00', '06:00:00', '09:35:00', '12:10:00',
                                          '14:45:00', '18:00:00', '21:00:00'],
                EXCLUDE_NODES_FROM: ["FM_01", "FM_02"],
                NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'PLATFORM_TYPES': ['Cpp', 'Bsc', 'Msc'],
                'ALARM_SIZE_DISTRIBUTION': [1000, 1000, 1000, 1000, 2000, 2000, 2000, 2000, 3000, 4000],
                'ALARM_PROBLEM_DISTRIBUTION': [
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('Nss Synchronization System Clock Status Change', 'indeterminate'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'),
                    ('TU Synch Reference Loss of Signal', 'major'), ('Link Failure', 'critical'),
                    ('Link Failure', 'critical'), ('Link Failure', 'critical'), ('', 'warning'),
                    ('', 'warning')]},
            'FM_08': {TOTAL_NODES: 60,
                      SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675, NODES.MINI_LINK_669x,
                                             NODES.MINILINK_6352,
                                             NODES.MINI_LINK_Indoor, NODES.CCDM],
                      NUM_USERS: 3, 'NUM_USERS_1': 2, 'NUM_USERS_2': 1, USER_ROLES: ["FM_Operator"],
                      'ALARM_MONITOR_SLEEP': 5 * 60, SCHEDULE_SLEEP: 60 * 15},
            'FM_09': {TOTAL_NODES: 60,
                      SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675, NODES.MINI_LINK_669x,
                                             NODES.MINILINK_6352,
                                             NODES.MINI_LINK_Indoor, NODES.CCDM],
                      NUM_USERS: 1, USER_ROLES: ["FM_Operator"], 'ALARM_MONITOR_SLEEP': 60, SCHEDULE_SLEEP: 60 * 15},
            'FM_10': {NUM_NODES: {NODES.ROUTER6672: -1, NODES.ROUTER6675: -1, NODES.MINI_LINK_669x: -1,
                                  NODES.MINI_LINK_Indoor: -1},
                      NUM_USERS: 1, USER_ROLES: ["FM_Administrator"],
                      SCHEDULED_DAYS: ["THURSDAY"], SCHEDULED_TIMES_STRINGS: ["10:00:00"]},
            'FM_12': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], 'TIMEOUT_SUBSCRIPTION': 60 * 24,
                      'NUMBER_NBI_SUBSCRIPTIONS': 14, 'TIMEOUT': 2, 'NBI_filters': [],
                      'CORBA_ENABLED': False, 'BNSI': False, SCHEDULED_TIMES_STRINGS: ["07:00:00"]},
            'FM_14': {TOTAL_NODES: 1,
                      SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675, NODES.MINI_LINK_Indoor,
                                             NODES.CCDM],
                      NUM_USERS: 1,
                      USER_ROLES: ["FM_Administrator"], SCHEDULED_TIMES_STRINGS: ["16:00:00"],
                      "TIME_SPAN": 90},
            'FM_15': {TOTAL_NODES: 500, NUM_USERS: 1,
                      SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_Indoor, NODES.MINI_LINK_669x, NODES.ROUTER6672,
                                             NODES.ROUTER6675, NODES.CCDM],
                      USER_ROLES: ["FM_Administrator"], "TIME_SPAN": 90,
                      SCHEDULED_DAYS: ['WEDNESDAY'], SCHEDULED_TIMES_STRINGS: ["16:00:00"]},
            'FM_17': {NUM_USERS: 1, NUM_NODES: {}, USER_ROLES: ["FM_Administrator"],
                      SCHEDULED_TIMES_STRINGS: ["19:00:00"], "TIME_SPAN": 1},
            'FM_21': {NUM_USERS: 1, SCHEDULED_TIMES_STRINGS: ["05:20:00"],
                      USER_ROLES: ["FM_Administrator", "Cmedit_Administrator"]}
        },
        "fmx": {
            'FMX_01': {SCHEDULE_SLEEP: 60 * 60, USER_ROLES: ["FMX_Administrator"], 'execute_on_transport': True,
                       FMX_RULEMODULES: NSX_RULEMODULES}
        },
        "ftpes": {},
        "fan": {},
        "fs_quotas": {},
        "geo_r": {},
        "ha": {},
        "launcher": {},
        "lcm": {},
        "lkf": {},
        "logviewer": {
            'LOGVIEWER_01': {SCHEDULE_SLEEP: 1800, NUM_USERS: 1, USER_ROLES: ["OPERATOR"], 'SEARCH_TERM': "all errors"}
        },
        "lt_syslog_stream": {},
        "migration": {},
        "ncm_mef_lcm": {
            'NCM_MEF_LCM_01': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"],
                               SCHEDULED_DAYS: ["TUESDAY"], SCHEDULED_TIMES_STRINGS: ["01:00:00"],
                               "RUN_RESTORE": True, "RESTORE_FILE_NAME": "/ericsson/enm/dumps/ncm_backup.tar.gz",
                               "LIST_OF_LCM_SERVICES": [],
                               "NUMBER_OF_RUNS": 5, "MAX_SERVICES": 20, "SERVICE_PREFIX": "service_LCM_",
                               "SLEEP_TIME_AFTER_ACT": 60 * 60, "SLEEP_TIME_AFTER_DEACT": 60 * 90}
        },
        "ncm_l3_vpn": {
            'NCM_L3_VPN_01': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"],
                              SCHEDULED_DAYS: ["THURSDAY"], SCHEDULED_TIMES_STRINGS: ["03:00:00"],
                              "RUN_RESTORE": True, "RESTORE_FILE_NAME": "/ericsson/enm/dumps/ncm_backup.tar.gz",
                              "SERVICE_TYPE": "L3_VPN", "LIST_OF_LCM_SERVICES": [],
                              "NUMBER_OF_RUNS": 10, "MAX_SERVICES": 25, "SERVICE_PREFIX": "service_LCM_",
                              "SLEEP_TIME_AFTER_ACT": 60 * 30, "SLEEP_TIME_AFTER_DEACT": 60 * 90}
        },
        "ncm_mef": {
            'NCM_MEF_01': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], SCHEDULED_TIMES_STRINGS: ["19:35:00"],
                           SCHEDULED_DAYS: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY"]},
            'NCM_MEF_02': {NUM_NODES: {NODES.MINI_LINK_669x: -1}, NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"],
                           SCHEDULED_DAYS: ["MONDAY"], SCHEDULED_TIMES_STRINGS: ["09:00:00"],
                           "NODES_PER_BATCH": 500, "BATCH_SLEEP": 1800},
            'NCM_MEF_03': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"]}
        },
        "ncm_vpn_sd": {
            'NCM_VPN_SD_01': {NUM_USERS: 1, USER_ROLES: ["ADMINISTRATOR"], NUM_NODES: {NODES.MINI_LINK_669x: 1000},
                              SCHEDULED_DAYS: ["WEDNESDAY"], SCHEDULED_TIMES_STRINGS: ["11:00:00"]}
        },
        "neo4j": {},
        "netex": {},
        "netview": {
            'NETVIEW_SETUP': {NUM_USERS: 1, USER_ROLES: ["Cmedit_Administrator"], TOTAL_NODES: 250,
                              SUPPORTED_NODE_TYPES: [NODES.RADIONODE, NODES.ERBS, NODES.BSC, NODES.ROUTER6672,
                                                     NODES.ROUTER6675, NODES.MINILINK_6352,
                                                     NODES.MINI_LINK_669x, NODES.MINI_LINK_Indoor]},
            'NETVIEW_01': {NUM_USERS: 1, USER_ROLES: ["NetworkViewer_Administrator"], "TIME_INTERVAL": 60 * 15},
            'NETVIEW_02': {NUM_USERS: 1, USER_ROLES: ["NetworkViewer_Administrator", "Cmedit_Administrator",
                                                      "Network_Explorer_Administrator"],
                           SCHEDULED_TIMES_STRINGS: ['12:00:00'], 'NUMBER_OF_NODES': 100}
        },
        "network": {},
        "nhc": {},
        "nhm": {
            'NHM_SETUP': {TOTAL_NODES: 1200, SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675],
                          'TRANSPORT_SETUP': True,
                          'NUMBER_OF_INSTANCES_REQUIRED': 300000.0, 'INSTANCES_GENERATED_BY_NPA_01': 8000.0,
                          'MAX_NUMBER_OF_CUSTOM_KPIS': 70,
                          'REPORTING_OBJECT': ['global', 'dot1q-history', 'port-history', 'link-group-history'],
                          'SUPPORTED_TYPES_CUSTOM_CELL_LEVEL_KPI': ['Router6675', 'Router6672'],
                          'UNSUPPORTED_TYPES_NODE_LEVEL_KPI': ['RNC'], 'NUM_KPIS_01': 8,
                          USER_ROLES: ['NHM_Administrator', 'Cmedit_Administrator'],
                          'UNSUPPORTED_KPIS': [['Added_E-RAB_Establishment_Success_Rate_per_QCI'],
                                               ['Average_DL_MAC_DRB_Latency_per_QCI'],
                                               ['Average_DL_PDCP_UE_DRB_Throughput_per_QCI'],
                                               ['Average_DL_UE_PDCP_DRB_Latency_per_QCI'],
                                               ['E-RAB_Retainability_Percentage_Lost_per_QCI'],
                                               ['E-RAB_Retainability_Session_Time_Normalized_per_QCI_Loss_Rate'],
                                               ['Initial_E-RAB_Establishment_Success_Rate_per_QCI'],
                                               ['UL_Packet_Loss_Rate_per_QCI'],
                                               ['Added_E-RAB_Establishment_Success_Rate_for_Emergency_Calls'],
                                               ['E-RAB_Retainability_Percentage_Lost_for_Emergency_Calls'],
                                               ['Initial_E-RAB_Establishment_Success_Rate_for_Emergency_Calls'],
                                               ['Average_DRB_Latency_DRX_Active-State_UL_In-Sync'],
                                               ['Average_DRB_Latency_with_DRX_Active-State_UL_Out-of-Sync'],
                                               ['Average_DRB_Latency_with_DRX_Inactive-State_UL_In-Sync'],
                                               ['Average_UL_UE_Throughput_per_LCG'],
                                               ['Handover_Failure'],
                                               ['Downlink_PRB_Utilization'],
                                               ['PDCCH_Utilization'],
                                               ['Uplink_PRB_Utilization']]},
        },
        "nhm_rest_nbi": {},
        "nodecli": {
            'NODECLI_01': {NUM_USERS: 10, USER_ROLES: ['NodeCLI_Administrator', 'OPERATOR'], 'SESSION_MULTIPLIER': 10,
                           SCHEDULE_SLEEP: 60 * 15, TOTAL_NODES: 5,
                           SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_669x, NODES.ROUTER6672, NODES.ROUTER6675]}
        },
        "nodesec": {
            'NODESEC_08': {NUM_NODES: {NODES.RADIONODE: -1, NODES.EPG: 5, NODES.ROUTER6672: 50, NODES.SGSN_MME: 20},
                           TOTAL_NODES: 900, NUM_USERS: 10, 'NUM_NODES_MAX_PER_USER': 90,
                           'SNMP_VERSION': 'SNMP_V3', 'NUM_BATCHES': 90},
            'NODESEC_15': {TOTAL_NODES: 1000,
                           SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675], NUM_USERS: 2,
                           SCHEDULED_TIMES_STRINGS: ['08:00:00'], 'RUN_UNTIL': '18:00:00',
                           THREAD_QUEUE_TIMEOUT: 60 * 60, 'NODE_REQUEST_CREDENTIALS_TIME': 3600},
            'NODESEC_18': {NUM_USERS: 1, NUM_NODES: {NODES.SGSN_MME: -1},
                           USER_ROLES: ['sshkeymaker'], "CAPABILITIES": {"sshkey": ["create", "delete"],
                                                                         "cm_editor": ["read"]},
                           SCHEDULED_TIMES_STRINGS: ["03:00:00"], SCHEDULED_DAYS: ["MONDAY"]}
        },
        "npa": {},
        "nvs": {},
        "nas_outage": {},
        "ops": {},
        "parmgt": {
            'PARMGT_04': {NUM_USERS: 5, USER_ROLES: ["Parameter_Management_Administrator"],
                          TOTAL_NODES: 5, SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675],
                          SCHEDULED_TIMES_STRINGS: ["03:00:00", "12:00:00", "18:00:00"]}
        },
        "plm": {
            'PLM_01': {NUM_USERS: 1, USER_ROLES: ["LinkManagement_Administrator", "LinkManagement_Operator",
                                                  "Cmedit_Administrator"], SCHEDULE_SLEEP: 60 * 60,
                       "NODE_TYPES": [NODES.RADIONODE, NODES.SGSN_MME, NODES.MINILINK_6352, NODES.ROUTER6672, NODES.ROUTER6675,
                                      NODES.MINI_LINK_669x],
                       'MAX_LINKS': 20000},
            'PLM_02': {NUM_USERS: 1, USER_ROLES: ["LinkManagement_Administrator", "LinkManagement_Operator",
                                                  "Cmedit_Administrator"], TOTAL_NODES: 20, SCHEDULE_SLEEP: 60 * 60,
                       SUPPORTED_NODE_TYPES: [NODES.MINI_LINK_669x]}
        },
        "pkiadmin": {},
        "pm_rest_nbi": {},
        "pm": {
            'PM_06': {NUM_NODES: {}, NUM_USERS: 6, USER_ROLES: ["PM_Operator"], SCHEDULE_SLEEP: 24 * 60 * 60,
                      'CELLTRACE_SUPPORTED_NODE_TYPES': [],
                      'STATS_UNSUPPORTED_NODE_TYPES': [NODES.TCU02, NODES.SIU02, NODES.EPG, NODES.VEPG, NODES.ESC,
                                                       NODES.ERS_SUPPORTNODE],
                      'NODES_PER_SUBSCRIPTION': 2, 'NUM_COUNTERS': 3, 'NUM_EVENTS': 3,
                      'MAX_NODES_TO_ADD': 5, 'ADD_NODES_TO_SUBSCRIPTION': 'WORKER-4',
                      'PERCENT_USERS': {'baseline_polling': 17, 'burst_polling': 17, 'create_delete_sub': 17,
                                        'change_counters': 17, 'activate_deactivate': 17, 'add_delete_nodes': 17}},
            'PM_15': {'POLLING_AND_MASTER_RETENTION': ("scannerPollingIntervalMinutes", 15),
                      SCHEDULE_SLEEP: 60 * 60 * 24},
            'PM_17': {'PM_NBI_RETENTION_PARAMETERS': {
                'STATS_RETENTION': ("pmicStatisticalFileRetentionPeriodInMinutes", 4320),
                'CELLTRACE_RETENTION': ("pmicCelltraceFileRetentionPeriodInMinutes", 180),
                'UE_TRACE_RETENTION': ("pmicUeTraceFileRetentionPeriodInMinutes", 360),
                'CTUM_RETENTION': ("pmicCtumFileRetentionPeriodInMinutes", 360),
                'EBM_RETENTION': ("pmicEbmFileRetentionPeriodInMinutes", 180),
                'CELL_TRAFFIC_RETENTION': ("pmicCellTrafficFileRetentionPeriodInMinutes", 180),
                'UETR_RETENTION': ("pmicUetrFileRetentionPeriodInMinutes", 180),
                'GPEH_RETENTION': ("pmicGpehFileRetentionPeriodInMinutes", 180)}, SCHEDULE_SLEEP: 60 * 60 * 24},
            'PM_26': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator", "Scripting_Operator", "ADMINISTRATOR"],
                      'ROP_INTERVAL': 15, 'SFTP_FETCH_TIME_IN_MINS': 13, 'N_SFTP_THREADS': 10,
                      SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                for minute in range(0, 60, 15)],
                      'DATA_TYPES': ['PM_STATISTICAL', 'PM_STATISTICAL_1MIN', 'PM_STATISTICAL_5MIN',
                                     'PM_STATISTICAL_30MIN', 'PM_STATISTICAL_1HOUR', 'PM_STATISTICAL_12HOUR',
                                     'PM_STATISTICAL_24HOUR', 'TOPOLOGY_*'], "DATA_TYPES_UPDATE_TIME": "00:00"},
            'PM_28': {},
            'PM_32': {NUM_NODES: {NODES.ROUTER6672: -1}, 'NUM_COUNTERS': 1.0,
                      USER_ROLES: ["Cmedit_Administrator", "PM_Operator", "Network_Explorer_Administrator"],
                      'CBS': True, 'MO_CLASS_COUNTERS_INCLUDED': ['global', 'context'],
                      'MO_CLASS_SUB_COUNTERS_INCLUDED': {"global": ["average_user_mem", "cpu1min", "cpu5min",
                                                                    "cpu5sec", "epochtime", "free_user_mem",
                                                                    "load15min", "load1min", "load5min",
                                                                    "peak_user_mem", "peakcpu5min", "sysuptime",
                                                                    "total_user_mem"],
                                                         "context": ["epochtime", "sysuptime"]},
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_44': {NUM_USERS: 1, USER_ROLES: ["PM_NBI_Operator"], 'DATA_TYPES': ['PM_STATISTICAL', 'PM_STATISTICAL_1MIN'],
                      "CHECK_EXPORT_TIME": "02:00:00", "NODE_TYPES": [NODES.RADIONODE, NODES.MGW, NODES.SGSN_MME,
                                                                      NODES.MTAS, NODES.DSC, NODES.ROUTER6675],
                      SCHEDULED_TIMES_STRINGS: ["{0}:{1}:00".format(hour, minute) for hour in range(00, 24)
                                                for minute in range(0, 60, 3)], "INITIAL_FILE_CREATION_TIME": 3},
            'PM_54': {NUM_NODES: {NODES.MINI_LINK_Indoor: -1}, 'NUM_EVENTS': 1.0,
                      USER_ROLES: ["PM_Operator", "Cmedit_Administrator", "Network_Explorer_Administrator"],
                      'MO_CLASS_COUNTERS_INCLUDED': ['AdaptiveCodingAndModulation_ACM_15min',
                                                     'ERP_RT', 'EthernetBandwidth',
                                                     'EthernetDelay', 'EthernetTrafficPerformance',
                                                     'IGMP-MLD-Snooping_RT', 'IP_RT', 'PDH_15min',
                                                     'PTP_RT', 'RADIUS_RT', 'RadioLinkPower_RT',
                                                     'SDH_MS_MSPNE_15min', 'SDH_VC12FE_15min',
                                                     'SDH_VC12NE_15min', 'SDH_VC4NE_15min',
                                                     'ServiceOAM', 'TACACS+_RT', 'TCP_RT', 'UDP_RT'], 'CBS': True,
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_55': {NUM_NODES: {NODES.MINILINK_6352: -1}, 'NUM_EVENTS': 1.0, USER_ROLES: ["PM_Operator",
                                                                                            "Cmedit_Administrator",
                                                                                            "Network_Explorer_Administrator"],
                      'MO_CLASS_COUNTERS_INCLUDED': ['BandwidthUtilization', 'DelayMeasurements'], 'CBS': True,
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_66': {NUM_NODES: {NODES.ESC: -1}, USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator",
                                                               "Cmedit_Administrator"],
                      'CBS': True, 'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_67': {NUM_NODES: {NODES.CISCO_ASR900: -1},
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator", "Cmedit_Administrator"],
                      'CBS': True, 'ENM_NE_TYPES': [NODES.CISCO_ASR900, "CISCO-ASR9000"], 'NUM_COUNTERS': 150,
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_68': {USER_ROLES: ["PM_Operator"],
                      'SYS_DEF_SUB_PATTERN': "FRONTHAUL-6080 Primary15min"},
            'PM_69': {NUM_NODES: {NODES.ROUTER6274: -1}, 'CBS': True, 'ENM_NE_TYPES': [NODES.ROUTER6274],
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator"],
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_71': {NUM_NODES: {NODES.MINI_LINK_Indoor: -1},
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator", "Cmedit_Administrator"],
                      'CBS': True, 'ROP_STR': 'ONE_DAY', 'NUM_COUNTERS': 1.0, 'ENM_NE_TYPES': ["MINI-LINK-Indoor"],
                      'MO_CLASS_COUNTERS_INCLUDED': ['AdaptiveCodingAndModulation_ACM_24h', 'ERP_RT',
                                                     'EthernetBandwidth', 'EthernetDelay', 'EthernetTrafficPerformance',
                                                     'IGMP-MLD-Snooping_RT', 'IP_RT', 'PDH_24h', 'PTP_RT', 'RADIUS_RT',
                                                     'RadioLinkPower_RT', 'SDH_MS_MSPNE_24h', 'SDH_VC12FE_24h',
                                                     'SDH_VC12NE_24h', 'ServiceOAM', 'TACACS+_RT', 'TCP_RT', 'UDP_RT'],
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_72': {NUM_NODES: {NODES.MINILINK_6352: -1},
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator",
                                   "Cmedit_Administrator"],
                      'CBS': True, 'ROP_STR': 'ONE_DAY', 'MO_CLASS_COUNTERS_INCLUDED': ['RMON'],
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_73': {USER_ROLES: ["PM_Operator"],
                      'SYS_DEF_SUB_PATTERN': "FRONTHAUL-6080 Primary24h"},
            'PM_74': {NUM_NODES: {NODES.ROUTER6672: -1}, 'CBS': True, 'ROP_STR': 'ONE_DAY',
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator", "Cmedit_Administrator"],
                      'ENM_NE_TYPES': [NODES.ROUTER6672], 'DEFINER': "STATISTICAL_SubscriptionAttributes",
                      'MO_CLASS_COUNTERS_INCLUDED': ['global', 'context', 'port-history', 'ces-pw-history'],
                      'MO_CLASS_SUB_COUNTERS_INCLUDED': {"global": ["average_user_mem", "peak_user_mem",
                                                                    "total_user_mem"],
                                                         "context": ["epochtime", "sysuptime"],
                                                         "port-history": ["epochtime", "sysuptime"],
                                                         "ces-pw-history": ["epochtime"]}},
            'PM_75': {NUM_NODES: {NODES.ROUTER6274: -1}, 'CBS': True, 'ROP_STR': 'ONE_DAY',
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator", "Cmedit_Administrator"],
                      'ENM_NE_TYPES': ['Router6274'], 'MO_CLASS_COUNTERS_EXCLUDED': ['twamp'],
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_76': {NUM_NODES: {NODES.CISCO_ASR900: -1},
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator"],
                      'CBS': True, 'ROP_STR': 'ONE_DAY',
                      'ENM_NE_TYPES': [NODES.CISCO_ASR900, "CISCO-ASR9000"], 'NUM_COUNTERS': 150,
                      'MO_CLASS_COUNTERS_INCLUDED': ['BGP4-MIB_bgpPeerTable_Group',
                                                     'CISCO-BGP-POLICY-ACCOUNTING-MIB_cbpAcctTable_Group',
                                                     'CISCO-BGP4-MIB_cbgpPeer2AddrFamilyPrefixTable_Group',
                                                     'CISCO-BGP4-MIB_cbgpPeer2Table_Group',
                                                     'CISCO-BGP4-MIB_cbgpPeerAddrFamilyPrefixTable_Group',
                                                     'CISCO-BGP4-MIB_cbgpPeerTable_Group',
                                                     'CISCO-CEF-MIB_cefAdjTable_Group',
                                                     'CISCO-CEF-MIB_cefCCTypeTable_Group',
                                                     'CISCO-CEF-MIB_cefPeerTable_Group',
                                                     'CISCO-CEF-MIB_cefPrefixTable_Group',
                                                     'CISCO-CEF-MIB_cefResourceTable_Group',
                                                     'CISCO-CEF-MIB_cefStatsPrefixLenTable_Group',
                                                     'CISCO-CEF-MIB_cefSwitchingStatsTable_Group',
                                                     'CISCO-CLASS-BASED-QOS-MIB_cbQosC3plAccountStatsTable_Group',
                                                     'CISCO-CLASS-BASED-QOS-MIB_cbQosCMStatsTable_Group',
                                                     'CISCO-CLASS-BASED-QOS-MIB_cbQosEBStatsTable_Group',
                                                     'CISCO-CLASS-BASED-QOS-MIB_cbQosIPHCStatsTable_Group',
                                                     'CISCO-CLASS-BASED-QOS-MIB_cbQosMatchStmtStatsTable_Group'],
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_82': {NUM_NODES: {NODES.JUNIPER_MX: -1}, USER_ROLES: ["PM_Operator", 'Cmedit_Administrator', "Network_Explorer_Administrator"],
                      'CBS': True, 'NUM_COUNTERS': 1.0,
                      'MO_CLASS_COUNTERS_INCLUDED': ['IF-MIB_ifTable_Group', 'IP-MIB_ipIfStatsTable_Group',
                                                     'IP-MIB_ipSystemStatsTable_Group',
                                                     'ISIS-MIB_isisCircuitCounterTable_Group',
                                                     'ISIS-MIB_isisPacketCounterTable_Group',
                                                     'ISIS-MIB_isisSystemCounterTable_Group',
                                                     'JUNIPER-FABRIC-MIB_jnxFabricSourceStatisticsTable_Group',
                                                     'JUNIPER-IF-MIB_ifJnxPolTable_Group',
                                                     'JUNIPER-MIB_jnxOperatingTable_Group',
                                                     'SNA-SDLC-MIB_sdlcPortStatsTable_Group',
                                                     'JUNIPER-IF-MIB_ifJnxTable_Group',
                                                     'IPV6-MIB_ipv6IfStatsTable_Group',
                                                     'RMON-MIB_etherStatsTable_Group',
                                                     'DOT3-OAM-MIB_dot3OamStatsTable_Group',
                                                     'EtherLike-MIB_dot3StatsTable_Group'],
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_83': {NUM_NODES: {NODES.JUNIPER_MX: -1}, USER_ROLES: ["PM_Operator", 'Cmedit_Administrator', "Network_Explorer_Administrator"],
                      'CBS': True, 'ROP_STR': 'ONE_DAY', 'NUM_COUNTERS': 1.0,
                      'MO_CLASS_COUNTERS_INCLUDED': ['IF-MIB_ifTable_Group', 'IP-MIB_ipIfStatsTable_Group',
                                                     'IP-MIB_ipSystemStatsTable_Group',
                                                     'ISIS-MIB_isisCircuitCounterTable_Group',
                                                     'ISIS-MIB_isisPacketCounterTable_Group',
                                                     'ISIS-MIB_isisSystemCounterTable_Group',
                                                     'JUNIPER-FABRIC-MIB_jnxFabricSourceStatisticsTable_Group',
                                                     'JUNIPER-IF-MIB_ifJnxPolTable_Group',
                                                     'JUNIPER-MIB_jnxOperatingTable_Group',
                                                     'SNA-SDLC-MIB_sdlcPortStatsTable_Group',
                                                     'JUNIPER-IF-MIB_ifJnxTable_Group',
                                                     'IPV6-MIB_ipv6IfStatsTable_Group',
                                                     'RMON-MIB_etherStatsTable_Group',
                                                     'DOT3-OAM-MIB_dot3OamStatsTable_Group',
                                                     'EtherLike-MIB_dot3StatsTable_Group']},
            'PM_88': {NUM_NODES: {NODES.FRONTHAUL_6020: -1}, USER_ROLES: ["PM_Operator", "Cmedit_Administrator"],
                      'SYS_DEF_SUB_PATTERN': 'FRONTHAUL-6020 Primary15min System Defined Statistical Subscription'},
            'PM_89': {NUM_NODES: {NODES.FRONTHAUL_6020: -1}, USER_ROLES: ["PM_Operator", "Cmedit_Administrator"],
                      'SYS_DEF_SUB_PATTERN': 'FRONTHAUL-6020 Primary24h System Defined Statistical Subscription'},
            'PM_90': {NUM_NODES: {NODES.ROUTER6675: -1}, USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator",
                                                                      "Cmedit_Administrator"],
                      'CBS': True, 'NUM_COUNTERS': 1.0,
                      'MO_CLASS_COUNTERS_INCLUDED': ['global', 'context'],
                      'MO_CLASS_SUB_COUNTERS_INCLUDED': {"global": ["average_user_mem", "cpu1min", "cpu5min",
                                                                    "cpu5sec", "epochtime", "free_user_mem",
                                                                    "load15min", "load1min", "load5min",
                                                                    "peak_user_mem", "peakcpu5min", "sysuptime",
                                                                    "total_user_mem"],
                                                         "context": ["epochtime", "sysuptime"]},
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_91': {NUM_NODES: {NODES.ROUTER6675: -1}, USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator",
                                                                      "Cmedit_Administrator"],
                      'CBS': True, 'ROP_STR': 'ONE_DAY', 'MO_CLASS_COUNTERS_INCLUDED': ['global', 'context',
                                                                                        'port-history',
                                                                                        'ces-pw-history'],
                      'MO_CLASS_SUB_COUNTERS_INCLUDED': {"global": ["average_user_mem", "peak_user_mem",
                                                                    "total_user_mem"],
                                                         "context": ["epochtime", "sysuptime"],
                                                         "port-history": ["epochtime", "sysuptime"],
                                                         "ces-pw-history": ["epochtime"]}, 'NUM_COUNTERS': 1.0,
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_92': {NUM_NODES: {NODES.MINI_LINK_669x: -1},
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator",
                                   "Cmedit_Administrator"],
                      'CBS': True, 'NUM_COUNTERS': 1.0,
                      'MO_CLASS_COUNTERS_INCLUDED': ['RadioLinkPower_RT', 'EthernetBandwidth', 'SDH_VC12NE_15min',
                                                     'AdaptiveCodingAndModulation_ACM_15min', 'RADIUS_RT',
                                                     'TACACS+_RT', 'ServiceOAM', 'IP_RT', 'PTP_RT', 'UDP_RT',
                                                     'IGMP-MLD-Snooping_RT', 'PDH_15min', 'SDH_MS_MSPNE_15min',
                                                     'ERP_RT', 'EthernetTrafficPerformance', 'SDH_VC12FE_15min',
                                                     'EthernetDelay', 'TCP_RT', 'SDH_VC4NE_15min'],
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_93': {NUM_NODES: {NODES.MINI_LINK_669x: -1},
                      USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator",
                                   "Cmedit_Administrator"],
                      'CBS': True, 'ROP_STR': 'ONE_DAY', 'NUM_COUNTERS': 1.0,
                      'MO_CLASS_COUNTERS_INCLUDED': ['PDH_24h', 'EthernetBandwidth', 'RadioLinkPower_RT',
                                                     'SDH_MS_MSPNE_24h', 'IGMP-MLD-Snooping_RT', 'RADIUS_RT',
                                                     'TACACS+_RT', 'SDH_VC12FE_24h', 'IP_RT', 'PTP_RT', 'UDP_RT',
                                                     'SDH_VC12NE_24h', 'AdaptiveCodingAndModulation_ACM_24h', 'ERP_RT',
                                                     'EthernetTrafficPerformance', 'EthernetDelay', 'TCP_RT',
                                                     'ServiceOAM'],
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_95': {NUM_NODES: {NODES.ROUTER6672: 40}, USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator",
                                                                      "Cmedit_Administrator"], 'NUM_COUNTERS': 1.0,
                      'ROP_STR': 'ONE_MIN', 'MO_CLASS_COUNTERS_INCLUDED': ['global', 'context', 'port-history',
                                                                           'ces-pw-history'],
                      'MO_CLASS_SUB_COUNTERS_INCLUDED': {"global": ["average_user_mem", "peak_user_mem",
                                                                    "total_user_mem"],
                                                         "context": ["epochtime", "sysuptime"],
                                                         "port-history": ["epochtime", "sysuptime"],
                                                         "ces-pw-history": ["epochtime"]},
                      'DEFINER': "STATISTICAL_SubscriptionAttributes"},
            'PM_96': {NUM_NODES: {NODES.ROUTER6675: 40}, USER_ROLES: ["PM_Operator", "Network_Explorer_Administrator",
                                                                      "Cmedit_Administrator"],
                      'ROP_STR': 'ONE_MIN', 'NUM_COUNTERS': 1.0, 'DEFINER': "STATISTICAL_SubscriptionAttributes",
                      'MO_CLASS_COUNTERS_INCLUDED': ['global', 'context', 'port-history', 'ces-pw-history'],
                      'MO_CLASS_SUB_COUNTERS_INCLUDED': {"global": ["average_user_mem", "peak_user_mem",
                                                                    "total_user_mem"],
                                                         "context": ["epochtime", "sysuptime"],
                                                         "port-history": ["epochtime", "sysuptime"],
                                                         "ces-pw-history": ["epochtime"]}},
            'PM_99': {NUM_NODES: {NODES.SCU: -1}, USER_ROLES: ["PM_Operator", "Cmedit_Administrator"],
                      'NUM_COUNTERS': 1.0, 'DEFINER': "STATISTICAL_SubscriptionAttributes"}
        },
        "reparenting": {},
        "secui": {
            'SECUI_01': {'NUMBER_OF_SECURITY_ADMINS': 10, 'NUMBER_OF_USERS_TO_CREATE': 25,
                         'NUMBER_OF_ROLES_TO_ASSIGN': 5, 'THREAD_QUEUE_TIMEOUT': 2 * 60 * 60,
                         USER_ROLES: SECUI_01_USER_ROLES},
            'SECUI_03': {SCHEDULED_TIMES_STRINGS: ["00:00:00"]},
            'SECUI_12': {NUM_USERS: 1, USER_ROLES: ["SECURITY_ADMIN"], SCHEDULE_SLEEP: 60 * 15,
                         "USER_NAME": "RemoteUser_01",
                         "USER_PASSWORD": "RemotePassword_01", "authType": "REMOTEAUTHN", "remoteAuthProfile": "STANDARD",
                         "baseDN": "dc=acme,dc=com", "ldapConnectionMode": "LDAP", "userBindDNFormat": "uid=$user",
                         "bindDN": "cn=extldapadmin,ou=people,dc=acme,dc=com", "bindPwd": "Externalldapadmin01",
                         "NETWORK_TYPE": "5k", "INTERVAL_DURATION": 24, "INITIAL_EXPIRATION": "01:00",
                         "CUSTOM_USER_ROLES": ["ACME_PKI_Operator", "ACME_NodeSecurity_Operator",
                                               "ACME_SecGW_Operator"],
                         "CUSTOM_TARGET_GROUPS": ["ACMENORTH", "ACMESOUTH", "NORTH"], "USER_AUTH_MODE": "remote",
                         "FEDERATED_USER_NAME": "fedacmeenduser2"}
        },
        "sev": {
            'SEV_01': {NUM_USERS: 5, USER_ROLES: ["SEV_Administrator", "SEV_Operator"], NUM_NODES: {NODES.ESC: 5},
                       NODE_FILTER: {NODES.ESC: {"node_version": ["22.Q3"]}}, SCHEDULE_SLEEP: 60 * 15,
                       CHECK_NODE_SYNC: True},
            'SEV_02': {NUM_USERS: 5, USER_ROLES: ["SEV_Administrator", "SEV_Operator"], NUM_NODES: {NODES.ESC: 5},
                       SCHEDULE_SLEEP: 60 * 15}
        },

        "shm": {
            'SHM_SETUP': {NUM_NODES: {NODES.ROUTER6672: -1, NODES.MINILINK_6352: -1, NODES.MINI_LINK_Indoor: -1,
                                      NODES.ROUTER6675: -1, NODES.MINI_LINK_669x: -1}},
            'SHM_06': {NUM_USERS: 3, TOTAL_NODES: 3, SUPPORTED_NODE_TYPES: [NODES.ROUTER6672, NODES.ROUTER6675],
                       "PIB_VALUES": {"SMRS_ERBS_NoOf_BACKUP_FILES": "2", "SMRS_RadioNode_NoOf_BACKUP_FILES": "2",
                                      "SMRS_Router6672_NoOf_BACKUP_FILES": "2",
                                      "SMRS_Router6675_NoOf_BACKUP_FILES": "2", "SMRS_BSC_NoOf_BACKUP_FILES": "2"},
                       SCHEDULE_SLEEP: 60 * 60, USER_ROLES: ['Shm_Administrator', 'Cmedit_Administrator', 'Scripting_Operator'],
                       EXCLUDE_NODES_FROM: ['SHM_24', 'SHM_40', 'SHM_41', 'SHM_43'], SKIP_SYNC_CHECK: False},
            'SHM_07': {NUM_USERS: 1, NUM_NODES: {NODES.MINI_LINK_Indoor: -1, NODES.MINI_LINK_669x: -1},
                       SCHEDULE_SLEEP: 3000,
                       USER_ROLES: ['Shm_Administrator', 'Network_Explorer_Administrator']},
            'SHM_19': {NUM_NODES: {}, MAX_NODES_TO_ALLOCATE: 1000, SCHEDULED_TIMES_STRINGS: ["19:00:00"],
                       SCHEDULED_DAYS: ['THURSDAY']},
            'SHM_20': {NUM_NODES: {}, MAX_NODES_TO_ALLOCATE: 1000, SCHEDULED_TIMES_STRINGS: ["19:00:00"],
                       SCHEDULED_DAYS: ['FRIDAY']},
            'SHM_21': {NUM_NODES: {}, SCHEDULED_TIMES_STRINGS: ["19:00:00"], SCHEDULED_DAYS: ['SATURDAY'],
                       MAX_NODES_TO_ALLOCATE: 1000},
            'SHM_23': {'NODES_PER_HOST': 100, NUM_NODES: {NODES.MINI_LINK_Indoor: 1000}, MAX_NODES: 1000,
                       "PIB_VALUES": {"SMRS_MINILINKIndoor_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["02:30:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["03:00:00"]},
            'SHM_24': {'NODES_PER_HOST': 100, NUM_NODES: {NODES.MINI_LINK_Indoor: 500},
                       SCHEDULED_TIMES_STRINGS: ["06:30:00"], EXCLUDE_NODES_FROM: ['SHM_06'], "MLTN_TIMEOUT": 90,
                       NUM_USERS: 1, USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"], SKIP_SYNC_CHECK: False,
                       SCHEDULED_DAYS: ['MONDAY'], 'MAX_NODES': 500, "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_31': {'NODES_PER_HOST': 84, NUM_NODES: {NODES.MINILINK_6352: -1}, "MAX_NODES_TO_ALLOCATE": 500,
                       SCHEDULED_TIMES_STRINGS: ["05:30:00"], NUM_USERS: 1, SCHEDULED_DAYS: ['TUESDAY', 'FRIDAY'],
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"], 'TIMEOUT': 1800,
                       'MAX_NODES': 500, "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       SKIP_SYNC_CHECK: False, "MINIMUM_ALLOWABLE_NODE_COUNT": 500,
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_32': {'FILTERED_NODES_PER_HOST': 100, NUM_NODES: {NODES.MINILINK_6352: 500}, 'MAX_NODES': 500,
                       "PIB_VALUES": {"SMRS_MINILINK6352_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["02:00:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["02:30:00"],
                       'TIMEOUT': 1800, NUM_USERS: 1, USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"],
                       "MINIMUM_ALLOWABLE_NODE_COUNT": 500, "MAX_NODES_TO_ALLOCATE": 500},
            'SHM_33': {'NODES_PER_HOST': 100, TOTAL_NODES: 300, SUPPORTED_NODE_TYPES: [NODES.ROUTER6672],
                       'MAX_NODES': 300, NUM_USERS: 1, SCHEDULED_TIMES_STRINGS: ["06:30:00"],
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"],
                       SCHEDULED_DAYS: ['SUNDAY'], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       SKIP_SYNC_CHECK: False, "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_35': {NUM_USERS: 1, NUM_NODES: {NODES.ROUTER6672: -1, NODES.ROUTER6675: -1},
                       SCHEDULED_DAYS: [datetime.datetime.now().strftime('%A').upper()],
                       SCHEDULED_TIMES_STRINGS: ["19:30:00"],
                       SCHEDULE_SLEEP: 604800, USER_ROLES: ["Shm_Administrator", 'SECURITY_ADMIN', "WinFIOL_Operator",
                                                            "FIELD_TECHNICIAN", "Scripting_Operator"] + COM_ROLES,
                       "NODES_PER_CHUNK": 1000},
            'SHM_40': {NUM_USERS: 1, NUM_NODES: {NODES.ROUTER6675: 300}, SCHEDULED_DAYS: ['SUNDAY', 'THURSDAY'],
                       SCHEDULED_TIMES_STRINGS: ["06:30:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["07:00:00"],
                       'NODES_PER_HOST': 20, MAX_NODES: 300, EXCLUDE_NODES_FROM: ['SHM_06'], SKIP_SYNC_CHECK: False,
                       USER_ROLES: ["Shm_Administrator", "Network_Explorer_Administrator"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_41': {'NODES_PER_HOST': 40, TOTAL_NODES: 1000, MAX_NODES: 1000,
                       SUPPORTED_NODE_TYPES: [NODES.ROUTER6675],
                       "PIB_VALUES": {"SMRS_Router6675_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["23:00:00"], EXCLUDE_NODES_FROM: ['SHM_06'],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["23:30:00"]},
            'SHM_42': {'NODES_PER_HOST': 20, NUM_NODES: {NODES.MINI_LINK_669x: 500},
                       SCHEDULED_TIMES_STRINGS: ["03:15:00"],
                       EXCLUDE_NODES_FROM: ['SHM_06'], "MLTN_TIMEOUT": 90, NUM_USERS: 1, MAX_NODES: 500,
                       USER_ROLES: ["Shm_Administrator", "Cmedit_Administrator"], SKIP_SYNC_CHECK: False,
                       'TIMEOUT': 1800, SCHEDULED_DAYS: ['MONDAY', 'WEDNESDAY', 'SATURDAY'],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["03:45:00"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_43': {'NODES_PER_HOST': 40, NUM_NODES: {NODES.MINI_LINK_669x: 1000},
                       "PIB_VALUES": {"SMRS_MINILINKIndoor_NoOf_BACKUP_FILES": "2"},
                       SCHEDULED_TIMES_STRINGS: ["19:00:00"],
                       "SHM_JOB_SCHEDULED_TIME_STRINGS": ["19:30:00"], EXCLUDE_NODES_FROM: ['SHM_06'], MAX_NODES: 1000},
            'SHM_44': {NUM_NODES: {NODES.SCU: 300}, MAX_NODES: 300, SKIP_SYNC_CHECK: True, SCHEDULED_DAYS: ['FRIDAY'],
                       SCHEDULED_TIMES_STRINGS: ["10:30:00"], "SHM_JOB_SCHEDULED_TIME_STRINGS": ["11:00:00"],
                       "PKG_PIB_VALUES": {"SOFTWARE_PACKAGE_LOCK_EXPIRY_IN_DAYS": "1"}},
            'SHM_45': {SCHEDULED_TIMES_STRINGS: ["11:00:00"], NUM_NODES: {NODES.FRONTHAUL_6020: -1},
                       "PIB_VALUES": {"defaultNoOfFilesToKeep": "2"}, 'BACKUP_SIZES': {"FRONTHAUL-6020": "500K"}},
        },
        "top": {}
    }
}
