# ********************************************************************
# Name    : FM Specific Problems
# Summary : Functional module for FM problem codes. Contains an
#           extension list of FM problem codes, e.g. 'Ambient Temperature
#           High'; allows the user to select FM problem to be used
#           in Alarms.
# ********************************************************************

from random import shuffle
from itertools import cycle
from enmutils.lib import log

SPECIFIC_PROBLEMS = ['Alarm Indication Signal - P',
                     'Alarm Indication Signal - P',
                     'Alarm Indication Signal - V',
                     'Ambient Temperature High',
                     'Ambient Temperature High',
                     'Ambient Temperature High',
                     'Ambient Temperature High',
                     'Ambient Temperature Unacceptable',
                     'Ambient Temperature Unacceptable',
                     'Ambient Temperature Unacceptable',
                     'Ambient Temperature Unacceptable',
                     'AU3 Alarm Indication Signal',
                     'AU3 Loss of Pointer',
                     'AU4 Alarm Indication Signal',
                     'AU4 Loss of Pointer',
                     'Auto-Configuration of Board Not Possible',
                     'Auto-Configuration of Board Not Possible',
                     'Auto-Configuration of Board Not Possible',
                     'Automatic CV Creation Failed',
                     'Auxiliary Unit Processor HW Fault',
                     'Auxiliary Unit Processor SW Fault',
                     'BFD Session Fault',
                     'Board Overheated',
                     'Clock Calibration Expiry Soon',
                     'Cluster Member Unavailable',
                     'Configuration Version Corrupt',
                     'Connection to Default Router Lost',
                     'Connection to Default Router Lost',
                     'Connectivity RDI - P',
                     'Connectivity RDI - P',
                     'Connectivity RDI - V',
                     'Contact to Default Router 0 Lost',
                     'Contact to Default Router 1 Lost',
                     'Contact to Default Router 2 Lost',
                     'Contact to DNS Servers Lost',
                     'Control Inter-Switch Link Cabling Fault',
                     'Control Inter-Switch Link Degraded',
                     'Control Inter-Switch Link Fault',
                     'Credentials Enrollment Fault',
                     'Credentials Validity Fault',
                     'Denib Device Configuration Fault',
                     'DHCP Lease Expiry',
                     'DHCP Server Fault',
                     'Disk Volume C Full',
                     'Disk Volume D Full',
                     'DNS Server Redundancy Fault',
                     'DU Cabling Fault',
                     'Duplicate IP Address Fault',
                     'Duplicate IP Address Fault',
                     'Duplicate IP Address Fault',
                     'Duplicate IP Address Fault',
                     'Duplicate IP Address Fault',
                     'Duplicate IP Address Fault',
                     'Emergency Unlock of Software Licensing',
                     'Equipment Protection Hardware Fault',
                     'ET Hardware Fault',
                     'ET IP Hardware Fault',
                     'Ethernet Port Congestion',
                     'Ethernet Port Degraded',
                     'Ethernet Port Fault',
                     'Ethernet Port Overload',
                     'Ethernet Switch Fault',
                     'Ethernet Switch Module Port Degraded',
                     'Ethernet Switch Port Congestion',
                     'Ethernet Switch Port Fault',
                     'Ethernet Switch Port Overload',
                     'Ethernet Sync Ref ESMC PDUs Missing',
                     'Failure of Protocol',
                     'Failure of Protocol',
                     'Fan Air Temperature Extremely High',
                     'Fan Air Temperature High',
                     'Fan Ambient Temperature High',
                     'Fan Ambient Temperature Low',
                     'Fan Ambient Temperature Sensor Failure',
                     'Fan Ambient Temperature Too High',
                     'Fan Ambient Temperature Too Low',
                     'Fan Contact Fault',
                     'Fan HW Fault',
                     'Fan Power Redundancy Fault',
                     'Fan Supervision Failure',
                     'Fan Supervision Redundancy Fault',
                     'Fan SW Fault',
                     'Fan to Fan Cable Fault',
                     'Far-End Protection Line Failure',
                     'Fast Ethernet Link Fault',
                     'File System Diagnostic Error',
                     'Gigabit Ethernet Link Fault',
                     'Gigabit Ethernet Link Redundancy Fault',
                     'GPS Out Loss of Time',
                     'Hardware Failure Imminent',
                     'HD Stack Configuration Fault',
                     'HD Stack Configuration Fault',
                     'HD Stack Configuration Fault',
                     'HD Stack Configuration Fault',
                     'HG Alarm Indication Signal',
                     'HG Backward Alarm Indication Signal',
                     'HG Receive',
                     'IMA Config Aborted at Far End',
                     'IMA Group Blocked at Far End',
                     'IMA Group Configuration Aborted',
                     'IMA Group Insufficient Links',
                     'IMA Group Insufficient Links at Far End',
                     'IMA Group Start-Up at Far End',
                     'IMA Group Timing Mismatch',
                     'IMA Link Out of Delay Synchronization',
                     'IMA Link Reception Misconnected',
                     'IMA Link Reception Unusable at Far End',
                     'IMA Link Transmission Misconnected',
                     'IMA Link Transmit Unusable at Far End',
                     'Inter-PIU Link Fault',
                     'Inter-PIU Link Fault',
                     'Invalid Ethernet Optical Module',
                     'Invalid Optical Module',
                     'Large Number of Counters',
                     'Left Fan Stopped',
                     'License Key File Fault',
                     'License Key for Feature Missing',
                     'License Mismatch', 'Local AA DB Fault',
                     'Local AA DB Installation Fault',
                     'Looped Link',
                     'Looped Link',
                     'Looped Link',
                     'Looped Link',
                     'Looped Link',
                     'Loss of Cell Delineation',
                     'Loss of Cell Delineation on IMA Link',
                     'Loss of Frame',
                     'Loss of HPTSI Sync Reference',
                     'Loss of IMA Frame',
                     'Loss of Link Redundancy Group 0',
                     'Loss of Link Redundancy Group 1',
                     'Loss of Link Redundancy Group 2',
                     'Loss of Link Redundancy Group 3',
                     'Loss of Pointer - P',
                     'Loss of Pointer - P',
                     'Loss of Pointer - V',
                     'Loss of Signal',
                     'Loss of Switch Redundancy Plane A',
                     'Loss of Switch Redundancy Plane B',
                     'Loss of Sync over CPRI Connections',
                     'Loss of Synch Reference Redundancy',
                     'Loss of System Clock',
                     'Loss of System Clock Redundancy',
                     'Loss of Tracking',
                     'M3UA Association Congested',
                     'M3UA Association Congested',
                     'M3UA Association Down',
                     'M3UA Local AS Down',
                     'M3UA Remote AS Down',
                     'M3UA Remote SP Down',
                     'MAU Ethernet Connectivity Down',
                     'Maximum Number of Counters Exceeded',
                     'Medium Access Unit Fault',
                     'Member Identity Not Unique',
                     'MS Alarm Indication Signal',
                     'MS Degraded Signal',
                     'MS Excessive Bit Error Rate',
                     'MS Remote Defect Indication',
                     'MTP3b Link Out of Service',
                     'MTP3b Link Out of Service',
                     'MTP3b Link Out of Service',
                     'MTP3b Link Out of Service',
                     'MTP3b Route Set Unavailable',
                     'Network Synch Time from GPS Missing',
                     'Network Synch Time from GPS Missing',
                     'NGSM Configuration Fault',
                     'NTP Server Reachability Fault',
                     'NTP System Time Sync Fault',
                     'NTP System Time Sync Fault',
                     'NTP System Time Sync Problem',
                     'OSPF - Working Mode Disabled',
                     'Packet Server Availability Fault',
                     'Packet Server Availability Fault',
                     'Password File Fault',
                     'Payload Mismatch - P',
                     'Payload Mismatch - P',
                     'Payload Mismatch - V',
                     'Payload RDI - P',
                     'Payload RDI - P',
                     'Payload RDI - V',
                     'PDH Alarm Indication Signal',
                     'PDH Alarm Indication Signal',
                     'PDH Alarm Indication Signal',
                     'PDH Alarm Indication Signal',
                     'PDH Alarm Indication Signal',
                     'PDH Degraded Signal',
                     'PDH Degraded Signal',
                     'PDH Degraded Signal',
                     'PDH Degraded Signal',
                     'PDH Degraded Signal',
                     'PDH Loss of Frame',
                     'PDH Loss of Frame',
                     'PDH Loss of Frame',
                     'PDH Loss of Frame',
                     'PDH Loss of Frame',
                     'PDH Loss of Signal',
                     'PDH Loss of Signal',
                     'PDH Loss of Signal',
                     'PDH Loss of Signal',
                     'PDH Loss of Signal',
                     'PDH Remote Defect Indication',
                     'PDH Remote Defect Indication',
                     'PDH Remote Defect Indication',
                     'PDH Remote Defect Indication',
                     'PDH Remote Defect Indication',
                     'PDH RNCI',
                     'PDH RNCI',
                     'PIU Device General Problem',
                     'PIU Device Hardware Fault',
                     'Plug-In Unit General Problem',
                     'Plug-In Unit HW Failure',
                     'Plug-In Unit Synch Hardware Fault',
                     'Power Failure Left Slot',
                     'Power Failure Right Slot',
                     'Power Feeding Fault',
                     'Power Feeding Fault',
                     'Radio Clock in Frequency Holdover',
                     'Radio Clock in Time Holdover',
                     'Real Time Security Event Log Fault',
                     'Remote Defect Indication on IMA Link',
                     'Remote IP Address Unreachable',
                     'Right Fan Stopped',
                     'SCB System Clock Path HW Fault',
                     'SCCP Remote Subsystem Unavailable',
                     'Security Level Fault',
                     'Server RDI - P',
                     'Server RDI - P',
                     'Server RDI - V',
                     'Signed Software Problem',
                     'Slave TU Out of Synchronization',
                     'SPM General Problem',
                     'SPM High Temperature',
                     'SPM HW Failure',
                     'SS7 Cluster Configuration Duplicated',
                     'SS7 Cluster Configuration Duplicated',
                     'SS7 Cluster Configuration Duplicated',
                     'SS7 Cluster Configuration Duplicated',
                     'SS7 Stack Overloaded',
                     'SS7 Stack Overloaded',
                     'SS7 Stack Overloaded',
                     'SS7 Stack Overloaded',
                     'Subrack Power Configuration Fault',
                     'Switch Core Fault',
                     'Switch DBM PLL Tuning Fault',
                     'Switch DBM TUB Detection Fault',
                     'Switch Internal Link Fault',
                     'Switch Internal Link Group 0 Fault',
                     'Switch Internal Link Group 1 Fault',
                     'Switch Internal Link Group 2 Fault',
                     'Switch Internal Link Group 3 Fault',
                     'Switch Internal Link Port Fault',
                     'Switch Internal Link Port Fault',
                     'Switch Plane A Fault',
                     'Switch Plane B Fault',
                     'Switch Port Fault',
                     'Switching Discards due to Errors',
                     'SXB System Clock Path HW Fault',
                     'Sync Ref 1000BASE-T Not Slave',
                     'Sync Ref Quality Level Too Low',
                     'Sync Reference Excessive Wander',
                     'Sync Reference PDV Problem',
                     'Synch Reference Not Reliable',
                     'Synch Reference Path HW Fault',
                     'System Clock Distribution HW Fault',
                     'System Clock in Holdover Mode',
                     'System Clock Quality Degradation',
                     'Trace Identifier Mismatch - P',
                     'Trace Identifier Mismatch - P',
                     'Trusted Certificate Fault',
                     'Trusted Certificate Installation Fault',
                     'TU Hardware Fault',
                     'TU Oscillator Temperature Fault',
                     'TU Synch Reference Loss of Signal',
                     'TU System Clock Path HW Fault',
                     'TU11 Alarm Indication Signal',
                     'TU11 Loss of Pointe',
                     'TU12 Alarm Indication Signal',
                     'TU12 Loss of Pointer',
                     'Unequipped Defect - P',
                     'Unequipped Defect - P',
                     'Unequipped Defect - V',
                     'Unit Contact Fault',
                     'Unit Hardware Fault',
                     'Unit Hardware Fault',
                     'Unit Hardware Fault',
                     'Unit Missing',
                     'Unit Missing',
                     'Unit Missing',
                     'Upgrade Package Corrupt',
                     'User-Defined Profiles File Error',
                     'VC ete Alarm Indication Signal',
                     'VC ete Alarm Indication Signal',
                     'VC ete Alarm Indication Signal',
                     'VC ete Alarm Indication Signal',
                     'VC ete Loss of Connectivity',
                     'VC ete Loss of Connectivity',
                     'VC ete Loss of Connectivity',
                     'VC ete Loss of Connectivity',
                     'VC ete Remote Defect Indication',
                     'VC ete Remote Defect Indication',
                     'VC ete Remote Defect Indication',
                     'VC ete Remote Defect Indication',
                     'VC11 Degraded Signal',
                     'VC11 Payload Mismatch',
                     'VC11 Remote Defect Indication',
                     'VC11 Unequipped Defect',
                     'VC12 Degraded Signal',
                     'VC12 Payload Mismatch',
                     'VC12 Remote Defect Indication',
                     'VC12 Trace Identifier Mismatch',
                     'VC12 Unequipped Defect',
                     'VC3 Degraded Signal',
                     'VC3 Loss of MultiFrame',
                     'VC3 Payload Mismatch',
                     'VC3 Remote Defect Indication',
                     'VC3 Trace Identifier Mismatch',
                     'VC3 Unequipped Defect',
                     'VC4 Degraded Signal',
                     'VC4 Loss of MultiFrame',
                     'VC4 Payload Mismatch',
                     'VC4 Remote Defect Indication',
                     'VC4 Trace Identifier Mismatch',
                     'VC4 Unequipped Defect',
                     'VP ete Alarm Indication Signal',
                     'VP ete Loss of Connectivity',
                     'VP ete Remote Defect Indication']


def update_com_ecim_parameters(event_type, probable_cause):
    """
    Loops through all the event types and probable causes to use all possible values.
    Total probable causes are 26 and total of event types are 11
    :type event_type: int
    :param event_type: list of enm_node.BaseNode objects on which to issue the netsim command
    :type probable_cause: int
    :param probable_cause: list of enm_node.BaseNode objects on which to issue the netsim command
    :rtype: tuple
    :returns: event type and probable cause
    """
    if probable_cause == 26:
        if event_type == 11:
            event_type = 1
            probable_cause = 0
        else:
            event_type += 1
            probable_cause = 0
    else:
        probable_cause += 1
    return event_type, probable_cause


def get_specific_problem_iterator():
    """
    Returns iterator of all problems
    :returns: iterator of specific problems
    :rtype: iterator
    """
    shuffle(SPECIFIC_PROBLEMS)
    return cycle(SPECIFIC_PROBLEMS)


def map_nodes_for_profile(nodes):
    """
    Prints summary of node counts
    :type nodes: list
    :param nodes: list of enm_node.BaseNode objects on which to issue the netsim command
    :return: node types and their counts from the list of nodes assigned to the profile
    :rtype: dict
    """
    ne_types = [getattr(node, "NE_TYPE", node.primary_type) for node in nodes if node]
    node_type_count = {ne_type: ne_types.count(ne_type) for ne_type in set(ne_types)}
    log.logger.info("Nodes used in profile: {0}".format(str(node_type_count)))
    return node_type_count
